apiVersion: v1
kind: Secret
metadata:
  name: truenas-exporter-secret
stringData:
  TRUENAS_API_KEY: ENC[AES256_GCM,data:PuWIDXhESSZSGHVxbh+ZU/u1uZU/p/0ylHeeCh5GP3hqjPulBchE4904TRxOGjKCKCccJ2ysLDKu2sQOyiOYHa+R,iv:cY8HZqO2nyt1+wAYAHAYbq+Xs2oL0q7IqymSrOi+6Og=,tag:7oY9NSxZnHj5F8GFkxHxvg==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQXkxWFdwbUMrWkZ0ZTJR
        dTVrMGxKNklXQlR3OW5Ob1ZMZXVQVUsrMFRnCitaOXcyWFVCS2JwVllBVFYrcXo0
        SkxZMW5VZzltZUVya3UzQzBUZCtkU0UKLS0tIGNwN2hNZnoxc1plZnFrTzJHOFg1
        dzFvVzA0NUJuampmQTB3aXFzS0RnWWsKdFmG6l4cooNke7NtW1THgochAcWwsxDP
        Tu+K+PJyIX2oZUvcwGde/hAlNwCbWV0umKsEDsoFNF58S7HLcdqpOQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T15:15:52Z"
  mac: ENC[AES256_GCM,data:f8wSqaTPJz77PLNGqSb6lFXgENZyx5YNnhEqn/jF5jP23bhwYrY13+oEFpYCGd0/vTCg693RZVwBHKZRH25zfVl5yUOm3vd9xO584roYXxl6u8oApT9TyfZjhfinQ5gJIX+/wsmyhH+u3nYdK+kdjRcmiY/4o750EgcXzsJpbBc=,iv:77JpayqA+YbVDYpa5AiRZwNuZ+tkjfOb1Zy1IavmzUQ=,tag:cU+U5NiACFk1m3ng/4jidg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
