apiVersion: v1
kind: Secret
metadata:
  name: garage-secret
stringData:
  GARAGE_RPC_SECRET: ENC[AES256_GCM,data:rJJ+8ESp1Toyq5JjZJWS70YFCHro2yVRsMJrU1KElBUjAZ7VwnNHy0mRtu6dMtLy9oC1m5XTbtJGV7hq8bUMiA==,iv:WK5UXxGJ7UXnemrchuOJVa4ODnABryit9PEuZ578UFs=,tag:amUgpeu4jpvcjzl6zuAo/Q==,type:str]
  GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:dbtqFABtZdy+USZ6ZCe3O40slgUdZW8OqqAZ97IJ1rfxjulwEd90Gt9nSd43tf94YYkBYU7VmacSN5rq9XAR+A==,iv:HOO0KqcTlf0KDUDFBhonVvhFdOJXrVyTlAIaszKRlHk=,tag:jkS8VYXgDbsdr84EYeZpqA==,type:str]
  GARAGE_S3_KEY_ID: ENC[AES256_GCM,data:CL6cxOt7b8nZiHhBexNuCIsiUkVeGgi5aYY=,iv:nDbUrVBajr3hTGc912ZLGy8ZScKPcXjv+lUimXlcybM=,tag:x4hbLO5HH9BZCTlUt5EQyw==,type:str]
  GARAGE_S3_SECRET_KEY: ENC[AES256_GCM,data:FOy1Cc1p3cQVh2FvnzWms3QU4vbcR18y1CTGXiqdANoPf0jlByTOBp5wKmCOjxR1RMDRHj07p2yhDZf2/56CoA==,iv:hJeHkWWpFtFvQOS35DZH45+GZi8kFkByNNBr3mIjUTQ=,tag:pAi/yVK8xaU9dHSWo6fWdA==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWk1IMzBCUjBqVVVMWXk2
        UUREVzV4QU80bmdBaXVSaUVLMkwvMEsyM21zCjY0QkhBazh6VjN3UWRaN1JwZmRF
        L05BVE1na1U5MVIweEpENXpJcjc5aG8KLS0tIEVnU05NNUlFNHZ5S0FCeTRIUnYy
        dEQ2TlNCOTJNSHpWd2NuQnQydE82Qm8Kaag9a5/AHKm+DfCHPvDwfZ5IS5MgR5kC
        1pZbqFvc7QAmSpAff9OhPYMdU/VJdNDSK3UO2uPwE7zpsF7XjAOq6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-05T23:10:33Z"
  mac: ENC[AES256_GCM,data:69EczrjfqTYFINm/hY1QnhW4s6LBHZNBC1eSVchh9SnRaeL0TS5cZCZL5ZVRGv65pGn7N82M8BENSGOoRqQ6VXG28sW/x6O55mK6Xp0PEJqkvfNqmF6mzDrPPCKrSwdMxwd/T8DYsNvfO0YI7r9Aor91ba7xZRZxEmxAb0vFJoQ=,iv:kAY4KsW8fhnjgbf818yLh816hozziwNXeFKIqqUxxxg=,tag:7geRe5mIf7QaZeW0rZ1Q0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
