---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: garage-data
spec:
  sourcePVC: data-garage-0
  trigger:
    schedule: "0 * * * *"
  kopia:
    accessModes:
      - ReadWriteOnce
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 5Gi
    cacheStorageClassName: iscsi
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    moverVolumes:
      - mountPath: repository
        volumeSource:
          nfs:
            path: /mnt/tank/homelab/kopia
            server: 192.168.5.40
    parallelism: 2
    repository: garage-volsync-secret
    retain:
      hourly: 24
      daily: 7
    storageClassName: iscsi
    volumeSnapshotClassName: iscsi
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: garage-meta
spec:
  sourcePVC: meta-garage-0
  trigger:
    schedule: "0 * * * *"
  kopia:
    accessModes:
      - ReadWriteOnce
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 2Gi
    cacheStorageClassName: iscsi
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    moverVolumes:
      - mountPath: repository
        volumeSource:
          nfs:
            path: /mnt/tank/homelab/kopia
            server: 192.168.5.40
    parallelism: 2
    repository: garage-volsync-secret
    retain:
      hourly: 24
      daily: 7
    storageClassName: iscsi
    volumeSnapshotClassName: iscsi
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: garage-data-dst
  labels:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: restore-once
  kopia:
    accessModes:
      - ReadWriteOnce
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 5Gi
    cacheStorageClassName: iscsi
    capacity: 50Gi
    cleanupCachePVC: true
    cleanupTempPVC: true
    copyMethod: Snapshot
    enableFileDeletion: true
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    moverVolumes:
      - mountPath: repository
        volumeSource:
          nfs:
            path: /mnt/tank/homelab/kopia
            server: 192.168.5.40
    repository: garage-volsync-secret
    sourceIdentity:
      sourceName: garage-data
    storageClassName: iscsi
    volumeSnapshotClassName: iscsi
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: garage-meta-dst
  labels:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: restore-once
  kopia:
    accessModes:
      - ReadWriteOnce
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 2Gi
    cacheStorageClassName: iscsi
    capacity: 1Gi
    cleanupCachePVC: true
    cleanupTempPVC: true
    copyMethod: Snapshot
    enableFileDeletion: true
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    moverVolumes:
      - mountPath: repository
        volumeSource:
          nfs:
            path: /mnt/tank/homelab/kopia
            server: 192.168.5.40
    repository: garage-volsync-secret
    sourceIdentity:
      sourceName: garage-meta
    storageClassName: iscsi
    volumeSnapshotClassName: iscsi
