apiVersion: v1
kind: Secret
metadata:
  name: garage-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:9Yu4/Bo98RdF+omWaFf3/dzdpv2zWxuM9BHY6lgnb1tXM+peu1I5ES082A==,iv:JwxQs2ECFlBTv2PwIreq3AS+atskbYcZkcBSqwZ4mVk=,tag:msvBfjgjrO7T/rqIJrmEqA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:ocL7CZ8IdcuLkGkH1/wsoRFVxPX2hjgYxP1gYg==,iv:SjTPSxUbCVaL9hG4l4LBIDExoQPQFL2xSVZ+K3DUk+s=,tag:QU3+G28VJvDMj17mY6cjkg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMHlKRHg3UmVzQlQvYzhF
        bzl6VmtESEVkUEh5M0RCNHBFeTF0UnkzcUZRCjBhRE01YlVKSUJHanBCVjM3Q1Zl
        T1FWOGZkUktBY2lQZk5uN2F3NW16NXcKLS0tIE0wTld1MEtxUUZCUVNUcFl6T1Ns
        OHIrdmlkaGZmZ0l4dll2a0ZVTVI2VU0Kqu2Ul9W+hN29HfbCvbGqqcC2Cs/2/ZJd
        G2C5+teK4SPNRbb5rx49HTTzw3k+0Tabdi6Hw9LTvukXujW1SPPdxw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T17:50:54Z"
  mac: ENC[AES256_GCM,data:fd1kp49hHg/c8XD5G9+sDSlRyRlAom7l8DLaQ3FnVpgF3DBGqkP2iNcofPwzk4fTgKO0u01fa5/dFYKVfRyfrH6zKZ/8Gig5eJ6/w/z5afRrHPJzq07OsjZrSDuzmvTDeTZXWzlmgTLTu8S1ejCs9IcgmQF9i5HWyPSgUh2SNFQ=,iv:btv/tbZ8DiWpfDYEjmGtTJ2cTbPK7+gdQhCkQcUoTsk=,tag:ebGI3sDMNmI/fgCfFVz3/w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
