apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-gluetun-secret
stringData:
  wg0.conf: ENC[AES256_GCM,data:qsrqFLAXY5XypdZZ/E+n2Hr95LvrM2gu0W5k2XLmyAgIeokyoTRIpw3tknbKiUD/bLUXlx97Gw9CjdIio1dCVXpPL47mqoXy0aPVlTug5Y1rVn9ojzS+W5k0744gZhKjGS26W5PJMrRWJ7d3lNw87OXoVk+IV2NeFeJBd2sKFYnXBCgQYrukcoZBTqB33PjoAoCRlSOmSQMe80VR7Y6BmeJTqpedZ+hEj7sXZUN/AE8a8FZfMYL30wo+6GlHbH3hjmmto9wWmLYdW6TIEheSNMyLGUC1SGh+1iyii9I2JtTOp3XlOt6bANCHDQVCT3ImJT0OZsfr1P8fLwVU/o/JBH7pDhGI6+by7JQnd2fjfo7fl0G3BnNt14Iy91sMuGKbZsrJMOHgaKg/9Jg/Xh5DOQRQc7wXGYapgnEZvuJ0xEkREM/nYeaAo5GJSGo8dMoTqVo46rRB92yykcj5SwSG0lACKjwKX6xhpQ==,iv:jSlzechwmWWjD6O1hJLMkMSGGwf39lgg6swC9T/67C4=,tag:yz38CafUSNDZxMvACvvZ1Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrciswUDhDYk9wUjhZWG1Z
        Rk92TVkrbEVEL1h5YWJMMEs5cW9KeUlOZ2tZCkRNM056TXg4Mml0dGJmZmtoVW5w
        Y09GNmhzSW16L2FJOS9QWCtTUmtOMFUKLS0tIFJxWnM3UVg3aDFQRGl4V1gzendX
        RVdBTVVlQ3R3U1hBSGZ4YTBZbU9LdXcKSML9eHBSisqMwIOJ0peOXf21oa3C3xXq
        c/wxYpQ6Y14SJSPy+JpS7LIsAEBi41lq8w15yJTFt9reR/QgMG8JbA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-10T17:15:59Z"
  mac: ENC[AES256_GCM,data:+X8mrCnFd38InOXpvFdDO7+Gy3CVTQW5W3X1nlbOnhaM+afA76Jc82a8oRDbBusjX2bDqDCSVaT59VEqqlLXgcZ9jsQHJXFkzgxuSR9GOfxWchWlF9wFcxj2SvgFqvvLKjK74eN9mRUTLSgIITfs6YAx/IurUeWzoXaaEk6PRds=,iv:PostpuSzP1f+c91sB1zglPtgOoKp9dC10fGOqUuZc5g=,tag:pOBdr85+EU4q/Q3zx20K+Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
