---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  chartRef:
    kind: OCIRepository
    name: grafana
  interval: 1h
  values:
    fullnameOverride: grafana
    admin:
      existingSecret: grafana-secret
      userKey: admin-user
      passwordKey: admin-password
    defaultDashboardsTimezone: America/Chicago
    route:
      main:
        enabled: true
        hostnames:
          - grafana.securimancy.com
        parentRefs:
          - name: envoy-internal
            namespace: network
    grafana.ini:
      server:
        root_url: https://grafana.securimancy.com
      analytics:
        check_for_updates: false
        reporting_enabled: false
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://kube-prometheus-stack-prometheus.o11y.svc.cluster.local:9090
            access: proxy
            isDefault: true
          - name: Alertmanager
            type: alertmanager
            url: http://kube-prometheus-stack-alertmanager.o11y.svc.cluster.local:9093
            access: proxy
            jsonData:
              implementation: prometheus
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: flux
            orgId: 1
            folder: Flux
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/flux
          - name: kubernetes
            orgId: 1
            folder: Kubernetes
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/kubernetes
          - name: network
            orgId: 1
            folder: Network
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/network
          - name: observability
            orgId: 1
            folder: Observability
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/observability
          - name: system
            orgId: 1
            folder: System
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/system
          - name: unifi
            orgId: 1
            folder: UniFi
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/unifi
    dashboards:
      flux:
        flux-cluster:
          url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/monitoring/configs/dashboards/cluster.json
          datasource: Prometheus
        flux-control-plane:
          url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/monitoring/configs/dashboards/control-plane.json
          datasource: Prometheus
      kubernetes:
        kubernetes-api-server:
          # renovate: depName="Kubernetes / System / API Server"
          gnetId: 15761
          revision: 19
          datasource: Prometheus
        kubernetes-coredns:
          # renovate: depName="Kubernetes / System / CoreDNS"
          gnetId: 15762
          revision: 18
          datasource: Prometheus
        kubernetes-global:
          # renovate: depName="Kubernetes / Views / Global"
          gnetId: 15757
          revision: 43
          datasource: Prometheus
        kubernetes-namespaces:
          # renovate: depName="Kubernetes / Views / Namespaces"
          gnetId: 15758
          revision: 42
          datasource: Prometheus
        kubernetes-nodes:
          # renovate: depName="Kubernetes / Views / Nodes"
          gnetId: 15759
          revision: 36
          datasource: Prometheus
        kubernetes-pods:
          # renovate: depName="Kubernetes / Views / Pods"
          gnetId: 15760
          revision: 36
          datasource: Prometheus
        kubernetes-volumes:
          # renovate: depName="K8s / Storage / Volumes / Cluster"
          gnetId: 11454
          revision: 14
          datasource: Prometheus
      network:
        cilium-agent:
          # renovate: depName="Cilium v1.12 Agent Metrics"
          gnetId: 16611
          revision: 2
          datasource: Prometheus
        cilium-operator:
          # renovate: depName="Cilium v1.12 Operator Metrics"
          gnetId: 16612
          revision: 2
          datasource: Prometheus
        cloudflare-tunnels:
          # renovate: depName="Cloudflare Tunnels"
          gnetId: 17457
          revision: 6
          datasource: Prometheus
        envoy-proxy:
          # renovate: depName="Envoy Proxy"
          gnetId: 11022
          revision: 1
          datasource: Prometheus
        external-dns:
          # renovate: depName="External-dns"
          gnetId: 15038
          revision: 3
          datasource: Prometheus
      observability:
        alertmanager-overview:
          # renovate: depName="Alertmanager / Overview"
          gnetId: 9578
          revision: 4
          datasource: Prometheus
        spegel:
          # renovate: depName="Spegel Monitoring Dashboard"
          gnetId: 22104
          revision: 1
          datasource: Prometheus
      system:
        node-exporter-full:
          # renovate: depName="Node Exporter Full"
          gnetId: 1860
          revision: 37
          datasource: Prometheus
        cert-manager:
          # renovate: depName="Cert Manager"
          gnetId: 20842
          revision: 3
          datasource: Prometheus
      unifi:
        unifi-pdu:
          # renovate: depName="UniFi-Poller: USW PDU Insight"
          gnetId: 23027
          revision: 1
          datasource: Prometheus
        unifi-client-insights:
          # renovate: depName="UniFi-Poller: Client Insights"
          gnetId: 11315
          revision: 9
          datasource: Prometheus
        unifi-network-sites:
          # renovate: depName="UniFi-Poller: Network Sites"
          gnetId: 11311
          revision: 5
          datasource: Prometheus
        unifi-uap:
          # renovate: depName="UniFi-Poller: UAP Insights"
          gnetId: 11314
          revision: 10
          datasource: Prometheus
        unifi-usw:
          # renovate: depName="UniFi-Poller: USW Insights"
          gnetId: 11312
          revision: 9
          datasource: Prometheus
    serviceMonitor:
      enabled: true
