apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc-secret
stringData:
  client-secret: ENC[AES256_GCM,data:k3utbiQrp984zKyq185DQhfHk0tVz1LOC4He07bs1sQ=,iv:rRYXOJ/v9ccH9IqfyXsQr+8zplMdL2XIlxIknbvZwLY=,tag:rzLVW8ZJ2vRpqsCOomgo7A==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXejNCaXlCcXpyS2tGT3Nh
        STcwK0hwZFlJWUNTNEhFdzUvOW1uMVFsUjEwCnYvc1hRNG9ReFBpY05EbUFqWnRQ
        UWt2MEdTeGhneHJ1NWF0V0JOcnc2UWsKLS0tIEZlUGFRNXpsVDJTejZaY01jOXVC
        QlBBend4dmNCdU42aGVEeEZ2UDIwanMKyePxnuU6Nx/9MJh8oXntPmE+/f7v8Zic
        xE7ZO0NlueqvbfX8zGREvgWfeLMO+N8MkgvtebOV2klthaUWmBIdoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T23:28:56Z"
  mac: ENC[AES256_GCM,data:5sCC8gK1tXoEzOxcNvuHD7h9k8tRfuE2XTZbAwpk60+B82d1dJ0O9YlAXLsgjUdP0HHRq+AuGu69Vj6a6bVkZZWE+htWK9Lmm7dFj/9k5+QHjQfkGKvX31gA69/8jzuJIBmojTRhzKCWhhhxlSZcTrHONb/Ve/b83j7m24CHdbE=,iv:HEG9aHHxLpm7x6zONL0o49Kfeq2dJzLLz0LG3fPzp/8=,tag:umMQ2DZsC+IlnVqzJyzlXA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
