apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
stringData:
  admin-user: ENC[AES256_GCM,data:Voot65c=,iv:2fmPlEioUSbKRPas/R6o6G3wqgCpWWzeoLREIcbyYZE=,tag:WLezTEVxovk08MDbJInAPw==,type:str]
  admin-password: ENC[AES256_GCM,data:Y2z/D4JNLKlHsnXyl4VBvpZpokGAtrIlpeb0oqHRFdk=,iv:IC45L8kcZ3hZT5bXBCxVDif4DH9msvMUO+naVEMEO00=,tag:f73JSogcekDaF2a5XAuBZQ==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MElqMTNSYTAwMENkN0Fn
        YStJVVBtZ24rYWlBZjVBSVI3SG9nSjN2dzNjCjlSVXJOMStZY0M5amNKRTZjNXpJ
        cFJoWGhPeVZkN2puQ3NaSzFibFpSRFkKLS0tIEVQRWFEa0dnYlJycHRNbXBTUCsw
        K1FVWXVRNEtGWWN5WHQ0Q0p6azhZUm8KYknBDuW+e12b3SBXDTaf8ZXtQlCIYHWp
        AtLefktFLme4+08zRRWDLlfN1EHS0+cV8Jie9zlRy1wL/v096MTuiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T22:53:27Z"
  mac: ENC[AES256_GCM,data:A8swhBkfES71gyeE2+SQAMbEi5OwRkss515JXOg+OGmxxfxlbVWjRZ/Yk2PtKBoyt8bfifqN3W53/RHaSyS+8VqKYx8TTiRvPbNobAUPJwsW+CZFYRQY087YRojza2O51n+VnL53CVY7QjTvr7ljYBi0UlmV2DGG6vFYj0wSTls=,iv:6DRHueon7WaHmjF+kg6WDEwAcBTC+VVEd7xmRnecPio=,tag:jFXxwIUiIafh3QAUc6p87Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
