apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
stringData:
  admin-user: ENC[AES256_GCM,data:Vi/02NU=,iv:udMUtG1wX+Kd0O4cy/YtypB6mo5lBG3JWOYNXUZHrO4=,tag:mNT3zHnoAabIxLKDek5W2g==,type:str]
  admin-password: ENC[AES256_GCM,data:RPGjNi+kZ/ylohOb0SDECBD2dGQw1RVtUKtfr243OS0=,iv:gQvR6MdtfAp7N+mAfbknVXAHAitZ5EonJk5ACzVrKe0=,tag:wMXR38bQLAnkjgVe8kwMEQ==,type:str]
  GRAFANA_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:j2Rzr6RMieaRZV9VqhHlZ9f4X7PeW321cAffAPIFPV0=,iv:IBullaV+Dly95/cspcVx4lfagiX1WC1dITnhZv5ztr4=,tag:lzTgSatg1/KzBE7LE8kM7g==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeWdPUXRhVkljQzBaQmtV
        YjArV3F4YW9vM1FHWHEzK3ZTWFFtTzRSZmhFCnRnU1JOSk10UmhUOCtiZzVUL3d1
        OWFzaXBxZmZyRWJVczNPcXF4MEhoaXcKLS0tIGJ4UHpXeng1MHQrM240R2FtYzBl
        ZUxZeVdIMUpUQlpzUXdvd2M5Uy8wVlkKvM5WEAicE0riiyUKgNOeorbT2O3Kyquh
        qBSnIZewFxZ3OcbJdmsiKenV9pF5ucn5tAO+CWqmzVt0x+v1EOQ5Hg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-09T15:08:11Z"
  mac: ENC[AES256_GCM,data:egqJp9jO9tAh6us7KMiJJj7u989hj0zKB1EQzEp97YkKsMDgAW0Hq51e9DzvxwxpcsVxkE0uQZEMQQ6xQjEpgY2j5UjS5b5HXYO9wT+PD8YI7lAY5empeFF3KOXpIByrUm0ZB6zA42L5lReukSrrO77uK+qjN7FOi8xLD4xt2/k=,iv:rliSMd5UyknnEx9WWldjHH/83gY1GhQ6y4RweyGFlY0=,tag:Xx7HUWOryxOuIGiyWfK47Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
