---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: volsync-test
spec:
  interval: 1h
  path: ./kubernetes/apps/default/volsync-test/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  dependsOn:
    - name: volsync
      namespace: volsync-system
  postBuild:
    substitute:
      APP: volsync-test
      VOLSYNC_CAPACITY: 2Gi
      VOLSYNC_UID: "1000"
      VOLSYNC_GID: "1000"
  wait: false
