apiVersion: v1
kind: Secret
metadata:
  name: backblaze-exporter-secret
stringData:
  B2_APPLICATION_KEY_ID: ENC[AES256_GCM,data:Cvv62a7qF8ylKFMnbJqr9TmAP/Pg9hRUVv6AzqW5nQ/XibNXbgrIgH4H2T0=,iv:Fv57FuFoV8Qj1LQziwoBDI48EsgA7GXQvnMa//ZHSuI=,tag:H9MjO8mnNHFwBlGN+AcvVA==,type:str]
  B2_APPLICATION_KEY: ENC[AES256_GCM,data:Om1JhUQPBwMNnvIvrzWuSx1O4soKYXzEDD1dM5vaDgI2c9goU7KYe0M=,iv:4CG5stOT8noJ+kq82lpxcjGaWNHZpB1s9h13y9k3MEg=,tag:MDXZvtmAMuFNvjlBEz6/4g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlekZ1QXZSelh1bFRweTFY
        Wk0xRWRXQ0hDazhJdm1Pc0ZDTVBVdGpVTzNFClJ3V2svejlkdDNQMlppU3Ztcm1S
        blg5NDNWVldVejN0K1VuNm56ZmNXdmMKLS0tIGJBRWhLSFhSRzV3a0JnSjU4Z0h6
        c0dGMG42cmlGZ1dpVk5LVWpZSm9yajAKUQHxeZDESQLpSZMbU908qGDmJX2h2XIW
        9ELQWng0g037KS5mQmWAppQswrchAavFfzAPDEPs986BKEjZIwNSAg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-27T18:15:17Z"
  mac: ENC[AES256_GCM,data:WZRZ7NhYJyJByx/sjDrKn9+nw8YJfgTYbhOB161j5OcBwUsUy/fLeOvXjcTqbnOl4mh9LbgTvlQaM/K9ZeqxEzIUx+Dq5rnw2eHCHWGXEo46jpDcjieWjmpGH3FpF0DAWcY7teWTKu4RqVNDht/Ho/z1gkK9sPyI8JKSU5eX+Ys=,iv:Zn19jPYTO95UZemU+X36HEGL+JM2/K3O0+/BHKXRymk=,tag:fr8sNk9fvGsGp69qgOqbgA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
