apiVersion: v1
kind: Secret
metadata:
    name: backblaze-exporter-secret
stringData:
    B2_APPLICATION_KEY_ID: ENC[AES256_GCM,data:VC/WuJtXwp+h52iTXGvUzO+gypDQgh29Dg==,iv:UsB9Pn+A+6ZPVS/YxoWBfO33CyV90XB8qYL+BOHWtWI=,tag:409N+yfbFha+kFgKbrYeYg==,type:str]
    B2_APPLICATION_KEY: ENC[AES256_GCM,data:CSGF1H24CXCTFU+L6Lf069yZavd4BlZfCqGemVKn/g==,iv:eI7lYVkveF5qM97gKDsl3N9tr9ziO6ShfABar+hZ/o0=,tag:KVymHSCeZKAyKg98emwoWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlekZ1QXZSelh1bFRweTFY
            Wk0xRWRXQ0hDazhJdm1Pc0ZDTVBVdGpVTzNFClJ3V2svejlkdDNQMlppU3Ztcm1S
            blg5NDNWVldVejN0K1VuNm56ZmNXdmMKLS0tIGJBRWhLSFhSRzV3a0JnSjU4Z0h6
            c0dGMG42cmlGZ1dpVk5LVWpZSm9yajAKUQHxeZDESQLpSZMbU908qGDmJX2h2XIW
            9ELQWng0g037KS5mQmWAppQswrchAavFfzAPDEPs986BKEjZIwNSAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T14:57:48Z"
    mac: ENC[AES256_GCM,data:dWtJC6Vbb+pAH4l1CIQ2ECc6FCGVPnuKojKmqJO2LS+nFRwZ/9EHVPH6O8HWvC/1c7jOKJycarnxAbgLoQmUsl1O6ZMYp9tqpkwUJrNEiT1w+i/h4MVEcUpD3Wv1rGdxJ7Zt6qJI1wQIZJuWMd21CUcwWIlY2IuCQkfOHbW9+Ss=,iv:sJ4q2AR5DbC8AAcFlZFt9C6C+Tl1diwjT88jf/TovEw=,tag:GvlbNkZfgNUp61HvnXf+8Q==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
