---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: it-tools
spec:
  chartRef:
    kind: OCIRepository
    name: it-tools
  interval: 1h
  values:
    controllers:
      it-tools:
        containers:
          app:
            image:
              repository: ghcr.io/sharevb/it-tools
              tag: 2026.1.4
            env:
              TZ: America/Chicago
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
                ephemeral-storage: 50Mi
              limits:
                memory: 128Mi
                ephemeral-storage: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "tools.securimancy.com"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      tmp:
        type: emptyDir
