---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 18.15.0
    digest: sha256:2e31172b66866ba4c5abc2256f73561b07b2f544f1dbfc62d1d287c33af1b813
  url: oci://ghcr.io/grafana-community/helm-charts/loki
