apiVersion: v1
kind: Secret
metadata:
  name: loki-secret
stringData:
  LOKI_S3_KEY_ID: ENC[AES256_GCM,data:G8xbtvxYlEQt6+tSVYMigQ/jChiy47MXQWA=,iv:8kt6mVvsIUinxlGwO0hWSgvqcm+cSNqj1xKTu1YKQAI=,tag:Ca9KiwlIKYt7nvWpfpQu6Q==,type:str]
  LOKI_S3_SECRET_KEY: ENC[AES256_GCM,data:JlwZQJS2D3oKi96MoBqvg2D8z6ztij+V9zsXnEY2VtXrUzHRFkII4wa27mx3KmMMeXjKH03wpIa7GpWhqasW/g==,iv:pRoQdX65ksLJKrt5BCwDW0GDR0QqX1xyQUkNK2dqOaw=,tag:EDjDD5i43WiJK/P2H8lZ1A==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRnpXVFp3UHUzdzBHZk5r
        RUVqLzRNdmQrMW5hdVpCWVU4bGNWMFBNemg4ClFIU3ZaZGlyUGpVaHR6TzhPbnAv
        MGl1MFE5dDVIR1R4Y3dIMTlid1NGOU0KLS0tIElkb21tazhrOUYvbS8wbVZLSE91
        aDcxelZUelMwTXhvUDRmY3dBMnNZRkkKr1mDKGkUV8hEDNWcRyuWCepjPIojzgYs
        IPF8POm53RM6a9rzIU9FzPbPM1bCvmljMaGs1jOz4/ZnVe1rpv4Zvw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-05T23:10:37Z"
  mac: ENC[AES256_GCM,data:DXRUR6iscI+8WsMpJWWh7NXkm97MdONFYg89uT5XmAyHkyOlFllr0vzygl+V5DWAAE4f2Pp4YieIuqw8xDw/QOyeek9Df0OSuEc1PmdjrcbAJM3ZfXLWw+LYx7SX2WZ8bUPaD9pdbpx+QEog0N6QyNgjsTL1R+P+W7McZouker8=,iv:vwgNp2ovqf0H6yLkBxJm0v25xzND0C95lbe5ALsOsC8=,tag:5JI5matoC9yQZiUbInuKAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
