apiVersion: v1
kind: Secret
metadata:
  name: seerr-secret
type: Opaque
stringData:
  API_KEY: ENC[AES256_GCM,data:IXTT2DOszrctr4noHipgYlqgPrEYlvLL1wgDCL0LMj8=,iv:Gvc2qZzfwyLKg6cQkvUVKr6dssH4TAW5m/UndI0tgLc=,tag:VwScTy1hdGWhhrWxEaIWiQ==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMjRDMDN2QkkwS3NkZjh3
        cGVmWERsa2FOdGh5REFFSUFDY1d4cVFoU25jCmZvcG1qajIwQUZYcmlEWmEzL3gw
        V1c2dFNseHk0a2VJU1p4NkZOUWN5dUUKLS0tIEJ2L3JuemRUamNaR09nckpiQ2R4
        aE9kUm10WERFSFBWVXdZam9RWWkvT0kKhkdeZpTmxIutYth01+KXVVT1GtIUOqrR
        ciKEmtAjMK8LEDX68foyyuJhu9uZAfhhKLU410IxK9Mx6MeRSdbq7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:UOtNisaxK5EwpOfsHnH4sxMmY02la/kUyTIjere8rPa/gbXWQ10nnjEBPjIlehFqZ7Hl9uKeYiGPVTFEIVwn9+7arU0RFnbm9yTgsBP3g02lvaAju48jKr0Em77bcqWuua+aiRjWaLCsSXKDdCUBhU1S3jS5XObwT2tMnslwhq4=,iv:kVLYQhBTWL05iFzBig0I8iyG11ILRd7hEOdYAtG7BVE=,tag:9lKtmoWfg15N/hby37TfXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
