apiVersion: v1
kind: Secret
metadata:
  name: seerr-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:/nV3trgRaxgEpu3cLlAQ9HEPyXB3NzoUphirHLdShjbsmQUs2quYsqw5WnvnqnBYhdUTzJHtK3vJJ0xPUjk3Ng==,iv:tCvG+1Ie/qR1Q79l49kWrbZBZdmD1YamvMnx76ZXyhs=,tag:hbqfnp2Tbdu7ACpdRrQBAQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:uOS0yJs=,iv:GwQCdJMye/zUQycoE3LEeoPq7hN2SYgYVlA71+0bnfI=,tag:8KbNLzwfJpw2fIoTnSapJA==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaUEvcEhmYndKSnN3TU81
        MWNpamhyU3lTUUhnUGNGM3RYQjNxL3E2VEF3CkF4OUI4TTdTQW9tYzJQaXBaSVhw
        MVdEY3FEQVJWUm9HQzlyaEdNaCtRN28KLS0tIHN1U1NxVTZMc1dCNXI1bWF1a2Rq
        Q2FkUkFiTjNoVjR6aXhHVXBjUlZZd3MKrY33SWx6vSvBrtZPI0G1KbMoYC8npcyM
        F0vanc8uSIKXbb2a5Vn4T3yuKURtEp90aGMZQE7ArV9X9pkzPe18Ng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:Ih3NdUTqgeS+jnkLQ/foQa8E0ebVz9V1TIdeGubW590ejHgGK56UnJwtxpM2IzmCqRtzjiHo8jDT7ciVg0g4tXwFjGtUll7j1RkLy4VgV+q3tqgdDB6LwkLqtyLkCD22H9LyxiRmV7E/ng4TWgfwHdqTGbt1+ZOQpROSeG0VkAM=,iv:LN3mHVtGkeVFrCGFdz3rZ+AOtt6WIbC+4uZg3Nc+dTU=,tag:rUn/XqMTQY2uFK4tbWM/sw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
