apiVersion: v1
kind: Secret
metadata:
  name: seerr-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:0JXC0BGNU0T8jJZ4HlkoGAedO13r2ST/S/tdsUtmgZp/DVQ3C8fSDEXaNw==,iv:p1RGzPBBj72Tr1jYg7+UnBHPpcV+mvSG5t8JruF4M34=,tag:YW0a3MFxnfzYeMennO6Lpg==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:4Zdnpd1j+WB1XxV1AHDDyDsAIwgDoZWqXYoysA==,iv:vdLEX2rgGP2RxUkozHo8fbOF8JezzE2RNHtqjdOc2LM=,tag:fWeAYKPSaM4NNNnmGV1JEA==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRWpNVkY4c1BJNnVMN09D
        OTFZa1p3U01XRWRkVUFMdHlKalRRNDRqQkZFCjc4Ti85cC9TbENkWTNxRVhZZGRa
        NjZKUlBYa0JRa2s4dVFMY2Q1bEJqTnMKLS0tIHVyaThaUkxremVEQUFiNjFFOEFI
        YkZqZjVNeTVyMTFYbFdVYkZuM2QwOWcKzrMgkMbxvQHndxHP1XOmR83Bn0ri6cyA
        ojl7oCailHgfkVuBoLG99xQaYoUGnYeOIHbzol2n17aSfXq1/ruEtg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T22:12:31Z"
  mac: ENC[AES256_GCM,data:9NFQof1lx+Lu8wdZZ6zuTDDyb++GIPXWA9DWco7KelwGqnRJDRpS/fm2M4J+uvQqZ5+j4k6BS/cArFa/ZzBcblrEAT30RAPV15Ty6sQabZTObIWJSeJiXVeVJu86iQ1CozHkgj1OeaMRRh8yrooHEggrLXw2BiBaCayqpSBh+zY=,iv:mMKvuCugBZgmJAKDpF3dRKU7JDjeqjrK5T5tGE/aZ50=,tag:9IQBplLm77V+iae40hlwpA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
