apiVersion: v1
kind: Secret
metadata:
  name: homelable-secret
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:UgNTN+UYoFPjNpLSo1V83eUo5ongu/OZm4vgbWMoVgtpEg2BXDQpxReYShCpgaFPCcpO9RRVotaSfx7HwhELxg==,iv:xXRsbeHb7GbtJ9iF6YPy3eLCpTgFyNcXICeyNOfwDFI=,tag:69A6RAqf6/QW6u22bv9gCA==,type:str]
  AUTH_PASSWORD_HASH: ENC[AES256_GCM,data:I3e8GrELG2w/nmc2v/Z1cK0Po92LltctoV/aE52bm1Q4UamgKTV1pWtbAJLS70i8eUbt34WuaVmYrIyw,iv:RePS3CJK+6MY7wnWLUPYhyxxpn4PWmkgHqNXOHNxJ1w=,tag:g7TbbMsfvPdupb0HUGIAdw==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MmtHV2VyWlhhRWk1NGJn
        c3JLWExkdHJIT1AwZHoyM0lVN1lteXVGdTNVClpLVnNuQllXaTFWbXZlUUZrK1N5
        bUxHVTdRZE5NSGVaV20vVnV5MTR1S1kKLS0tIDM0TnNVdGlmaWFhM3FCNDRucCsz
        RWdKY0c4MXNTV3JPQUhsVE1MSDY3dE0K6fGfBHnu3bElMbF+pd7W18X4H2jiyd3p
        3ynm9L/3X8EMAOymsMMJUwOQ57f+XNJNhR9Us+QrS7B29vDCZSUR5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T13:20:52Z"
  mac: ENC[AES256_GCM,data:zK0mcqjJDOkGSg/sfu5/F0u/z0YloHavNARICqXD1POT/X64nC4A4hJqO3erj+alI3Nm7CpwSmGmeI7dd/73P2N3eUkwB2GCxC/vCZ8hhkm4jemT/IaU8STEWHBmkUm90teme8U3rSPnj1coVm5PAyBMqSdZAnUWz34r3uehvXU=,iv:sd3NgvV64zMi2P7dl06rXRH6TENpuH7MvM11u8g3w5k=,tag:v6cl3L6Hz4EAvZ334+16vA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
