---
apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
  - address: 192.168.5.1
searchDomains:
  disableDefault: true
hostDNS:
  enabled: true
  forwardKubeDNSToHost: true
  resolveMemberNames: true
