apiVersion: v1
kind: Secret
metadata:
  name: aws-backup-credentials
  namespace: default
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:8tU4bq79ZHGu0nzcKXYI2761hj9LVHe4xbXvqrWQ642PJAI=,iv:vQ6fgsFu3Lx5Pdk9zdtUuSMQKZzRZNcqBzW2zkzCyTc=,tag:pzB3W1XWPTSNRrUDGI42dQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:MMXyFoxNHqfwX6gDTrj9nXxk7LkvxNmGh6qCP2nUsLkf0q8=,iv:GnaEFZ9OtVf6PPPDBcmvxy5QFuo9pLN5s5WxQVUrg+g=,tag:GvPEd6je2tiGqKESgI0p9w==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:GWr5N6iZ+CAF,iv:Vy8zo0i72bhQ+bpzYjDq9tfxsmMrFX+BmssRLd5DhX0=,tag:t38OAizF/I3+dRoQAISw1Q==,type:str]
  S3_BUCKET: ENC[AES256_GCM,data:wEI24ovGITH79yYqAChMfkmYfYd8sTc=,iv:3iUHelXWazyZuAd6DzxkBkkZCKkrlwpbKfMbcmtac3I=,tag:fyGxdOYI/NtGzGT1VahwEw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZzlsUjBleVVFUU1UUXgy
        Q3Q3a2NPMHZUa1hiNFdJSC9XS2NCYVQ4ZWx3CkI4VTgrYlFtNmZMdlZMYXFRVkEr
        Q1pPNU1rbGJOR0dUY0gvZVd6QS8xejQKLS0tIGdWVEFWRTU3Umkwak9URkp4eHpI
        MU43UVNvRUgyWE9FaWg1MW1MYUlESjAK+uiwaoQlr3zNM2hyq2CfXRiBsLDLjt7o
        3PAA9wwVm1tniNwgXaPPiAp9hjfxtWzLE5/pNzx+wdN811swulTo+g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T15:42:41Z"
  mac: ENC[AES256_GCM,data:ZQyBzJU2yo2mLaS1eKyo7hnFd1Pj8sBNT9nwyXvtKJ+IRNPooDDdkqLULCRsPVDM4a0/ubii7WNCOWV300yPl+fHA+xCCYfJf2nKX6vkT7uCzo431DDZMM/AvogTK6wToffgT86AjeFHwNdhfF7p2h+ImlO7fGKkCgLnj6uZz5E=,iv:YeiaY/h+Ly6gL+auMXrWT6vQt0kqfLgD9lY0LcEh7N0=,tag:jKvk9WMOE7rIrWDfqTTM2g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
