apiVersion: v1
kind: Secret
metadata:
  name: headlamp-admin-kubeconfig
  namespace: o11y
type: Opaque
stringData:
  kubeconfig: ENC[AES256_GCM,data:bFOTacoF0zfk+VTFwfgHr1gYzOch64EffGkEA/AhGpCcwZY=,iv:C0zKKPTLn6WFO/yVKQMpr8DY3ewlVcHRi17fnrxb1VQ=,tag:bFZqrJP2kfXVV39IAczhRQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNFR0MFJ4d2JqMG1PWjNj
        WGsxNFlDVFl3MnZ0djJDeDdmdjJHbjR2V2d3CnNHamFjcStXTVlpNXJITHp5SHh6
        ODkvS0t3MTAwMjUxQWl5cVRUNFloQ2cKLS0tIGpDcFhjczM2SGg5UWxVZHo2VGpD
        RzBja29aRFlRZ2tCQUJnNm4zZW5xazQKa9PbES7ZHA8NTveZdLXSbyaNKJwpl9za
        qGtuUw/db0FM7GHJxVZKOx9AZjZVWl9vD42HmP+UDxj9Kvo3EEamXg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T15:42:41Z"
  mac: ENC[AES256_GCM,data:JWoc7qo5m5l96BXU8TCAw0O6WpjASAYeYBtJNtMEylWeYXXaTAayF1PJGkIymwFNmmGIG/RUItJ03HpF8SsOqhrl58gj3Px5jcsVf1E9zFRuoIuxl6vQjVtmL4sf4nZTDTvBqNMBlrX8HAuZgT+nUJfjwlsr9wqy+FF8UkwQlXE=,iv:L+iz47VxXIskBREcx3L/YIPo6ncYe49PG4KC9oYrfgc=,tag:mge6ph0BHz32R/Jlz/tUyQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
