---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./aws-backup-credentials.sops.yaml
  - ./headlamp-admin-kubeconfig.sops.yaml
  - ./registry-credentials.sops.yaml
  - ./loki-rules.yaml
