apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: media
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:GWobNKHFl4+4hTWbQcV0GKjNLfcuZMP4P9mKsipb9RxxxtSzAyidGkbpB2/88A6IiY1OCQ28hYZjKVKS+pF4m50DJrDzhVJZKev6zUMgg839QRlxGzTMSoTXcsCWBZ9JTK73MutfGmFmGoZz4B2xqFZ8pwb8twR9j5+WHftIF7LuVfoH98Oz/O/VyKKouB735kU0o611cHJQcrxBwEksFaUWVojZNEpWyASTLbu/0Tly9pCEI1xibqpeq/U=,iv:zk50zeFTNqAyXapcIK+Kx7ZZT/AFTaF7uiZRxu+R5Ls=,tag:NeXFgBugH851agJRGy9bEA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhY00vZGpibEtBRWpNTVRW
        MDdUd2FxVGVMdFkzVXdUNWMwMFVReWt4TmhFCmg3QzRZS3RvZVp5SDIxdmw2SzNS
        c3BBV0hjUW54ZHdlU1A3ZkZUQ2E1WGsKLS0tIDh5U1pZWFVPaGhLc09hSVhlRHdX
        RzlEbTFQOTNxclV5UUpOajFXM0YwRUEK8sx+A7iiu2W44BVpDtDOE4wv+c1ZwLWl
        awoaQffe+3uIlXNGyNhvJvMKrmmhExtmaeDxB+IGHYOALdHf3ak9jQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T15:42:41Z"
  mac: ENC[AES256_GCM,data:UHNapyr+2oUb6Caf+VnVO5hHbjP3/uj5N+X87qJqcQlgwr9usGRlc7ihRrO+1pSDzsOEQCk+DK0DPBfINarDG/ldJA9nAQHDEvPvwKg13ED95ccSJ9aw3aIZrFmR+2XMswvIhjmZwVftV3qxHKo58JiiirFGdoLgAMZT3Z/0KvY=,iv:uT493Q9FA/fRTD96O8KNoeEF0uABfFYI6n5V1hRH1Qg=,tag:WMSvpEa0T8AmdrECsZUGFA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
