---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
data:
  settings.yml: |
    use_default_settings: true
    general:
      instance_name: "SearXNG"
      privacypolicy_url: false
      donation_url: false
      contact_url: false
      enable_metrics: false
    server:
      base_url: "https://search.securimancy.com"
      image_proxy: true
      http_protocol_version: "1.1"
    ui:
      static_use_hash: true
      default_theme: simple
      theme_args:
        simple_style: dark
    search:
      safe_search: 1
      autocomplete: "google"
    engines:
      - name: brave
        disabled: false
      - name: duckduckgo
        disabled: false
      - name: google
        disabled: false
      - name: startpage
        disabled: false
      - name: wikipedia
        disabled: false
