apiVersion: v1
kind: Secret
metadata:
  name: searxng-secret
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:y/x/D+NSN2Yo3ny8BpqDSPdjzWnKLaR9RCIEjEvjzFWuhClGWwIbOhqD5W197HIhwYWiDj9BrIzaVl3EY0OoDA==,iv:5XoPLp0nGkHuWhgLcs1sgSWOkBI8gyVYLDEVnHtlsgo=,tag:CLyvSqXdk/fkuI6XiEDm/A==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UEJZeTRLOHdRNllNUnRK
        TXZla2pialpSSTAzVWlrbkxRZkFpamlmMW00CmtzbEFrTlY4S2UxRFpZenhsVi9q
        Vlh3SURidUtOUEk0c2NMVmpuUXQ1K3MKLS0tIDFpM0xhTDR2UWFsNlEwR2xoZmc1
        bVdTVGhkdU10bWpyeDFYVjA3OUpRamMKLU23bGyrffn4iBevXLuUUo1ofFvI0tX0
        54dGhvxxUNpfU5Ra82SKVqUwbVcyBIFCar6C82zav7xKXDfjXp5xwA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T21:41:37Z"
  mac: ENC[AES256_GCM,data:xL2YcaZfy5rbzXfu2icGFan+/Ctk8wB2m7BcZ6Jk5CI+HFiD+lNr4L+2vIXC+yqzh8GhFfLAGfu04cHUDpXBJyFamtGFRNS0X3xYG8q0I95lQCVUhCVLr+uw+TnU/kNZW8k0Ts0Ww+ikfxXrrmJgwg/ylzd3IkE6NrndXyuYL4g=,iv:0RHeiqaPbQsOfiC9ywihVblpPdiCO2NV7ki3e2poYmY=,tag:9WUvi27TYO1xADSnGiLK7A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
