apiVersion: v1
kind: Secret
metadata:
  name: autobrr-secret
type: Opaque
stringData:
  AUTOBRR__SESSION_SECRET: ENC[AES256_GCM,data:OgRRlCyeEjujzH8YgGQUxGAen4T7l4BLDeJEcbB/33R0uR8+i08maZeOhDCuSUvoI1yPd/5yjAMTZM75Puet9Q==,iv:AdFWzme5Fr/VjGSBy03UXUb0idm16UqnUFB77tFL8jU=,tag:S4DSqMWpqFUJaiBap20s+A==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTU5NU1NZR2hxV0RVSUdW
        N1pJTlBHV0YxRm40RUZTNXI0a1ZKclljQVRRCkU3M2JZaThEVHFuZ3RnNGVMV05v
        Q2FNYSsxSGtDSU9xMDBhQWZ0VzhuY2sKLS0tIE9jY05iN0dtWDRJWVVOWVBQeDVS
        U2FhaGRJSFRWT0hLWWRMUGMybm5tUG8K0hEvgZJACySg3g74zVZff5WZN+sceTEP
        ufuDK3Hz/tKhGdjPmHmQgwp35ASKZlco3mN8yQjnNS3dgvFD6vOAkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:tOxOjd0u7cFTPuvX4sE4G67bJ/sLK316qX3UYm/O7yW1lMKBLrGTGFGHyC1muN6hJTFZtV6CVvftOzSWkm2MCuaLyaezLkMv+pcktDrzpGlYQQp+uSHPROftP4re5XrNijk8y+7dw5t/Qi23zZfLhvmrxYODC66a/TBUETKYHBQ=,iv:Us+vUA7evPsgXXoAgecXctQ8tqJp653Zd+1S70cLCm8=,tag:wgenzbCQYM2tsNmRd5Wqnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
