apiVersion: v1
kind: Secret
metadata:
  name: autobrr-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:vIaCt+lh4wy5f7nBCe6nJ7RdbpQygoS99sb3eTlUX/90zukfUPb9J/ccJk4HCuXLnxHvBPnxRN7Br1++31VoTg==,iv:bM4zHh4m+ojP6+Fyx43jFLvh/exbN/5FRC8iSmsOVsM=,tag:6Tg/If6fdUA+W6qQ4vLBZA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:Rm+v2E2XMQ==,iv:j8wO5xU7nhkr1hN5IwaDaCdM3iFWMsZ98zjYcinnnlU=,tag:J1/c16YNAD7jkyMwO80Qmg==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhODZ1dnkrbTBtcmJWL0hG
        b3hPOVFnTThvUXZUc24wVHAwZFhpRWpXRW5rCnFvSkVoTWNnOFBBWkpjekliVEpI
        Unk3cU9XSjFsQUZFbmxKYUhEbnI4NjAKLS0tIFJpaTFVWXFpWjdEQmpSRkl5dHhV
        dE96Y1UyUEwwWGNtMG9iYmpqVUtiRWMKmfUyNWkMJoxF3y4HKKjzxibvnkVzqz9D
        jJNgQ3TC/+7a0MBYJgsZngjU2vpR6ac0hyVsARg0XCDXI38TQz3pdw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:k3CTPDH3iN9ngUAZ2O/8x+6xPoHTzKbH1VY9IJtfdU2dXiHr7rX13ldaLB+lmnGxMMVz94imHbd37kzIMxdvzOPDDDfofAxgIvvLPbhtyF8LdvUtyBiw541jRSslizFv5TALhh29xRT0kx1Z6bG3PAB1yruxgrR+9JWywOI5wBg=,iv:ggmcZlzHiOhAL0HDZzrxJzoVQoMFE12CrCYUelCB1mE=,tag:ulcYDQmIhfncyVfIN84sQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
