apiVersion: v1
kind: Secret
metadata:
  name: autobrr-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:DoYjM8TM6ra5hpXaO4xeS24El+778gchYNoeCaLzgkTmc9LD2ChGfgLI7w==,iv:v+wiG4X4HdreefENeRz6rmC2TrJ3/nvS1LR/kohVw6Q=,tag:xzNd6Mc95TK+elqIVxXU9w==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:iY7ikorhXNR/7C9PItYeiZbR5tQjYaaFyDcssw==,iv:W/SXYZeBHvbRiRiFfrW2m/PgHjVVRmvAqGya8uRgzA0=,tag:jCp1EScl4e8qslDjq40NGA==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaHBoQkZsTUtpMXJGZUQ4
        MUcralZ0eHhoS0hNc0ZWSWJ5U3Q4WE9BZGxFCmNPOFdGNGx4SXZVcHhvQ2picjQr
        bHB1MUdVSkFjQi9kMGtiRjUxY2lDMGcKLS0tIFhQeUlneGQ2dGRHck5WOCtXVTV4
        VEFCc1FGeEdwVlFackcwdjZMZVllTlUKm7448CtZtDm4lhSPP/TEwzQXutvdrsx1
        wMGUw+Ybfd1/SCwyeX02tAxerpHhfhNs30kQzgz3BvFw85wnPapZyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T22:12:30Z"
  mac: ENC[AES256_GCM,data:jsMtHqppZIcWYCvzposevNmfsEAiNw3/IAnC5ib8COksOARX1vnzNrjIEutOZBXjOdhW9Gg9ABxIKFHrd4xIwJ2KTZP8KwU4QzRCRz4ClFX3eQ74a93bslT9st2HvuSpQ0CDPRV44Gjfyw+pMyu37XVqVOlvT9lOjgZEHgz77qw=,iv:miC5MkH3RXebriGRAfa0Y97XQxA15v89UGvylnYwGLI=,tag:VvQ7D6ErIKpv480O5StWtg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
