apiVersion: v1
kind: Secret
metadata:
  name: volsync-test-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:w1wW8Bs3k+1n00VQKDXi2prJ7Lc5i9fwqwFmUO01DPR8cmSJJyh2GcVjNw==,iv:dYzKcn4e5Zzdi+S9iGuRUEL5ai+MjlkCg97njf69dag=,tag:Xaht/KucLR0f+VLqDbIJpg==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:3zc0eGBYxRrtyLwdVYXhKQQbqL5+V+8Yk21n7w==,iv:WGr0fDVfqAFwYzBSN8iI209x4HU/BIN4MyFXp2NovEE=,tag:Y6XxBxK3TXZ4/OFBgKO/kw==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZ1BLQXplSHVDeEsvK2ZU
        WlRHQ2ZiY1RoaTBsODlzOVh0YWpjdGNsT1YwCnBKVTZDMEU0L0pSdytWS0U3aGZD
        QjQyOFZ4Y3krVFFsWmsreXZ2b0RnMG8KLS0tIDZYNjZLc1dKNEJZTHNHYmRyM0No
        eHZGZVFlaUdmeG11S01iRGNScFEvYjQKIbbQQSN9tIuucHp4/y+e0U5jMVvlMxs3
        4cg8j8AgpBct/dSf4LGwoZkpH2+O5qeVyOf7xTssWX/sxY8DyeSfxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T12:22:18Z"
  mac: ENC[AES256_GCM,data:SkysqdEt9+lG1n9QDjzC3CTA4a5QZ2lGJUC43ha4W+iA1SiyPL33C7KMT5kQWwVyG6xm2pGSs9upKs79fgrL4kniT57QDTxXSkjv6kwe4vHdGqv94wHzSFrwA7rTOx6iyh9c8aV3C01F/NQYhCDutg8iVWPpDj5lh6rVKsk6ItY=,iv:Vf17J9823Yjtfim3A9qF8N8ZvySdMxsIUuUZsJjsX1s=,tag:PcEHwJZAqKaL3cwiLmrPYw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
