apiVersion: v1
kind: Secret
metadata:
  name: volsync-test-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:th5mQlxwzpu7yHiNYkPP1S5oqvSgAUHlS/hsgP0MfH0/UUCaIFEWKpuXkA==,iv:bHuu+HXZBMk1hR/1pTgPMOLOoNgmk1elUZ7fr5jx4Fo=,tag:otste1AG/EBTA6LGtR0uuQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:SoeIB0ZTYPY6kFCeaPBEMvxqXdeWgcSniLTqwl7P2P6vBsWzm+4ErIrvVBYYD04rPfnlPcHXlASmzp+msFcZjM3ZY/D3jealfpgg3ZNsGuQN579v3m6zuQ/xipPHeJ5qqpWmXuhPn22BlkP0HzSDcL0zZfXPzXhdzrXyJ5EGQKFRgAfMQ2mbsJk+8M7ejy9do6RHmy0o8ld09a/65M5EugI6eC0AhGulvP00O4HaO5oh5ADQIUSv09/8fxrvHt/DRl8sZmV+PVvEnWtKHavxbXIuFLF8WZ8jXWJ6P5qHSChihiNhXZaQJmpwtqo=,iv:MyA74gcdEm576iqU/i3e91sQ9UxbvjU32RxjcvokGcw=,tag:wSuIiH+TiBJFzK+47BSJ7g==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NHRmdnd1U1c0cUVnKzJF
        c1pkZy9NWjdiaElIb2xrcUowTE5nZU9qUlFZCkJkTFVneitRTkJmQkZmK2NCTDVs
        eEwvRnhsbDkxT3VtZHZTeWFnd0x2aXcKLS0tIE82S0RQMjFJSFpzeElpY08zK0pr
        V1R6TUVjR2hOeEY1SmptbUtPZGI2RkkK2D4rPICtZa4caCzNJP3dsRZndJy3q7sc
        OUOPgM4+Gnkcq4js8ZKDi4Q3zzev9iW6PcTO6XYWEv29xmJSW9XnyQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T12:15:11Z"
  mac: ENC[AES256_GCM,data:GfeszJ3C7A1Z4yf1sv2mWlz2+wlusaQmcuYSZVNLeQVSlNjtCTEUL07HqCXKVhgRqatI+Ndzic5jmXfAr6W/GFHfKrwA6e/ya+TlPHHLCMFZ3Pqu92YakPuWSXNImd182LRwKFJFkvnlnJVjK3+CdMtNTcJU8Vv6gCRD/93GLYU=,iv:JpSUkltXA5uzWrHZUWlCP7PTxtic/pKZEUIv7SYpqa0=,tag:rVDzGPMQm7Or2LfvtOPrWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
