apiVersion: v1
kind: Secret
metadata:
  name: volsync-test-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:aa642Gd+gxulGhZmcxnxU0WeiKoGZuWcT15uzkHmV0mgYrnxJyrEGWg+iQ==,iv:hMk7RbuDPrRh8Sm2l72vovtocoqd/c6mtNOhhUIVUdg=,tag:iDpFGfjLWpBKJKuxrSM0/A==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUmljK2lTUytWQmowQ2po
        RGczeVBTSFlLNGhTWFVqTTdiaW11TElnSGxrCndPbnhYczJmYm9sVDZBYzhwTDR2
        WVBHRVBKYWVrZlVmWHlLdmpQWUkzZU0KLS0tIFNPa0dEZTBtOEtNaGdjTWo4R3JI
        ek5DcXhSUi9RUDhwN01NVllvVmgxMGMKXzQO9FEq7xYRiMIHdiUAHYzx1ZfM7MmK
        092zEfX3l6EwzzmeLlYP2suLT1ymufXMyTgolNPNlWrE11GTj6LZWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T12:06:32Z"
  mac: ENC[AES256_GCM,data:zvp36gpUbRO838uzUSlN9EIxL78aKK7G1oBGzI+f1aTewGmL6cQhPsOM63yBXeBMU8sXiY1kqdGYRoG/OQZImstdxPJuGNfXj37ghwEKvVKhUJpAJKoXzp90dfrR0InPH9xoW3/UF6h04QCsOozBrZSYaARvOif2E7Ph2TXoCVw=,iv:zu+xvR3cUN8XXUGgcDFEktoB9gXC4COITN7eSHStJTk=,tag:/N46vPIw9T7vbshMQwFJfA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
