apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-secret
type: Opaque
stringData:
  SABNZBD__API_KEY: ENC[AES256_GCM,data:7vmojNYJ6NiHqPsmbDIKLOvOyld0pb2Bf1g3QI8Lezc=,iv:iCb18e9DwhzcEZq4AyJ5GO/SbLN5wr2KiEekIyJMAPk=,tag:k/4MJc0jorDAS01/tqzmIw==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYzRsc281L2Z0SWM1czFQ
        cmVPVU54Ni95UGFFUUxqc1lIcWtKV3FxNDNFCkhIbFVqUWExT2tBRzg5TmhERk52
        MEYrQnBhTitraGp0aWdKdGpnQTUrbUEKLS0tIEVrQXErOHlVTFc4M0pyai9Gcksv
        VmtXditsV1hZS1VPeUNUbEdhV2htY28KSnWpxLj6nw3NtTQga9Q55jbzOJOMxOQ/
        WA8EPnFNLA7NgFlXh1iqjpksgDutQRayLYj/OO+Mwf9GViDAidFpUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:hUYMAbwa/LUZb4yYYnTSUi7hECVr/f0hFAwAzAJyo09UKLIfHzjajdWInkeEx1G+XlQZsHZ2vfO3J8ETfYweOWZ1UNxX7w5ikrtsR/CgWXudpwSMId05W2Bp5Uzc2PeBhNKXR9KuuU2k/0/ISvtyzCUk1aAqzv9+TjSUPjNxtxE=,iv:go9zSgTT6j2vlWXQ1QAvXq9tp0nrFq5mSNIiPhLKqMk=,tag:2apHwFmALyjGL9tKuSlnpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
