apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:MB/p1Df5QRSzosEko3N0X+KTjuNxquB2sBWNHtfF8LLulhKvILaBCCv38A==,iv:LwvFPulaEMCS0dXSOe+JI9ux/BkKe6CHT1JBQv1qrr4=,tag:JNheNMI9TCnWvOnuujcmzQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:2NP5Y0+jUoz/wE0RbwoPS0J9vdJCDqRZtqfMGw==,iv:pk+BgxvfWZG6gBpu1R7m3fe+MoooTs5GR/ISmcZfanY=,tag:gJ84HSDNVe8FufdzYhdqvw==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrc1pobmMxN3cxK0dkZ3lx
        bGFGNGlleFYxbzlvdzlWb2dobEVTaTI5UkRBCkxwNzIzZWZycXlEV0xlN2hjb21L
        MzNjL2ZoTnZnVGxLUG1wemhmWDVST0UKLS0tIGFQMG5KVXlFTks5Z1EvdlFlaVRP
        RlhOSHhKdTJFL3R1RUlLTEtka0J3ZDQKBPrVo82Os9SH9n0a0UwbgZt7fzNnp2bH
        bq8Q3T8hSH+HBufuxu2Zii/i3d7cKCPC+ovklDLOeGDoHxnDzcgNJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T22:12:31Z"
  mac: ENC[AES256_GCM,data:mVjKD8hBT/VMATYZhJ/0SZPNzTDYmphOX90chNEKZ5BSw5CBUP20Q2nDIhK6Ydv+r57LYT71jPpt07y0b3pKU1w1Uc6lNqNK275KRPwy/oWJ9N8o41TcHi2mp7FzI+pGriPpF+yVzZYXUEAaAmZx+KfutIaapOc6GvCmB4iXI7M=,iv:163PeMsAt9LEyhEeEcDZyi3a19gPP4fJ/lJ2FcpIWA0=,tag:ra5uQj0GNEaUylPhl5q5EQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
