apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:mJgWUUiU9tkSC5S2sgAe8EkHxTagBQM8oF3QD/lRzWJ9aXxrunZS/dcx/T0JEf39gYAvut+s70hHqmHE5fElYA==,iv:0Wp+lxIw852re+c6FNEmhqp9e3vU4UjscBZnq5nPJqk=,tag:SrTRgpV9TO8SpaeuxRqITg==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:zkHgld0I5A==,iv:R0emMToxHbHYKqjZkHnIJysBhBQqe6a5sCVTfHx2zHk=,tag:4by+FoqJh9fbdTfzvUrFaw==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWGM0NkRzekQ0SWwrTWMv
        U3dQZS85bFlTYmgxL2Z4dFVTMUZtaFZzZlYwCldyWGpCNzZwbjFKTXpBZHNUWGFL
        N2duT09aWVY3Tnpld1d6MGwxQVlkbDAKLS0tIDMyYkdJNUNDRmxIcC8vaXl5R0l4
        QWx4NnJqZ3J5S09YbHN1UEhFNldLNWsKWaXeHk9wEbpzYyPo/bVL5XJBDpboTL0/
        jPcsEfHaYDmEu4h+OyMXvZ+uXTZLi1L0/ng5TibvVhbst4sCUEADzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:Oi6G+lXZuGt/GyXD02hgZazSbrO40bZvMNYRdlx5fgLFzHHlaoMTYCaIg8NgrNtw6oIQBCMAWVhn1KTZr+6Qn3ylQ2JuK8rWa8RrCD3uYUKk9JkkQ1AUXeED/Oq8nVXH94/TZqNMrGJY/8mHFCIwJopRb/W+QwVnw7MvQJEcto0=,iv:1gVgbI+x5AN54wlG9+eP56pZiqjzEDKwM2L6YEGcZ8s=,tag:Cu9+bLJuAGUpBm9ojDbfrg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
