vault_ollama_api_key: ENC[AES256_GCM,data:h4gpfDxOI7ITmtnGngi2c2iI+oRmV2VVM1+pgOblAHwFpFov+XHGKw==,iv:M5n8egARjNspiexBuU+3eFEMjJZF7qUbr3ZzzxBSGFY=,tag:Hj74HwT9D9WZ21KrDF2g8g==,type:str]
vault_nut_monitor_password: ENC[AES256_GCM,data:+VHZrK+umAheH1e78loyHxMy,iv:tVJORL4L0fw905NBO9G/ZvUG45/kmIeSCPcTb2uPdqI=,tag:nid9ve/yu+M+tSDBepwX6w==,type:str]
vault_speaches_api_key: ENC[AES256_GCM,data:zJWcLzDiAO+uiD+tCpyXlYHDAGtVBOURnxRxSoKpH9Mbx+K25lC83RnHBA==,iv:KiVsUwaav4TJyBux/os7VofklxTAvrBNQkMwoswGbN4=,tag:+PUdbCkSjFjDTJ2fXF7yyw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOFV3dGRTaXliSy9QUTB6
        TUhFT3k5SW5reHVYZmk3dStBTDQ5RU85dURjCmlTbjhSMXFKd0pzeEVkcHp5UmFW
        OVc5YjhsVjY3TjVsSlFGbDdLRTBRLzQKLS0tIEpJeGQrUklxYkFIS1RwSThLUU9S
        S3U0eUFValhXT05pN3ZyYTRFeGdFSFEKAs4v9RM1NZYkwv4MbvfdrbgAx7BARrpT
        DmRvRUjUUbtw5E1p3hrWblh1dZkU276ZoEgPPk6LPa5/7GfPG+86vg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  lastmodified: "2026-05-23T20:48:50Z"
  mac: ENC[AES256_GCM,data:8zJUlvXivtZw+1kVz9KQPlIuDV4ilyEdxLY0z+cU2UJZO+7dXCMH/e6YYXYz7FUGQAgoWwrZYBbjs+TLSJ8ahUhhOo2AEPndZToxTA3PZNXMfdTSrUAhvuLnF3+WbFZJAdmp7Kokr1vMflOzuBlbfIELfkf2etlTOc9SN+p93og=,iv:iXnvmdUGMnDh+PUow9DeD4QdnDkEMm5lO9/zbOngWwU=,tag:D/MVIY4KtLuebhz2dfbdCw==,type:str]
  mac_only_encrypted: true
  unencrypted_suffix: _unencrypted
  version: 3.13.1
