vault_ollama_api_key: ENC[AES256_GCM,data:JOGiDYdg8JhSycqlz0lV8EKQjRhsFb0x,iv:GsYxD3hz6phMyN/gNjxWpF62UmWnsemrXaaDJZD/KCE=,tag:4ncEcVx2GjCReb2RB2hGHQ==,type:str]
vault_nut_monitor_password: ENC[AES256_GCM,data:5zZwFE2OMnID27Hsqo02bYbc,iv:PHOK2rYqAZFmFZnFYpodSDrAv/Of+1IBZ5Kp3wygzpY=,tag:kxB5rqaZ9i/dYSlGlhiHYA==,type:str]
sops:
    age:
        - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVmFmYWplOUxuaTRPNXEx
            cHdtVVdlc1pQWEJvOUh2RWZtSmthcStxTW5BCkNQY2ptc3hSUk84aEtTYVFFRW8y
            eE82TzJaNWM3S01PUm5tNUpaVEZ5M0EKLS0tIFRDMmlUTy9Nczl5cko1SVo0Und0
            Q294K2JnRlRCMzNlcUNOR2lGZnQzSmsKAoZldsmqa9X3GzIe+59oC4+lZnJGFozB
            OahHSlvL1mw3c+js7PFUie0Xkn2N5hcO/F1R6xIRbkWLOE1Rak0R7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T17:23:03Z"
    mac: ENC[AES256_GCM,data:+wDy/xL9xbTcih1CRu3Tj+bK68mg+2sFdp4D9EMXERq8Sz6PuBwuxcRbGnqcXt+uoz86JDosTg81FmQC7VrPZ1wN2XB2B0RWLQudrVQB79ZiAI1z7cGtg+EtY6F7KGC1A8u/GrJgUCL0G2W9UBZ7TWGSRkbiHNBonQmY4NOpcPM=,iv:rx1wcdimN9T9pYUQ0b2IfhoFJsauYTx6CAMdOcLdRHg=,tag:M4gVmYWNw5sXDi353uKtlg==,type:str]
    unencrypted_suffix: _unencrypted
    mac_only_encrypted: true
    version: 3.12.2
