vault_ollama_api_key: ENC[AES256_GCM,data:orEqquybDLUpASi8GqLKYZimbopAeZFBmnR8kgV7ifH6MR2KcWeK/w==,iv:/PToUfVBmnerGuGFwT5Pf9z8498xVzGCnFAgGgdCEos=,tag:gA4nIMoQSx3YuOOrCs2cjw==,type:str]
vault_nut_monitor_password: ENC[AES256_GCM,data:PrwjsPTPpkHnD/BIW5xOtYgp,iv:2LhZvRMvSTqbpbVjmIWybvchpVFVfuJqf2YAiBILI80=,tag:GlTeGdtrZyvogqEadMkkRA==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UUlkOElYUm9qeDJVNWQy
        QlpiYXFOWTVCN3hHWFZBTDZjNG43ZGNocmlrClIvV2VubzRLSTdRdi80S0JKUWk3
        bFg0eDVnM3R3Vm1oaE5tbmRZbjlBSDgKLS0tIHNCTFVqWnMwK3pzYWJKWENXNWE3
        R215ajdHVmswRzFTOWZBUkR6UkszM2sKz5hAgjZzB3gQe2x02/qY3AkTZShw1hTe
        M9Xa5jgrPVu3COCdWtl4puwtgONT16rmIzqOX10u2I4afqTA0kTDfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T12:26:56Z"
  mac: ENC[AES256_GCM,data:h765g7Kfx0V1mwoGWOaRW7CuziNeap9mg5hb57C1uyNUmOtpgh6WpWYoXeRY5ZQ7i5kt/pzfsk8QOYLVJI1wSONp+1/g1b51bt0dSiwITegrrMwLi4roPsbqJLPdntskLTGgOnQlCeFuttbFwe04O4R6NbxZUeUdy6thnKSVq6k=,iv:mRTiNETHcX+bql0F2+SEkTOwmPHdOAvf7R3WlMsHm/M=,tag:9cWTrX4AXCUoAlO+tayEJA==,type:str]
  unencrypted_suffix: _unencrypted
  mac_only_encrypted: true
  version: 3.12.2
