apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:8k9VgaaIEpfqcxLIeV1SdStIdJBAcyEtkaMg2nkej3uxnhtRsleMo93ocThtYlMK3o/ONDw=,iv:U+P2wkjutdMHO//dtcuYYPTdip13LOIpinxBFMRJEsY=,tag:DSUhVfSBIFd4VariMTBCzg==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQ2dxWUJEYWIrMWRHT2pF
        VTdoVWFxODJ5YnU0b1ArRTJEd20yYnZjY1hVCkYrdzBxMUNSWkNPM3lDVEt5TFFs
        eFdKUjVaejBoOUxmZkRrazVDUXYxRFUKLS0tIHZldjM3MTJ5aTdKbzVRUE81b0hC
        WFljaS9OQ3F0ZnZkMnRxYVovcDBtUHMKSs9WORn1PDomXtBfvmwZVWzh5xH2Fr4g
        hXF1yMDsfjudf9N9PsYjQht4fL546Ge4KCDFw5QJGqsb8JdtN6uROw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T20:15:27Z"
  mac: ENC[AES256_GCM,data:8r/XcQD41Aubo1f3DU0XIpGjFIEWGerxLvXaeegGwimvVG1HXhchZnQhQwDKdp4eAtaqnjQRJRZDiir90V6ldtgaM136QZ+U1uP6/MIHhaFeZiEKxXhyuJyuK3MJAOWJyIt9TzBSAdgPlpDu0SVXIgasoscTTYTspP08i0IvgFE=,iv:jDxviC8KeyuM1PojgNO+1n6QPKPafc6v+v0J1BAjM4c=,tag:fE9dya2qL/+TIZP9SHCntQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
