apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:j2yElR+pMXmJQPWNFs+hvSjGHYkQ3j9NOrjyT2HvGphs+GbW+HMWL9Jra5D8GJA6B/A+c1M=,iv:e/nM5bP+BGewkZxVlu3UOY0sc2bCEVzoQVoE+8V5Ggw=,tag:igtDizPV486XwSq4A9mJgQ==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeVI2KzQ5aGJ3azBxTTN3
        NktnaFk4ay9tR0Urd29EbFAxeTlzMXEyK0VJCkZ3Q1ZCVkQ3VjloeFNjZUVJU2N2
        aitSSC9FcFh4UXBaakN6NlhTUXg0OGsKLS0tIDlIakJrOGYzY3Qvam1Ya3RiaEhQ
        VFdGdDhaZCt5S2ptZ3BEaGhZTEtRa3MKmxDR89/dFSUh3a40ZklBLhrZxr40sIHa
        0KHStbt7w/9gJHxtKQFiGzJDNveZQaUbFaSHaEXSDYEOHeZDiWVKdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T21:22:05Z"
  mac: ENC[AES256_GCM,data:F4Ik7oE7HNINglxoS/90NPSFo8NFA/zmV9YlES/NbhvTDxi1lXrQE1WXSTaymFaEu6xAkXiHOBzEKWW4wcfRurH+7jhYuJLLsnnlPhSgmuGyd1E9tV30dP+gJiM45t0YWY+P7hvGeb1Mrqk3OTWOCkUejMLN51sSb35KFTgxC0s=,iv:rG3psk3v9wWOBb29bL6tqbuDmbo9NMRJBd5aykhIQ4U=,tag:oY9F0tJ92/OnCJDqh2jk+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
