---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  sourcePVC: ${APP}
  trigger:
    schedule: "0 * * * *"
  kopia:
    accessModes:
      - ReadWriteOnce
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: ${VOLSYNC_CAPACITY:=5Gi}
    cacheStorageClassName: iscsi
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: ${VOLSYNC_UID:=1000}
      runAsGroup: ${VOLSYNC_GID:=1000}
      fsGroup: ${VOLSYNC_GID:=1000}
    moverVolumes:
      - mountPath: repository
        volumeSource:
          nfs:
            path: /mnt/tank/homelab/kopia
            server: 192.168.5.40
    parallelism: 2
    repository: ${APP}-volsync-secret
    retain:
      hourly: 24
      daily: 7
    storageClassName: iscsi
    volumeSnapshotClassName: iscsi
