---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: ${APP}-dst
  labels:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: restore-once
  kopia:
    accessModes:
      - ReadWriteOnce
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: ${VOLSYNC_CAPACITY:=5Gi}
    cacheStorageClassName: iscsi
    capacity: ${VOLSYNC_CAPACITY:=5Gi}
    cleanupCachePVC: true
    cleanupTempPVC: true
    copyMethod: Snapshot
    enableFileDeletion: true
    moverSecurityContext:
      runAsUser: ${VOLSYNC_UID:=1000}
      runAsGroup: ${VOLSYNC_GID:=1000}
      fsGroup: ${VOLSYNC_GID:=1000}
    moverVolumes:
      - mountPath: repository
        volumeSource:
          nfs:
            path: /mnt/tank/homelab/kopia
            server: 192.168.5.40
    repository: ${APP}-volsync-secret
    sourceIdentity:
      sourceName: ${APP}
    storageClassName: iscsi
    volumeSnapshotClassName: iscsi
