apiVersion: v1
kind: Secret
metadata:
  name: headlamp-oidc
stringData:
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:k5zQAQXTYFkKYCgKImDnYAVRaGpvYBe1wWjoFL8awCyzRURF,iv:QlJoQFr6D45o3YX9MJQAJDEZvGxycLGbNEF0C9RUJu0=,tag:EmGMK/Ow1TzthcZIYXI1fw==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Mxe5vx2WBuIdUxKMrXvog6dDlNdIPDzTKJbaS0mPlGc=,iv:5rVb302bhJG/KhtI7Lavb9IgGFXFUD7TV4nYSxnkmis=,tag:PMBCdmjuvSnnVr28x+1Qsw==,type:str]
  OIDC_ISSUER_URL: ENC[AES256_GCM,data:OR5QxrdhuqItJqHGCIqmV8/K2FWEGAPSaoo=,iv:DwDnMxuoA3VDXCbtkeVlF8MBRFVKeBLskTs+NT470k4=,tag:BaT+/5VwXPK1SKMSaeS1ng==,type:str]
  OIDC_SCOPES: ENC[AES256_GCM,data:PoDjQVtA4qRuKRzCnc8q6TEJlnPUOcZTcb14,iv:Rtwin+4PLcXcOIaBx+baiGIky+XLU7pmWADHgnIYVw4=,tag:v0ltI8ZlGws5jfdJn6AowA==,type:str]
  OIDC_CALLBACK_URL: ENC[AES256_GCM,data:870Cd/7yycNU4d3YC1kl4YW/ANhPZPnJ6RsUEM0eyKwUkm2gbqjGl75pHZ5zJg==,iv:pz6qcVY31upghz4U87LGi4l6wfwr2vvatKTkHYNIar4=,tag:RGE5YTpb+kebbkT47AtvSg==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eGRmNG84aGM0eURObDNr
        MUhKTU1nODNVcHplcVF6YTJRRVBJZVdIZGtvClozMXJBaytZNytTYVN4K2ZhVjEr
        YnJiMTczbDBKK0pRMmdnWGs1c2ZXZTQKLS0tIDlEMm1QQkhCcWZSOXM5T2VlNUZ5
        NmkxWHp0MkgvRUFkM2RmL2tCaWdPcXMKQRjl46IImMD+jjl3+nHn6VBDmaA6NuSW
        TMG/MK+ZTC4Uc3QXPcJmGTD4z759ISYUZBz8kS1j7OsiwttkneMyHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-09T19:24:15Z"
  mac: ENC[AES256_GCM,data:V0e2YL4YhmHexOwNxMmJhW8YjwUgJFoh34beC2PC4d39cHBm0w1hGZMCtKUHq72XtTv/S0+rwxy3CcmfAhp5eQ5K7higg9WNkOusswc6tdOrWKfu2bT7gSnw6TWOXlVTnEWn4OG90L4xAKrgMa+tjZrp62bjbQmXjGp2rF/Vzgs=,iv:YjPq4jAu5MvOEOh+/toegaUJ4Z5bT9OFY3dk3AyJJaw=,tag:Uy4B6CBQR9vNzRxGlnW01g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
