apiVersion: v1
kind: Secret
metadata:
  name: headlamp-oidc-secret
stringData:
  client-secret: ENC[AES256_GCM,data:LBE9GONZdqOwF8kqLLWE8BcZuzjtzs29UU1whRdtVOo=,iv:zcICseMzVJoJrW64u/Hwsd1JnV25yTtCL06Whiz0LGM=,tag:wY88qVz3mJh2ymWBydURog==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTF2RCtGWU56Z1N2S08r
        RFBFT0owd2pWeWhqTktubkNaOGRkdW53S1RVCkQxT3FOZWp0dy8vRmtESVNZclNY
        RTB6cW5ZUVBPLzNDWUl5c3Q0VmRoVDQKLS0tIGNSQktRWHZrekp0VDQ0OGE0M3hm
        cFJjSlZvenVlT0IyaDByc1AxYXlHNW8KFwpkooHwAqNAenRodXbALg4zmQgRGkyC
        +QFxG8WZr5Er3BPI1fyAxpCvCXG+iTK9baXQWbT1lEio31Sg/c3Otg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-09T19:46:05Z"
  mac: ENC[AES256_GCM,data:RaPtEp1Qf8V1qom1K8x3bKFZKs1PCFVhJF4WzM2ntB9KSe9qUbtwwknqnmCN2g/LI1Be+xXD1jfxqumiKc75pMdslCJIzGt+vEvui3EB/+fLdq9dEqoownMu4wcEu3zbiHDMIzsedrFmz1mjzU6dHcJdc3dZxxmzZdBilu4DaOo=,iv:Jmyp42NIMvx/MA/2tgj19xJ6iFn+wESE5IcrkTc3uBI=,tag:wOG+OwI5ogDJlsBL7Ubq7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
