apiVersion: v1
kind: Secret
metadata:
  name: headlamp-oidc
stringData:
  clientID: ENC[AES256_GCM,data:Z8ra/D41eTmBVLWJGmicnR9b4zUen6jmWvFiQMkFlA6YqAld,iv:M6p9/KQ4IXSS/XAWSfT115g/98glE4ELluHLkfdSHxk=,tag:8H4ug5e1KJ76yPdSEZLK1A==,type:str]
  clientSecret: ENC[AES256_GCM,data:4FLMgSgiyj0Ro3BEDK80QqwYjOO+MM/d/Ib+ya9QAGE=,iv:8IR4sTgFJmJAJM4asHWPTuL+4SPO1Tht50Z4anWRjAI=,tag:UuxVAS+uWluBva2eOmrwQw==,type:str]
  issuerURL: ENC[AES256_GCM,data:j51hw3QL0Yr49mWuMrwf6RzihDrYQLhB/Gg=,iv:ynGnrQS2nnXCY1be24R+CJHpY6yHyLnwv/T8QPfWGYk=,tag:2vlGg0SQwIswrlFUJ1xpfw==,type:str]
  scopes: ENC[AES256_GCM,data:+7TA0LBMgtPXsQ8h6XlLWURGrBFomyq3+r+8,iv:ReHuGYRmjCtaXeNYgjIXwXWVzSmsuMuaNwl9ch7ox+8=,tag:YGLRnryTrg5sPZdNje9nSg==,type:str]
  callbackURL: ENC[AES256_GCM,data:l6hSTfiIwxha55hIeXsTX8uMofqKsnh3SiQJpr41C+AeqvupXol9GGaYy3wtzw==,iv:C7eou0e3RS4HH8p1L01HnPyo6B7B07/xN9ScRlIlp/A=,tag:M6hX5ep/W5TBlJEgtjcbBg==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZ2d2andhTEU4bmFnVWtk
        cGJTNmYwMUpFUGZRcTAwL1JtenlCNDVTSlhvCmQ0aldZL3luY3c3bWtHQ2xDWkFq
        Z2dZMzVoNXBQUWhWcWY4UWZIQnJUbGsKLS0tIGlqWjRXcFgxQTBHRkt4NnFIMktm
        UWlCNTRiSU04bVR6VFY3ZTJ0ZXJVamsK6R3+tjy25hyQB41aKuGL/3Acz5kBMmw5
        hofdnFvppRYXfpqdcrGiVKDSfuhqtacAuo/Va6N61luXfEs9ycflVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-09T18:28:21Z"
  mac: ENC[AES256_GCM,data:ZOJnMyZSRfL6DQmJf00bwNwh68uHcTgxcsb0V7VhAG75au95oRCOgqjyGag/5KJP64X547LLqj1xdpxjIKDETMgeDf6+/1PPi0CtHFZ65FifUf/8knk2K+TjboHxRHENOLgU1DdH4QRPmCZyDohnsquzalXdzThnaei+l+iS61Y=,iv:VkwveIiW1ZrmimZ/1Ekjba9PkgmhiuWYeLeUZ0StMZM=,tag:92xx3dkRQyDoLzEeLlIUDg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
