apiVersion: v1
kind: Secret
metadata:
  name: cleanrr-secret
type: Opaque
stringData:
  CLEANRR_SERVERS__RADARR__API_KEY: ENC[AES256_GCM,data:Rz0KMRn+g7VC1UMQxE25GUtr1wmHCwcRnHR1VSgKhTk=,iv:NHUVFQuHLbLOhaDzjYPkNLQIgN6uI9a5gUawJLABXc0=,tag:xC1wXp6ZiBWsfViwIpCUMA==,type:str]
  CLEANRR_SERVERS__SONARR__API_KEY: ENC[AES256_GCM,data:KkbQJVyCl+UfxtzsmXffUxgQQsef66sHzQxS/fXDlhw=,iv:1rN46MB69ERqczk34y+ZAhVJXkkXYDp9nyBLQCPX7C8=,tag:FtISTxVETwEci0Q3E5lCBw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbCtYS3dvTThNbENrUXZr
        Ly9WaU82VXloSXVhWWNwR0YvWG5PODlNbjFJClZzY0ZmOWRkQWxuZ0JYdWtvMXh5
        S05GemVrcUZGZU5maDRQRUdDWEVDVm8KLS0tIGgxRHlyd1BUUkZsVXFQMXFYUXdN
        RGUzSkNaUjBWNGNHYjgyNmpyZnc4T1UKB8IMW8YUxVnKrScw0qKx/Ya95p2fpZ6e
        xaDAHHBn7H/XWQqsXDwfk1MOX3EAbZ3WRzCIj4rOqAV1/MAIlB0j0g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T16:13:55Z"
  mac: ENC[AES256_GCM,data:QRXnSHd5iItVV2W6ZEfNcJTHEFSUvH8TVvVcpKWcuch9zEGzzJuZP/0qc3oXUv28TwUBlp2ywIAMrh2ogHbj+ox3IAOv7udzHX7UW6Vxzoy8vBaVFJ/Y9oSsncWVUY/wtiR7lWtxXxUOEwrOvSLmXUO8V4y7DCL7KjQ18m079bs=,iv:zFi8wiqy00SAMYqPyY1KPND9ud4B6Lg2zoy8lmjSN58=,tag:0Y39CcGfjeYKV4ma1b3Gwg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
