apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:HIQl38OXrWHmoAgH20xl,iv:GIDgHYCkB4XR7GOI0pOI50gYZWmesXkszey9VV+Qtzk=,tag:d7+2IvXJkfOoFu96yGiE/A==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZGNEWXFSaUxvRG9hNFpN
        aUpLaFNiMnp6bUJTeWQwc1VwODBGajRxSzBzCnVoRVV5VTZaTm0yWXZpSExoQXVH
        NFlEcVgva1EzN1F5OWh0SmZiR1gyb0kKLS0tIG56ZTF0UEt3MVAvT3JCRVNNUjlF
        M0xOZUNrZGhGQzVoRHRFSUNEeXh1MUUKf1IoD5hk/jfZ8fX5dYHp59CJetfsyFMG
        4PmJj71NG7JAznazcPljiTEk4WQ3CFd8VkBW0XxjS9oRZOY35lhd2A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T20:15:27Z"
  mac: ENC[AES256_GCM,data:ijCIPtWTOOBjBdGTVQp/WvOdS3ESje60YSd5udr+mkVUnnLSwVLhvyfXUlJQDbUVaZe5hpGIe0jwJS/OfN3vaHUq6iNn2+t41ZQTptDWZ5YaTk0gnQBUom+7ZUdXJjuM3epHZI+7NXyAEhchUPXNkYe+Z3evH0gzzwtAdf+yahw=,iv:JHZ1VDMZAqHAHYMmeXRVBpfVKLzH45UBIV/KnI8RxPU=,tag:RcDU3ZAidKVvgg5enLsZwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
