apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ququZg7eOw0H+zvhKJgx,iv:kYZgwCjBzqi9YIG03Mu9dlFiVpwv/IOtgK0Q7DZpjug=,tag:8avpuM5QGa+JlKOybSBXCw==,type:str]
  SECRET_OLLAMA_API_KEY: ENC[AES256_GCM,data:e9jc7Jc5LQBK0dxnwPsMy4N8p7rvRqxstNgLCLTwDPBgON22F2jLOw==,iv:veOxbVCvy2qbMfpQkMNFjHYq8CPrYfy7wbQJwiFU8dM=,tag:hwZlFPSgrsi2s0rc9rX0hw==,type:str]
  GARAGE_RPC_SECRET: ENC[AES256_GCM,data:BKAxpcun95Tu3W7wrJxdzwAqaBbBD0o0eXRy3TDaOF7dRhfMli9ZUsdz7Rny+pboP04oF/ilY152cr6yFagerQ==,iv:d1LlUideogWdr9u7Vs8F36aSGWrejlq4MKwg8lVjLmE=,tag:vg3M1Ajb3HZsuSanNI8Y5g==,type:str]
  GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:+Ku1uG+MFSBXB+6mMSxyhYUj78GGrm1K5MSPepY/Ch9ZK4YjNXNe7AmZQu2qJ70nKWhUXc5efWtV3t0R5NiXPA==,iv:Dw8epsASM7kQlG8Z4OoPnOQOZ/qmAS5h2Fpab+JdUd0=,tag:fxM/MkvVUD4BsG+b+4yZJA==,type:str]
  GARAGE_S3_KEY_ID: ENC[AES256_GCM,data:Pk7jUGL5MfuVrxRnOrQBZpWeuzOwhALdVJw=,iv:nX2P/8joyhopLXvOSiTiihlpMTaGPT+hPtptWcMpTc8=,tag:lNUKcroGahgyu1QpAN4t+Q==,type:str]
  GARAGE_S3_SECRET_KEY: ENC[AES256_GCM,data:5k138IG3qrzVvKtxov3epPdnrTvBHIsh43YIwDLI5RFn1Si2tA6KJBRB5dczLCDVpjzyFkkHU9ZyUUdXd1opow==,iv:wQB6hBIyYw7uTVMiHwqWpb1rgj6Z5qgUu93+PueaIiY=,tag:yMH6QzZKfdYHvMoreihCdQ==,type:str]
  LOKI_S3_KEY_ID: ENC[AES256_GCM,data:kAA306Mn/dFlOvKpQ8CILkuhsrd4zNm00ms=,iv:ajO3bG7TNe9pgZUuP89oCNNQ99klytrFjrJPlNEEht8=,tag:M/6rymZvVlXZt94JWLM41A==,type:str]
  LOKI_S3_SECRET_KEY: ENC[AES256_GCM,data:ACPFqmva8LyXsmERZUFfNtJAI1UN5cVULoPMXx5Aa+jzzCFa59nU1rBnwboS1enoF4phxEWCNC/nPGI5sJTd/g==,iv:jas/z456HPOZiTjP05DhadOwTUZp2vDG5Xc8gYqTzrw=,tag:OiqOsJuutaVZSZzBaIoaWQ==,type:str]
  POCKET_ID_S3_KEY_ID: ENC[AES256_GCM,data:fFKOf+OxE/vbUJKm6o66pNFIxZGf/j4GH1X6Nfwcg5fT+A==,iv:YrW+pMkj+Ey0x6RNu/rXNvEpqk3OWR09m/2BM5YH2s8=,tag:BOlfUq15tI01RTU4ErHeqw==,type:str]
  POCKET_ID_S3_SECRET_KEY: ENC[AES256_GCM,data:3U4YDEiADHcupjGrQRE6E0oMOjjwBRCiVflc9P3ljUOSWYfr5sDZJVNECc4=,iv:MDa9gbCITGBuz92dBHNWzrrL/3cwguo3BcFFyOTlljk=,tag:BjdnHVk0YnGvBgajjVnYdQ==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdEhibTVhTUhGRDA0amJt
        SGhLcmNWWDF6b0dCVEF3dW5KSCtTSjd1LzNnClZvTUVqN1VqRm9lbEIvMm5mUnVu
        WWlFKzlwWEhQRTF2MkE5bHJUU1hHNnMKLS0tIGRub0NleGtTLzhEd0NHWC9sWXJr
        UDNMMmRIUnFETHRBUVQ0QUl0ZXB1cU0KIaxchgMOISVe55neOp45WBpu2G+bD/UR
        7XCCd04P/zCVbdRNynT9j5h/WgDxZB0pl7RTqUOFAR+IwbzskuXCbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T22:28:31Z"
  mac: ENC[AES256_GCM,data:0IIXwdfkE2MV0BBGVWymwj6g1DCutKSRIrQtwoUtYtNiZSS1hpwpufCA78frn/iLSNdJY/EYEPyiij2y3YpPzaUTrEfe79TWSPs8PhgCyy31q4K1EtQRQDnURfQrAhh/0VhsL+HYFBNRhEvUrftWqoePlopUBskjnOS6q9GtpCA=,iv:srcc3uA5J8lznC8vr4zb8dUiIAmZfTh3IOOuAo2FRyc=,tag:i8cqxswt4y2g+vo2KcSu5w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
