apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:R/dmQsOsVXRhYo4DmTD5,iv:8OFwTNTAW0dSVEdFr5CLZ35oYBJGGBwD8Or93P+HFGo=,tag:c6VVLf+LbCDnSGZMt9dlbw==,type:str]
  SECRET_OLLAMA_API_KEY: ENC[AES256_GCM,data:3Eheg6DY2aPG6961CNj6QJQl2OpIGcPJULzRHsd3+5w8418mUA5npQ==,iv:I90qo22kEITw+SEb/SYFwoDZ+Q/OnI/urj7D5KuqRtg=,tag:0RFm7mU9Nesu27/ZcjX8PQ==,type:str]
  GARAGE_RPC_SECRET: ENC[AES256_GCM,data:+okiL3QDNhA368vmxlkwlO/2EG/enC0aP3cdsOBHr2TbRmVMSykBoWTodpzuSeElEIRuvLDEDYB7E/wQZ7IBZA==,iv:pBQRi3aCO2cZEcoXtcWQarRYH6+7jEw8+ERxoLn1Tog=,tag:0wpR+Gtat1V1U6V7SKErDg==,type:str]
  GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:8E8DtsT3AW1H+3KePBOBmygqRX0rYRBnmMGzDkaDFtkpxBDsBkYFWb1l31xKXkSFSFzwTZhyuwpPzT9LcqTE1g==,iv:s3P9MHhAWuxIIhw/s0XVwqRK//ifhT3J25DJN1I/ZVA=,tag:FUem2fUTwmgQs0lfA+8WVg==,type:str]
  GARAGE_S3_KEY_ID: ENC[AES256_GCM,data:5YhB4GWTdxZhWfeOQDYNrW1OQmJ2X2UP64c=,iv:VdOTM9dlb3RnRCI6p2+qFeXhoKdeG9xSDmhiAzele64=,tag:50A7DPHgBesy2IDjcUxtPA==,type:str]
  GARAGE_S3_SECRET_KEY: ENC[AES256_GCM,data:Sy+cryXM1d5YRVI0jq3uqOcIg7RAdHiKFNktO+WyDgId77HSrebcvEk8YgvdLn9PkvbbhK234rii/XXaAbCKeg==,iv:WjPVNa9Tf+z3dKQ9yq5MS2QzYCAv+wCLSbD5QUD67YI=,tag:Ic2ghySwx1ygnEFqB94f9g==,type:str]
  LOKI_S3_KEY_ID: ENC[AES256_GCM,data:vkLKhNn3ICdXLAVuoljgtlSEm0Vs9rd5920=,iv:GpMxpEk+GBpt/KQ2eD2+mChRXnV4qVTh7Frrd0aGw/g=,tag:36onawgOmbN84ryUATz7Lw==,type:str]
  LOKI_S3_SECRET_KEY: ENC[AES256_GCM,data:Ugm5WeolGalgZCYfF63sBFLR+625bPckWYDAjRdtyTJ3MYpv81kVGMnkqTsKif/2NDmcyB18MEO3DaWSjgC8Kw==,iv:B3PlSTubYRC8FPRE88GSYezm6f8Nz35ciOclg/vRk6g=,tag:qUebdsJchGnrDoGQYsJ6JA==,type:str]
  POCKET_ID_S3_KEY_ID: ENC[AES256_GCM,data:2a7Mx0eoQaZyOtVj7WODuyXIqoWRBK6Mg3c=,iv:jUOjhNz7ycl4mdm60BV/GKEoXLmQTmcV16dKphVXAuU=,tag:knD2krzUwBwLE4/DlA8wZQ==,type:str]
  POCKET_ID_S3_SECRET_KEY: ENC[AES256_GCM,data:sNWdDgkySGwxa+1+5H1KhDu4W53jzMh9ioQwUUmmny0yArHJWGtkVWWPu48zw5qG2uTW8JAChikJPeRjQXfQEQ==,iv:/6nQb2ghwc0SjqNHro0l4sfaEDKC68fe3k6ENk8Dbhk=,tag:0i6xrR14r6OIzOeBjoEAWQ==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZi9WVzh6YUtQN21GVG1M
        aVJQTGhkcjRMUC9lLzE5M2M4MXJKRHNCTW1jCjRNeVVzVnE2eTYxZDlsT3hxelhW
        U3Z2cEpDT0ZtWTkwMkNjR2tzSi83aWMKLS0tIFNCTGMvUWViUU5qWVZZMGFFcGdi
        WVZVSE1IOXJXVktOR1FJdUU4NWcyNUkKXHsKNnbn4CrBaGgLZbXRgeQBlw4aypHz
        BebYCyPfnPM5F0zW9Lu7v0q2oQKJhP7D1Uc5KnTyN2qImsS2Anhllw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T22:47:01Z"
  mac: ENC[AES256_GCM,data:cIPriCiS6Bg7VtoteT9jY5/TAViRKgxeAAS53ZG7XdjE1FKr2t/tZBpLsjjNsCKCqYL2tzB6tFbdhZ6U3NLxm/a3r9Af90WQPNnAbtBn5m0fY2WrnQzBGI/y6/r2cGgkCXf4MqOiAyn7E88OxpT2X+eWzKGjsG1loLe57P3Nca0=,iv:NkpZBiugYyEZK/dAfxH7NaogWrat12HUJQ0lIaJHOeU=,tag:vn92DFasAAl9ipue7Of98A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
