---
all:
  children:
    nas:
      hosts:
        hl8:
          ansible_host: 192.168.5.40
    inference:
      hosts:
        sardior:
          ansible_host: 192.168.5.70
    backblaze:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
