apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook-url
stringData:
  address: ENC[AES256_GCM,data:uOGvtmKOC0MCUxGvXuaBdMGsmrQ5sJfKq8QaMl8DSPruvPRlTRWgv3bR4gbXGYS2QdT9Axz6CAMHvOywqUeMh1caUVCBUZteh0rLWrwQziVvRqR0ZsgYanGIQu4c7MVYmpB5DHM+XeUk4CltUUfs/nst3vaU5IRr,iv:jj6moHbVCGYh1xLw63C/TeebcV7KEQTH7lN2EO4FlUw=,tag:3PIKT++v+P3UOVxz8oxhMg==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ1dEVkExWmZRenpJUkRJ
        OEo0VlBCUlF5M2JtaW9BQ09Dd0NLVytPNndvCmgrQ0RXVDJ4WGVyTEFCcmROY0F5
        Z21lTURoU0k2MDV4YkRwVnM3OGZzMDAKLS0tIEhpSHA4YnliY0w1ZjVJWlU3T3dU
        bXI1dE15bkdGUlZmSEFXMUVlVXZDbmMKK00wx+iLADU707kPC9A9Jy+gHmU4MDEY
        Tn+is+YlwHxogUlLXL38xsgohDt58fj0tbtLBrUMmUuHLNHa+C93Kw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T14:57:29Z"
  mac: ENC[AES256_GCM,data:I5fg6zjhljrs1BogE32IUDLHoOEYrG8P6BxkJ477wYNJbYJIIcsYJPiJSi229wv4aGp9tkyFSfIXyjs++lNfy996IKne16EspY5dyV7hUo5+AdcI3lub2PGHSaSS73HrZF2hTmttPpDPIlquW72RmkPOHjv+zYoaHX+mRXioM5s=,iv:IYZ5ydfwzOJJrKStvpQndBDIGoinSQZNfeXPvTE3AUs=,tag:qxuC5BIJQzVVXWX1rRx5Ug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
