apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:V6Tc/zvbh2RLZHX6EH7cnNx7lJcBStMdT/Mdnt3ozHQ=,iv:Qzjz08Ih0afrHWxTk7AFxU+WHAaQiNXynu42FoO4GwQ=,tag:qUf2cqh+9c5c9CtWPm34zg==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZ1BTNmFvUzFxanI3YVdM
        MDU5MHF1R3IxMTVPNGxzeXJIM1BLMFRZMTBrCnF3RlRaeVlvODBYY0kwOFpQT2VD
        M1hrL084akVSU2Jvb1F3MS9YTFA4V0EKLS0tIFpLeTZCWk1qakNScGRlaW9SMk44
        SHVvL2ZPcXFib1pMNUJNQ1JRTnk5NFUKoYpwG5csaRheEvzUvNkpBjBETaKlaE/S
        VGY7/YrHdQsWerRjUKZPtO1hvOBqyhu0SggRNyLPeP2wJmAMETj1YQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T21:22:05Z"
  mac: ENC[AES256_GCM,data:FUW8u9MILs8No1rKZ9BE1eam0wSMvyeRnndbCMQdYhlq/5E+NGYy4lngWiuHIGOwhh7C2E/VVzjQ2U3jJlMKpx2YQLGERnWG0j+RH8SASvpqX2YUBGpumdAoVJhmoVOsPk4LVsMhTSpjAetmOG9Jf4O3GxZiw3OI+ZEplhuWl4k=,iv:uf1Tg0Kr7Q8iJprxk5wsIlr93c0BySeDDbJx2QjCjQA=,tag:VCQR80mZ/ED3eTaSGRPQ1w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
