apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:wF8mjjw46fz6NBcVKL0/b53lfaKjKiIvQ79eENwm2Mw=,iv:yDMxP/6yAJ8L/NbQtimXF4T1HA6XjChdcjKBHAvlb4o=,tag:n/pboQewMySnBBNSLwfQOA==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5S3VuaVNNL25QUVplL2Iz
        NUlzd0gvSnQ5M3lJbHNrTlByYk96NE01REZFCnhCZnc1ZTNMQkp3QlJlVXlSRldV
        MGxkVmpxUkZwcXdIUEN1RU54dk1FYlUKLS0tIGhkOGkwU042bFIyY1ZJMUJBc3FC
        L2ROeE9oMkh3dThKdk9KMGFVaSs5dVEKJ1n7wqKSS4Q9bSLKiA9wms5S+cHSa3i8
        mWd6lGY4VzY5LJN1CFaGy74L3p6ddMtYcF4jxR26P3oEqMEThV/nyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T20:15:27Z"
  mac: ENC[AES256_GCM,data:fheMeF0wd6jMr/OJCntR8+Fpw3rgOUO74jaMBaYPSXbbc3VvhZT/rKfBqdB36T4Le1iNGaCushMjgC7zzU4BVNlqxz/xUb4lbJik2mg4TKm4N4RC9R01l7er2lcQOp02aBRF5urTlnGR8XlZChrup7gpP8/1tRviPRROj6AMqiM=,iv:zoWsuKIXJ0ZdRk8GVcLS8CxUgdgnImjoYhVkYY9EWmY=,tag:esz0oD13ERimDCI/UET8yw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
