apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
stringData:
  age.agekey: ENC[AES256_GCM,data:4jLcfTMoaJFRwz9N09JeI0Pi9CY0nMhgrHMkNeo9k52+xJVp8HDm5gvoXCWfqfjw5avY2HfyDe74uA+yraHqm9jvsoQ2Vd+RpF0=,iv:oh37WBEmKgJXmtoPUrqR1ptKUs+dVSMpm4KNelJzNts=,tag:DjS/fJ2dpxyF815AjkMu/Q==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySFBzcmd4WC9BeVYzVmNh
        Ym5kTThzMzd4eXYyN1NOQkZSay8wcXA5Qnl3ClZxTXcvTDdOVUloNjdjNnI2Y0M3
        bElYSWsrZC9tRHdwa0VuM3J0QzUwbjAKLS0tIDN0Tlg1R1NFa0tSVm9mRi9HbDA1
        VURCTWMrQWcyV0RxNzBTRy8rVE03MDgK7y+/+B9Ljz/sXiaCWu8WHxrr0ELG1ZdI
        tXYnzVd5ERC6spk7YL/NkXwnTjc+DLqPnKgop8ULMqdGF8/ih4J8Ow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T21:22:05Z"
  mac: ENC[AES256_GCM,data:WJvGLsmvNi3fXnpG3guj5XDa58ns0ZTmNCxb4qNCD++NQliFnbza5eLSpU65mysPesYCLPz/KjMBvmV7RmRtKEw3rsB/vWvIdUeuSD7tpjjsYZg7fNp1dmTk48EzXIx8fnagfl/6FzgouNX6hdhbBciFOIO2FZXiyV6hClXf+h4=,iv:snFc69I929LbnapDSPKLuunciUtG59Bc3Om3eNuMqHI=,tag:JuCfiYeWBpwlt6o0Fp+LAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
