apiVersion: v1
kind: Secret
metadata:
  name: hubble-ui-oidc-secret
stringData:
  client-secret: ENC[AES256_GCM,data:rs4VrVrpuawogNaNH9O7Kimx/3SXpNLVK+B+xMb/eFdrQNgS,iv:PDpBcYoBERAxLor7HMsmRWzFIorVgIdiSsfP7dcdXvw=,tag:GbnlTVwNyodDGxgIxAl98w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbk0vKzhFMHYwdzRyRDlr
        N1MwV0loQ2RNZTQ4cktpOEVhR2IwWU83eGhnClhOeGlJMjB5YVBTTGJybFVEcmla
        OXN1cXBIalYybVFyeFloYndxQ3lqeHMKLS0tIHMyeHZVdlhleDAwUnJjWGNreU5x
        WlZyZWJtKzJVY0E4ams2cUhoRVYrZU0K4luLTPnTQsp3W/8yOk+R55fFsDs1iH5F
        6luruZzO5MicVVsr+/qeJjRRXmB/t01Hj2dJnTJfivKPkR+76Zz2DQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T21:48:33Z"
  mac: ENC[AES256_GCM,data:mV+jsIW7Re23VGS6bAuof4lyL89zbesNKL3QSq0wSxgTAe/8EiiGhqFYy6XTq9+t5d+IpC8KxpXntMDzUORcJe894k2r16eLNWv5ymdM+b+xEfJVyjq1HM14OEq3M4ftNidlRG2jcFpdN2gKTwu+iGfxDYlKLflLGlIWRM5vaGA=,iv:QZiwUID9YMWngvRdR5oi61UjCWiOpBHguMlmd2aNeqQ=,tag:o4h8LqMlt4T9odcTPaT0Hw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
