apiVersion: v1
kind: Secret
metadata:
  name: hubble-ui-oidc-secret
stringData:
  client-secret: ENC[AES256_GCM,data:xkecMkAHOVOzkn7OPRnQQuetFPbnnj5R+hGeFDY3o6w=,iv:YVZpPLOaZRWxBg0Gzq0hIL3dKex5SIQ/ZIWvxvPYbs4=,tag:hDqx7cvz6IY28FtVWJF1vw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTTl4c2RKMW9KR20yTi83
        R3dlSE52MTNLaGVidWFLb0RKUXVLNzlvVkVvCkJ0bkloaENsR3VtdjlZeUI4YWlj
        OGlaNFpGU0VGQjExbTRZRWFFQTloY0UKLS0tIDI3Q01zMTkrYVkxM0EwUDZRaDFU
        VmVMeGhpS2RrL09acTc0UDJLblVxd3cKqIQQyNNhHlCCpEBm15GZYAP5t4y2H2Qf
        jdqstfmp19Avzl07q5hEKCRm0+B/+j4OWnbTarLpfWJ1A2s4kBATMA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-26T15:51:20Z"
  mac: ENC[AES256_GCM,data:RbebizRvPR+Mr7RdxytuuOxCr/pYX2uC70/WAosANUHhLzSxF476f+YxurjHpzcwn2YYbsoH6lNqpmWlOCMuGE2xRkf3s0ollg7cVu2Fx/i4vB/8ZsZxCnl7W+1VGnLUzt4ZLPZg2hwz9w0Y6OwTh0Y5h9uBMvt3dChQKAEQEZ4=,iv:xB6SAFG/xrHwax/mbBRdhyxyPD7s3Xn9Bd4ruUArSgQ=,tag:s7ZC+K2rbU3m+Fsv9h2E3w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
