apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:hJZvvzSCakC7XIed4ZeqM++KLT4EEMxzdrdje3ThpkM6naZ9LEw1whaBkA==,iv:mlqMJ9NHiTl3p6rukNLN0Nn3KEDaEBdeOkIb7YxcOM4=,tag:WaBbWbjnEICD1MyhO/Ioxg==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:rmo5JsGqcX3JkDr3zj3BUXvjPeZqg3j5MbHc5Q==,iv:KajsBvuQjkuk0xQkzTFCPhIoVgsnuMzmrFdFNXwJmBU=,tag:njFNa7di54w9Xf1OPwBuhQ==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eW5MdmVPbnZ6N1dWUVVK
        YkN4YVdBRXNQQzNYakZ2emhrSWNXK2dLQ1VjCnVEVkNzd1YyRkJMY2hLLzU0YWpW
        MGhraHFJdXlHdWxScWJZbGFLa2dBaUUKLS0tIGEycHFORk0zZzdwVXNHUXQweGVS
        K1hTVGpSL1R0N2FhQUxrYUxPcnVXdlkKbjZxk4fBFezwIH8Yo/urbL/Q5rv2yXx5
        My6tYHblQoYGrY9HguxOI4PXyS2wKrjIAI0D4QNgOsKA6qyuX9U98w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T22:12:30Z"
  mac: ENC[AES256_GCM,data:nlNmZLWTehZ7ClqHMzBMeiezxOHLQvCHLc3ZHF9kU+z/FShmJ7m7cmZFCR4O1RfrhOrrY3IUZh/blNhRSO7kIFgnmU5L1O3LHl15tj0xxAWX3USsPNt1V/bYcqx9hVLHCK+f3+HvUZaaiUbv4bR6opWDLNM5EfrBInZ9wRYObO8=,iv:2Mj2Yff0g3Y5uGLgJCgzwYh6K7WgTXw0/7xUyIghbTE=,tag:Bp9caUs7cyOgXW/Kl+2YTw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
