apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:gwtCG4B92cG3L2ErDyguIbmc/DbP9Ogb5oedzdYTtGOA8Th+zlb+LnuZgiC5n0sSm/myKAYsnN+YyH8Wcodp/w==,iv:J5+f5BylM2ebQomZXsIEA0fDf6D/fqHbYdKTh1Dhg3Y=,tag:U5muRvorrSl+DLP22k+0xg==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:mH6aQHpbdXPIx2A=,iv:jNEyrArwNDv2LoOMG/JXJlcJtiU/BOI9pugs/fO0yeA=,tag:aaTM7f4PTkUV2YqRhC2ghg==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VlhDeXJTcTZ4ZXlyMEE1
        cHp6V3FVRVNBT3JVQ3dmNGhBTmFaNzlyUTNRCjJuSDFPckgxc2RUbHdrMWhHRXFM
        VE9YMzhEN01xMCtXOW91d01HUFVZbmMKLS0tIDYvMlVPbnk4Z3FIMGtEOFVWRGNp
        UkRUOTJDdWk0bXRjY3FQTnJad0VrcmcKBnK7MUDzu/zWFZx3wHHraaMdWYtEaVDx
        NvxElGN5oTLSr6a2pY+nwC2Ng73i4fv5bbttzIdTLCz0E4zrwQtg5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:678xtvpPbpemVXZyN+zLujmMfpwX45FNgGWFy+o6ItwfwHAENUwLwee6T8bycdvjSDFlIWifEGrntct+J/q4yVbPKDmDo/4OZJUs0V9gT1PyUQywnCIGEPz8Q3f5ujbPPtITYLYp9C5bNezpFAd/h3kDL4S+FWOdg+VkQ9mdKQA=,iv:KLmLTQ39pJIXpRRQ7sgSDvGZK1Yy+3yjuPqBR+hX+8s=,tag:Blw12mo01X8vLMeN8aVsXA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
