apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secret
type: Opaque
stringData:
  RADARR_API_KEY: ENC[AES256_GCM,data:2I5iGIk0SVy8DrARWAB+YdOH0NmpbpFXdYCj4y2fVLg=,iv:3bR3wZ9sliN4pRSc4X9t/IxBIBS7OyPTUa4yYVg5Y14=,tag:qx3zZb6F6PT2hCbpDTjb2w==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:cqxnFeCHHe2ZOEn2YtSbSAugTfUwXs8d2YixThku/Es=,iv:DDy8NU6Je6Hlk3YAf3EKcZsYUF3wEkRj4MVrI8PpzJw=,tag:0XNHXhKRv4izyyQHorT5nQ==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YlJjc0RqcjdvMEU1ODlG
        a1lYMjB0d0FwK1crSWtyK3NLM0NJZlJtTlVzCnR4SDRNNXZ3SlhRL3NEbUttenEy
        Z1FKSGFldC9kdmJKY1dPZFlaZVZ4Q3MKLS0tIFZncU5rd1JEaWNnWTFqcHc2MXha
        Yk9TUXVWUWdIM285YmhKeExFT0RTYXcKrDLxYAgU985HItW/nhJvqmuhbGSDNkJJ
        n3DiE5wNfqDFMB/ytqHVe150MIZjlmJpSkMNj3DhiyylUHD92mtZoA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:pJSBFExr6vFvA4t1+IUXNVRYNAFrEgHakJo/GjZM9f+JYFh2nuZYTd4JylQmErYVFkY0eFNHpoCI2CPhxzbZsdjUWJ3axR/OrT2eVl89TMHCgkRph9+YTZHCIduo/QXC8vOREJQFjXiGaQbYrB+m7SgXmhnnljyXzFe61fTu/Y8=,iv:C5sMOFiWlEX+fR0DRZ68b6T35+jL9Fiy6futwQHn1pI=,tag:R2EZkthANqCjjhlRANZN9g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
