apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:zkU/yX8q5vS4V9KQ5caO4z2qxHlmLXaRWpLmuTziz/EoaW+xOOOZD7iTyccT64IBInu6JXc1G2N04yrhhXPp1A==,iv:H7qeA1zSCSRGqflZiOFUCPHnOtsRAVuQr1zO/FKNO1I=,tag:CIiwvzxaS9rwS0iVmBiu4w==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:gD00edmmT2m+,iv:uY8mNlpgt4Ljik3LgAPW+TAbTaJ+7ay6Ptl1gYKandA=,tag:foWa2gJPs0pK0R04+qBwJA==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSkZzRDZpR1FtQ08wdFJG
        dUY5c0w4ZG9nM0JoRG9qcFo4WWFqcVNqSGpjCi9DWFpGUEVwOGRtUFJtTVQwUG5R
        cGtNdlhXcXpZMkg0YnJQRVNkMFdxVlkKLS0tIGk3VC81Mnc2QXdzYmxSYmhkMFBJ
        cVNkODVaUGZIME51R1dOTGZnY0c4dlUK73bE95WcqY93nwW/WSQDcu9nGrDujIZC
        W0n04VvTVi0hLBYNCMEtwKoa0Bo/6+0G0Oih7Jmf6fmRTjua9vdEnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:9lburGrFEWsTBha/v62yhYYmHrcoiRoT4tw2goNYtaKQ5P26R/SbubztnRJfjR7IcL3hrNVKGheI/xDlGAUGUW9b1ULBYSbItYNrWX6kn/zd3n23NjuFFL0g4ufY7hPr4xFQCKRYXUT+VRx5KWjEeenk1NfTS1Nrysq3z+DjwEk=,iv:/J2jlVTUGdPp7m1BoCobXOEw8AVWaRpJ3c8PC53+X54=,tag:8GKIPiKg0zT5mlETbU3+TQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
