apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:yKo6TbmzSUSVbZrH2PStcD2iAcjgyhVPyEYs3SbTy+es1wI7dufobnPcHQ==,iv:J+WFFYYvmTb6+h9bcr0tlPPQwZNf4LOVl9nK7u4mY1o=,tag:t2qDYS+cXDN+5lciDLnxMQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:m3Zk//U4w+ZJY4zOy6V1VO8OOZ7T18YK31ueyw==,iv:uUjWGHGYpbHcHrgJM8gwUxDM+J2lPZmFFKkwumdAg/M=,tag:jsRLuiAvqOTrmQuiooqNOw==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYTZ4TlRBcnhJNEp1eElM
        YmFoZ3ZFSm05b09WUlAyaEsvN0U1blJlWWp3CnRhNkJjU0E4cUVJZkI2Z01xTWdE
        UnpPRlJpczlBbExrR2xwejVXRjJSMFEKLS0tIG83VnJKWDF6aUtXUnFNaHNTVGlq
        dC9EQ09ndjJKa0RIVElGdWh2UG9ySkUKnavTlhsq7v+D4FLBabuQaPhRtesUa6TF
        xLMvprkvRWiXuew27bE9dNxxbPHrDHg4TCC6XShG12c84aIyu1PNTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T22:12:31Z"
  mac: ENC[AES256_GCM,data:3HyF+t11p+ogLau73Wsj1Tics89sy5boKmjZRtE7ypXIFB2DGo7ooctvBJMIdMuFWIPCh6mang1NXU3ghUPeK5DAQxx1W6TcCVkN9AG2YlDiqyBKcwyyypx/BpwJeMVOjCgHkypWPV94jvqWvlRmEcSxybI7ZhzC5XRqz4KuSqw=,iv:JMVFEgwrGWm+PlLLlqUVvtO2XvW5uharasNIXoqLKMg=,tag:jR+YX/szzT7XPMZlcsFCcw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
