apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
type: Opaque
stringData:
  HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:fMHcuYOJftxwyZG+ZuB02T2KKUuRCrNdV53UCINaxmyw7nIK77hFpwrZi+hobBrq,iv:L94QhwBrC5kFIgxBzfDmz7qOCDbDvTS7kMZAtmw3iwQ=,tag:FfC18Nud8v+omro4LSq/Eg==,type:str]
  secretKey: ENC[AES256_GCM,data:sgcVyIBEIlXYD7FWTcp/3A==,iv:7nrr8tThrkc2p+7bo1uwyqep1PgZrfPTMDwZ/5K139w=,tag:joPO5Wl0LfZauTlQT8bX9w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2M1RUZGJtb2U0dGF4UHpV
        R1RTcm9sWGhtN2FMVUw1RGQ3d1pHcjhtS3hFCkJ1b294SlZXbk5OZGQwbWVEbVRh
        N0VRM2ZnYUkzeHlrMEVnemJkWTdkZzgKLS0tIDZ2WXFINk9ybUdUR1RMZFhYUW1Q
        UmRzNjUrbXNFeG9QTThhVWxlbUlvVk0KmmurgSSbPa39ySM/8YyYDcdMvuGSrxa8
        0svWw7nsEAVZAsP6TCsc8jmECJbIoGqCp91heDxxHxA1SjuRSvL2hw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T15:49:03Z"
  mac: ENC[AES256_GCM,data:RAUk/0bMUlQLXaDJEptVLApfrZhQoUqiSrSRuGRnec3fUs/WxdCKhhBt7zvCPsyLP7g17TYY+AMIS8QVB4oqCmeXlAjNhH1AjPUqWjxYgfHi1CGE6awbNyUP+NcpZRaXTcqP1K6YBQWctRU32S9fqbLrTXIfElkm2ogtcMTjJkg=,iv:71sZKzbbe5xe7+OTafByGUvq2EqjYAdto3iMQr2k25Q=,tag:uih3MzxMHuP9Smm8/rK2iw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-values
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
type: Opaque
stringData:
  configureUserSettings: ENC[AES256_GCM,data:PYQXUz6kWgBq52/5PDDNF9b+VFum1lUZ3isoEqsdk8sxFm8VPG7Rf04QEClHEI5C1wplKAT1Frt/hVQ5mAZ67e9/YN3b81U+JSF0h3Tf4Nv27QnkAjZ5/PaOIK/c815OnuSSRD//wJJPhbndnykfq7Gc7QanepAuWFFezcL0T2RBRgsItC7MALP1MjxjPNVibL2ZqqVbMM7sogmadIdbOBEo0IQXyWq/+aqsLoLW5t2Djjpf8PbRLMe5m/X6/DoMTISBYEAFGnwPJ41CwUTOJsP/cOfEzL6luWvWwDtCE+02oklhFrNKcH4wW0kdQ/mo+jfZO19RSRYASo6ut3x8JtMB38s1LSR4aldZGLrSmMVUxnhUMBmCcvHDVhZWBH35BDQbCeqVC5KFAr2MOMywbYTzkWhjS6HkwQe/PaFpU+1/nmxGZWzb3mhlmA26M+VKJmvb7iOmxoVKRgcjbHIkLM39TSEuA1QkDzqPstSVgL7TcDa2Rdz6QGrqIthMUdBM66Dq5Z1krr4smAQXHGfyivabFE6gBKCeqz/oavSDaT7tfxxeJPdTlRw6WH2WsVvbM0eXQaDC6EsrG+Tse57UHQbBwhcfwXeN2Gwu3RHs2jvItYm1iPHbDZhzc2l3fCJVOamyq3ITM7Mn+uZCADLcl+ubu6JhyuwrkTTs11TUTEU1asEYBHaqDsvd69SAxYyn4KJbUmapgpoh2yznIUMOBQ==,iv:OkzStIOg24w8iMJgFODiTEcjunKyJjJ/647kSxHPsZE=,tag:STtn3+5ZpqQVQtDwP3RBzQ==,type:str]
  databasePassword: ENC[AES256_GCM,data:UroPi3yQH4HcnCDmLbiExw4vG8uME7XKhFjPPM1Sog/cuBAK4zZ8S2rHhfcc0YZe,iv:1uG+n9JIBijPqA2sh+0yx9LpW8DWxd+G9ZooAzBcyyQ=,tag:NmlCEyOPCh+F+BG6XPrJPQ==,type:str]
  registryPassword: ENC[AES256_GCM,data:5UHpYuLAzZTAUvb0i3RY4Tc/fO02gdI7FuTeW2BmwtdruOTD3W0zTgPYk3bLnsBR,iv:ybfXOAOoIGR6GXfy8seTR/aoi92M4LeiEvsaEO+KVt8=,tag:DQtIyILL+z8vZnt75zuZbg==,type:str]
  registryHtpasswd: ENC[AES256_GCM,data:OXX7oyCAgz3UbeQs0s9HLHQrOwo26PUdjeVJCQVcn6Rn16adhl3aAbsESxt/0oAg4NP1lOj1stGqjSyZJLvXi5zyKQBRtFZBgrZ2Zda1/LaZ,iv:A6qjavxuOD71ldaOkXumJzY7rCGn1XN/QGYXWjjtfqY=,tag:eCLz8+r47tySIRy1zGG13A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2M1RUZGJtb2U0dGF4UHpV
        R1RTcm9sWGhtN2FMVUw1RGQ3d1pHcjhtS3hFCkJ1b294SlZXbk5OZGQwbWVEbVRh
        N0VRM2ZnYUkzeHlrMEVnemJkWTdkZzgKLS0tIDZ2WXFINk9ybUdUR1RMZFhYUW1Q
        UmRzNjUrbXNFeG9QTThhVWxlbUlvVk0KmmurgSSbPa39ySM/8YyYDcdMvuGSrxa8
        0svWw7nsEAVZAsP6TCsc8jmECJbIoGqCp91heDxxHxA1SjuRSvL2hw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T15:49:03Z"
  mac: ENC[AES256_GCM,data:RAUk/0bMUlQLXaDJEptVLApfrZhQoUqiSrSRuGRnec3fUs/WxdCKhhBt7zvCPsyLP7g17TYY+AMIS8QVB4oqCmeXlAjNhH1AjPUqWjxYgfHi1CGE6awbNyUP+NcpZRaXTcqP1K6YBQWctRU32S9fqbLrTXIfElkm2ogtcMTjJkg=,iv:71sZKzbbe5xe7+OTafByGUvq2EqjYAdto3iMQr2k25Q=,tag:uih3MzxMHuP9Smm8/rK2iw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
