apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
type: Opaque
stringData:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:sHEKi4/WH11FdxGbrSEMfUjMJiWS6wyavhxuShuBZwI=,iv:6tgvgWg0MtKdkxdFHgS9KRbv4crz8X1PhtwdMhR/ZHM=,tag:pb8b+/6TBhNT0n3Jk4DQLg==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWXpOUEFFOTFEQ0RxZTRF
        anN1RTIybFBGTitWMWY2OFY2QTRmWlRkcDJnCndyQlpGQ0FLa3FTQ0ZwQlhXcW5F
        RGZKSUw5bGh6VWJFMmRWcm9HY1FkMWMKLS0tIG4rSWhFRXNzdVFYNjhiKy9QeHBy
        UUlMOTZXZjkvV0d3RGkzckt5RDMvN1kKqsPU7/3Xi54ycSdRboksbqM+hcQjiDnA
        1firT8So3LSrAUW713k0fWdrcC5IdT4KynTQbRNNWZcoBqstCydcSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:ixqFitu9Dr2KUxUYZaL/eYbJsnsuc9A9zUcR+3bKDXDZcML92f0ttmXNEwf7pDc0wzv1MJwXsH/Rs5B6k4PITDMVPrqVuTDycOxDqNvjIiR6WTkoP0Rf9Ly/MlHSYQFxyjnUTGKfmZGP19a+vCsYM2p+sh9okI7RWdqmCmHzCcw=,iv:biSv+7Z5IzDV13mPAhrTB0zpyXoXzSqCedQ1phHekJE=,tag:Mns4SCHv+FzXsu2/N7ujZw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
