apiVersion: v1
kind: Secret
metadata:
  name: sonarr-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:bWkLzamPCWU4yiOpYB3NXZawtnVYyzFS7n5fe9AVf/aeen8KmluKcinnfx7aqY7DT/9UM5ESuK2Pw1mKBItVPQ==,iv:bV8Yl7w82zJ0c6fcKxNwiLbHLbzJ2T6i0QGfPvn26dA=,tag:ZhfnTiTAqmEk5M7/wiGsgA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:9Xtuo097,iv:hZKiPZqCJC8OWYpjdRRZn1ZWYlpAnjihXxohhBuP0PA=,tag:EwqiKNr7kTJXOKD2YAEHbQ==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLY0pla2lWYVUzK1VyWThU
        VDdnL01pbmVHYlJzZjljSXV3QTVTa01kRzJzCi9ZTzE2YUZZSWd2d3YvQzlnRCs4
        ZFlSUGcwL1drbWQ4eDRVOGFnbll6RGMKLS0tIEdxdTZTREhuWEMva2hnZzcxeHdG
        V1ArK2Fkb1VBK1ZvVUJaaFlNeEcwNW8KzGVgQ3JRkOD+SfRNxWVOmN+BU2gCxwl4
        TuSD79ZownYYmZ1JiWKahL9POYni30KAnTF6odyDT+SRsCgb0+tsig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:nIN/q2AqWSdrx5Xjr2aGYudU0x76rPTCyPEsCPggJBSvNSy1SLPf+Iqfyn8U8VrLn4gSyogDdNA4AhgwDKGfUs9O6RC6/LO5n3oXYI6PLqn601j7/rMZszGOn3v3Gfd/kU5XCasDj+kxIam3FWY3M2Kj+GTJT07Bft/bt0dCBXw=,iv:8Zm74K+b/w2i9dGzQIIlg5OvmmqjTNKAjpTrXA0p2/Q=,tag:XhKJt3JLiRRrxDtaCcezLg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
