apiVersion: v1
kind: Secret
metadata:
  name: sonarr-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:22vAWHSP3TgDczzmJfdkuQJ0oVZJdtFv+0b9iGLV7Jn5RcV888k/sM/ulA==,iv:R4dDmPhOzWxEjyc7+5fs0Aqdjt74qBcC+YPIMtB1K6U=,tag:EAuSOb4FRWz1iKLyXfnWBQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:4uS4fwcvtLQ+5RjODH+PegkSDFY8f8IfE9AzTw==,iv:9Jv/LD3PVNHd/i17CD3t/Z/WgqlX3ZxkHSEHUcbabDM=,tag:nXonCf4Ee8ko1+FlK9anog==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNVhCUUVoSkw3TUFhTXN0
        dWZ0TllvSENUL0t3MG5EUkFEMkZ5NUhha1Y0ClFiR01BOEg3OGNRRUx4eVBGMG9s
        djN5NWtveXRqZ3hQRzlwV2lNcTlvZDgKLS0tIFpyV1d0NklQMXlTbG01OUkzYzZ4
        aTY2TGdFdWdkaTRLMDY0cnhSZU85Q1EKQlXYaGHuYZoh56fqBFaG6N2sGh7RBdkZ
        mKxY/FGRPcdtt0GDY2QbCvDue7l16Tu1ps58z7V1X2ch54NRAiG7cA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T22:12:31Z"
  mac: ENC[AES256_GCM,data:6QUlkGuCemuJxkDUGhzSzgAYRHiAgmMDiyKWHrxZNTSu3oNsW6HAUXCMbKkTX7dL8kkKytyFZpj13IoUTypkBgVu5wV4GBATrC7LawcDEMJCpG1ubAFbukn9IhcNj7GF5S9APgWYdUK+mJBUPPBagsl0nNQ6HN8dY38v8NFO8Ns=,iv:adi6eGIK3/edDc9lg5XwuTHPBuzHSAjn4vOLML66HBQ=,tag:h1QtzPArp5+7mHjRQmBpnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
