apiVersion: v1
kind: Secret
metadata:
  name: brrpolice-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:QRQDC2FzSPAL3CljeIbtBP5CJFf3sH/gk6NBIvE8ENsL3K1rjBGq2Ph0cg==,iv:L+g+ZVjYtcLjQ3Kqo+c7eKTY9e2BVEclKj2LYO/M2ko=,tag:aaBLQHHyynGBflCR2fjvVg==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:9dG1lMnLNzEkRNNVt9da/fmfoEirsWfdCWimQg==,iv:kg27gqNyhFHsr7QFuaDS7fam1PsMHRe4oI63NnEmJ8A=,tag:noryEQXrYp6dENIE4AROhw==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZnFuYjgzT01NdWJTMi9M
        UzlWWThXdytRb3hTQ3laOXc4cXZUc1BkV0RvClAwS01XVUl4MjBqY0VjS3BiaGZn
        dk43VHg2cHJBM3haZUxYT05OL2xMZEEKLS0tIHJJRWFqYXk2RVRzb2ZLdGg2Skp6
        ZFV5TURzL0NpMllsak1VSnRXTUE3aHcK9OVJQ57K5JNHX40a5hwkmHhXW/DLvqss
        nzjLdZa2n/MXVYkLpr9xJzavqBTJVUJeyqZLYWm2Eq2qwU4nUjpPFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T22:12:30Z"
  mac: ENC[AES256_GCM,data:NO+KoyfBNK11VYMu9R73/ArGXQ/yKsPWmlHn2MOCSvDwDJlOP3eZwONK0nNOG6trSr2a9KeLB7n7Bc0dmZcCPRyN+Z8RUjRiHsOJbejsorZ2LLScmLfzdt+gZU45OxCuVGknZ0pnlo5/xt5V+sOGo93J98SCIlhbVWjSGbWZm4I=,iv:yH/2/NBqRONIfgtx10PgOHd+9wjoxGn9IOYGr1cmtMk=,tag:8jkbQajGlft2mzaPBwtX6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
