apiVersion: v1
kind: Secret
metadata:
  name: brrpolice-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:V++pNjq3noErX0BYQC4LYKQZTbkWI6qn97A8LtT7CJOrwEf7WEpZECHP6/VMndJBDtwWf6Y5Qjva6GRbWxwQ1w==,iv:gVKMvusscCN1ajG5lFqcC5YsB9viWohr61ZQSBrYn+Y=,tag:nynJqioNvDnaBlNeH2GBIQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:/yJNn9yv1VX5,iv:+65KG9h62eoeoG5zmTTs4rDsqgu3uzs+nU1FNT6k8Qk=,tag:5GFactIacGf61soqEXQbJQ==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhb3NlcVEzYzhTRVRGQTBS
        NERHQUM4MUJaUzJRUHdNRHZLUGNhaVIvRmpBCmxZR2pzV2U5MzI3TlV3SDlUSEFD
        clBWT1UrUjRvWDdWWUlHeTdPTUJ5dG8KLS0tIDEvcGo4Q3lkcVpCRHNCd2I1TnZm
        Rjc2NllaYkRodWY5bzdDY092Y2V3TFkK19XlXSqejgYZhOrxA3Oc3HEW0UhjOE5D
        figz0iZ81nGm7tQ5iipoSYYXWcQpOZsWG+VA1iOPDbsQ6FMhxh+Kdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:3TEl4jAlaNg0GG84peEWNL+kOyy5v3Si96RpA8gMNcnw1GIsAy4KrLaFTgyWIlNQF+lGhrqdShVGxXzVTYSRV+4AOcbzQvrd9h7ISejfU/Jhkf4nXMxkiC31gv9rq9HisUiwoQ/NJTP76R/byTTTXdRHgJklSoJfT08Wfm/netg=,iv:drb3EBBBQtfVzlT5OsvXUGD2lW3SVgV0X6JsueBnLio=,tag:Jium93oZK10Mes9Qe9+naw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
