---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: vector-syslog
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.59.0
    digest: sha256:807a3651fbebfd01a3ab867978eedfa2e29c66f9a80f93d8070f6c39163dc6c1
  url: oci://ghcr.io/vectordotdev/helm-charts/vector
