vault_truenas_admin_email: ENC[AES256_GCM,data:l/sVR4uZY3EJjgQZTy2gXM7S5432gTM=,iv:f/sI2oKTSupb2WBg6ZIf1UwaMxuti5Xr0Cwt8t1yFPo=,tag:f3wd0uh4n7awyCR2MK3Y7A==,type:str]
vault_truenas_domain: ENC[AES256_GCM,data:qNj4+/TOLdtPCfvPskFZ,iv:yLSU+VTIw7RRXOIeNUWKaw9uTizZFmJ3wpEzSpIdiq0=,tag:ZWKrxGF71zBdRYjP4zLhNw==,type:str]
vault_truenas_ups_monpwd: ENC[AES256_GCM,data:7mr8ld6u+Y6r4bXPDd9NPTO/,iv:X8fl8xQKdRV3v8Uxqr67DeQLH9IHrWEhCjr6TZoiK5M=,tag:ORCnoCFyC4sywkjgCJ6fDw==,type:str]
vault_truenas_admin_password: ENC[AES256_GCM,data:IDSGcsA8BQGQXC4J4Rs=,iv:9Asvnj6jfBmnYcO0F5Js6O80BGnqEhOkuoJDpc10Yz0=,tag:xuiNJWpuCs1v9uq57tUpkQ==,type:str]
vault_truenas_cf_api_token: ENC[AES256_GCM,data:BEU1fqtoQfLtdZikn0WMoYKM04H1OS/O1N5IIViUWYyvkgbM+/HilJUIAR+CEtZGL0NAblg=,iv:xpc3sRystifTAfbgBRVV1vVn7lgkuGPrRP8UN+NhZV8=,tag:HaGnId8uFOtkosjlm3useg==,type:str]
sops:
    age:
        - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SmNOQ1c5NTRwN2lEVGJi
            KzJtQkpyZXBFRXNHUU5jK050R2ZFTVoyNVFzCkJoclV1akVWWXVzOXdsMGtVTnR3
            VXpkZDBvVk96cWF3SHhTcVFVMjJ2aXcKLS0tIGZVZzdZUkx0aXVjdzdYRnZiVTdk
            NXIzSjZpYXpEemhSZ2toM2hnbDR2TjgKOPDEQhZsxnwLxZrX8mzkKRTSfHBa5jMS
            ItqBwdvad8BfNLn4hBu36IbdjkAw+rn07k58BikVZnXXXOu8GvTj1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T00:50:45Z"
    mac: ENC[AES256_GCM,data:5vzP9AcP+D1/qWUN/om1jURV0YOdxEoFyYbnjMIo6HXtQU5qbCKBXn1cTa7kT0lZBVdMop4sAnoqdhRQaPmdCFZKX7LHboGXynvDms4uflpdgpfrSqq+1IUspTOGRsNUeFZra2c9kyHjDycmDjzG2er+Eaq9zGhgRQB8ZzbKMd8=,iv:nA81UDgAmavY2/oUXVeFPIiORNzs512JpjAwqu7uFQ4=,tag:7e7gapcmpWNzbFxcqPxI1A==,type:str]
    unencrypted_suffix: _unencrypted
    mac_only_encrypted: true
    version: 3.12.2
