vault_truenas_admin_email: ENC[AES256_GCM,data:DT9hqdOFl+OjjZDvenxl2m3jd5IInoQ=,iv:5B2+2onYlVmwO1ExN8SY7LI9UWOqGk90VQzCfcfqFXQ=,tag:OpfQvvP0SRF1p3oQ23RoNA==,type:str]
vault_truenas_domain: ENC[AES256_GCM,data:gtcriG/P9dm9tPi72tMV,iv:fuyIDccVoYJ1DeCR6MsxlhxdSdesPae2zTYk3xpXfWw=,tag:wMBx9xwCFfDsyQFG6jN6rg==,type:str]
vault_truenas_ups_monpwd: ENC[AES256_GCM,data:Zqc1pbAoQ7VO5ginEypjxPHF,iv:jRBMOvfk0kZdG5trZ6LXESRfTqPg6ZWaWl+4UTwjUa8=,tag:ERiePZwLu19wbvJCuVVZAA==,type:str]
vault_truenas_admin_password: ENC[AES256_GCM,data:bOg00KXIdF0jNxModCA=,iv:sW+SNn7ysVw4Wemy7OMXxN59GBz6VGBNoSvqFfZaM/s=,tag:LPAG6clu8kiAobPs7CH/2Q==,type:str]
vault_truenas_cf_api_token: ENC[AES256_GCM,data:z4FpptdE3XNwvX+UcS9e/oYhF0XJasM3KbqEHWL05nIh0EDvq/mFeWiYXVDTr1TvQDRLcF8=,iv:1HNYcMRYXcu6FkiTK31APKcZkHwYxDqe5xf5YB6PDRc=,tag:wyIhklgOeTRnky60DzWyLA==,type:str]
vault_truenas_b2_encryption_password: ENC[AES256_GCM,data:xHRmiwip5bKHlS7MSyrG9nUGlOsEVoQtAxY2DqujAsRlslVU5j66qEusvI9aIRjyFOlItk8kCIi+sCXQzxgGJgVXDCJaGbstc4KY/rqjm5MIKowbygMorZrEOxHhCl/+PBoqug5P0OgZluFUmlfpcwA/PirtlTY9n4a2ri4ybw8=,iv:FiYU8c5t6U8lflUa/PRZ+4dKt8SwL151KxMFPkZKg+w=,tag:HbIWcRoeggZ1PqLOz0ruEg==,type:str]
vault_truenas_b2_encryption_salt: ENC[AES256_GCM,data:nrkhEOVeipfT+MqfH+ICu7MvatD+MW+0/3Hcl7sGY0BeSRqMUH6S6VPAwHcafy55nZXNVshDOt2dME8t0u2kBr524PI4SzFnhvZdB/L/nF3J27+ELVZ4xYdTpWiiN7IBkraMh6wrOWj6odlcdbz8yy0++9Ox5UcsF1lSy1bB89M=,iv:WCLsV+X680X1E4ijiR42+3wYQkGzoF1ooPHDk56iUtY=,tag:8IawkTzMBmeqPzSSLj5bxA==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOXdMODJxNUY4U3NkTDRU
        TVdNcm5FUjJjSW1GZHd5Y0NOZVpsd1F0QUZZCit2L01yNkZwYVc1WktmNWZZa0dP
        SWhseFdUSXNJTHdvTkdrRTdXSDhiYjQKLS0tIHBLZ2kzbXhkOVY1MjFxdC9oN3VC
        S0VaNkdMNU5ibGhDOGdDb2d5Q0VIdFEKuhl5zVSww2vK++wTOduM3JRw9oPXVJE5
        4OgdmQfuAh3q2WTmC7rb2PeE1RDVVomDbPB9ElKGqZ9BaU/FNFRRxQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T14:56:44Z"
  mac: ENC[AES256_GCM,data:e9B5mIDRbMA8x2m+VvIS974hQil5NaxzHDf50tHnywi9QtmnKId59HMnLsSGYgcnXuYzY8AmV63PQdFjSlThzpYD/fJ9sUVanCjYYJ80uZhIEauB147F37YAT7JupjOEElDdbJSOsbQee7RljL7B0oYPKNUv9r8YPsQK+oS3xXU=,iv:jeXPyhNUjhPyzJU9vTHtq1K6z131muBbGhQC9Sgl1U0=,tag:msf6mHNRjVQLD7+kSSdrng==,type:str]
  unencrypted_suffix: _unencrypted
  mac_only_encrypted: true
  version: 3.12.2
