---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: node-exporter
  interval: 1h
  values:
    fullnameOverride: node-exporter
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      runAsNonRoot: false
    extraArgs:
      - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|run/containerd/.+|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)
      - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs|erofs)$
    tolerations:
      - effect: NoSchedule
        operator: Exists
    prometheus:
      monitor:
        enabled: true
