apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-oidc-secret
stringData:
  client-secret: ENC[AES256_GCM,data:KlWnCPueIYvAQ0sJCaAqTpziIhUvSBHddhMEHNoVd8DNRA8UeV/2rsHnMqHHIM4oWA==,iv:aoKXj+Ze1Mi+FcIylx0lujyIIIDM5vjJXA3OhgY9Hbo=,tag:cj/JH9jhHydYBSiZ7moFbw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RGRydkhEeEl0VTR4YUg4
        VERSTmpYZWx6S2p5NkNsdkVjZk50TWFFdzBVCnRZejYrMERUSmE1ZnptWkVmRGp4
        THNMRGY5ZzE1WGhnT2VDMkhwYkV6UFUKLS0tIGF4d2Z5bWVEVmVIa0svZnhkZ1cv
        ZHJzOXVSclIyWC9sUXI2Q004N0dpRGcKWo5RpudHfOpWFQoesmoxElk/ZmPl7SgH
        MYCxDrK4U9cabl5H5vvw0FnznT+L2F/qyMJW8F9HvN9K3CxhyF/sCg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T17:11:16Z"
  mac: ENC[AES256_GCM,data:wbAtiwxOyLClGmaQGQqNrquxmZNBNvAD7ZlK6bL+sAVPlF8tUkO+A5NG+E4BJg+K4KW388wu/+4cI9tL5h8T6Xw3f+7Xyw9/FdWSKRk2d0CJZNIOaA0ymI/qfKNvp4BHIpwNfsf8IHfl90QFeRDQFpg58k6bXayQ2TKl8fxMsvM=,iv:Z38e5ThPSoqTpJIJTOREJI1Up4EyMhxGGIJmE7A+/wg=,tag:JtD5SkSwA0N2NKdXR5MGcw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
