apiVersion: v1
kind: Secret
metadata:
  name: prometheus-oidc-secret
stringData:
  client-secret: ENC[AES256_GCM,data:+xvOijMHzfPoowpLy0HycS0f7RokOrwr9D5pgUai9i2qYE020yEBm9PBdCv0fs0=,iv:nX3hZNYNQMu+fVNXkHJcgCnEJ39UpwLyKMPWcKN3cKE=,tag:u7A7X27y0vjK7a95rxWo8A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z3JXOHRkdFBjQ2ljYlF4
        NVF3RGI0dHdRa1pkdU91SVFWQkwrMjlKZUQ0Ck9GMEE2OUhhMFNvQWw4TTZWSno3
        VWtaUUczRjdzKzRJQlBLTVFxMmE2b1kKLS0tIGR4SjBhKzlFYlRMcDZMMFBmeXh1
        YTAzK3k0Z0xGY3FmcEZGaWNGNEJVL0EKt6Vw/bLmFw9ARyN+Tdh377PZzbDQadDU
        YWrarIUvqnq6FZgsX0xQPexBw3/L6rDS+chfKsHmsA9MrdOYIHJklw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T17:11:16Z"
  mac: ENC[AES256_GCM,data:lCKjv2V+c1T5qwLv+9DegvEyuwpcqwQBwtpbew4VxVZ7adha36KW47oyS8VZrpcr6wy7sW80qiI7jcuELf5eWn0tzTOLF/kAWQ6Us1arqnZqQ4WkiUV9+ZzzWvC0+AexocrleSDyMDZnPLkCO9QM8vJRSAqMdxXTYsUxldrtE14=,iv:reIm7a4Z4ws4vshCuXpFjm4dRPJw5wfu6ukTD9goy+8=,tag:/3frsAeB1FnbK8KFkeOBVA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
