apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-oidc-secret
stringData:
  client-secret: ENC[AES256_GCM,data:DoYAj9kSvWPffK3GOlaa4/Wjc9UIjGDgVjxDcGvfIs4=,iv:MKGApB7PU4tw0tTJFRcXbJPB9KRB0GR+pIwjc1O3uHI=,tag:4Sxdq7v0FyZ41UmAMk4kAg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RGRydkhEeEl0VTR4YUg4
        VERSTmpYZWx6S2p5NkNsdkVjZk50TWFFdzBVCnRZejYrMERUSmE1ZnptWkVmRGp4
        THNMRGY5ZzE1WGhnT2VDMkhwYkV6UFUKLS0tIGF4d2Z5bWVEVmVIa0svZnhkZ1cv
        ZHJzOXVSclIyWC9sUXI2Q004N0dpRGcKWo5RpudHfOpWFQoesmoxElk/ZmPl7SgH
        MYCxDrK4U9cabl5H5vvw0FnznT+L2F/qyMJW8F9HvN9K3CxhyF/sCg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T19:07:16Z"
  mac: ENC[AES256_GCM,data:yp8WalBFnljXn9mxFhZd7tLNdk+K37HH+VFIZLWmZB79cDOEkbV/CccwqP6R6nGFJDPJt94yTW7o+VYeEFJtszxmYi4HK34rewoQYCMXG3ibjUAms9YCBcjV5ShFt9Ol0XCuqr2+X6w8ANTwzRODOKF8SGVvxvH8yyJjKSG8irI=,iv:rUoWa2saABjeqzwl/fC2lvfmW7ON0U/7GZgbtLpXEuU=,tag:4GepNvPktixYaRK8hvTi1A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
