apiVersion: v1
kind: Secret
metadata:
  name: prometheus-oidc-secret
stringData:
  client-secret: ENC[AES256_GCM,data:qmBZhHaNQ4+Frsqq7HPn7/mns0oacPOwV/LUGX6iV4c=,iv:5F0EFZPTEcpx+lITAB08dOhk+PmH2koX7heZAmzjAWc=,tag:FAs+FbdgIwJkw1T2S3KYTQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z3JXOHRkdFBjQ2ljYlF4
        NVF3RGI0dHdRa1pkdU91SVFWQkwrMjlKZUQ0Ck9GMEE2OUhhMFNvQWw4TTZWSno3
        VWtaUUczRjdzKzRJQlBLTVFxMmE2b1kKLS0tIGR4SjBhKzlFYlRMcDZMMFBmeXh1
        YTAzK3k0Z0xGY3FmcEZGaWNGNEJVL0EKt6Vw/bLmFw9ARyN+Tdh377PZzbDQadDU
        YWrarIUvqnq6FZgsX0xQPexBw3/L6rDS+chfKsHmsA9MrdOYIHJklw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T19:06:02Z"
  mac: ENC[AES256_GCM,data:ZxqxoJxAbXgGBeX0HVvdrCiQSV2npvk65vBbhWiYO1E934fAC3vm4ACe26Qy1Em5eJhsj8Po4+V/cUzHJnX59H6d9ViJ1UeNKc/1uErZC9XtPQOylvllyrpVaR9KtpV0hTQzp00pS22eERw6O9XcTjyAHIc4ndb2EIHWAMK4ht8=,iv:zdSl88Y5SxluiyB8jJeSQk1ck8/UwAvH7U2oQCjl26M=,tag:OXQXkuR73Z8p2adBVxiWow==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
