---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-secret
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: thanos
      endpoint: garage.storage.svc.cluster.local:3900
      access_key: ${GARAGE_THANOS_KEY_ID}
      secret_key: ${GARAGE_THANOS_SECRET_KEY}
      insecure: true
