apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
stringData:
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:VsMaVAGovAvQz/pCuFsEkehVmqHenZ8C6o2wckX2YeuNFsFG4/JNchxmsR+N3ZTqWTW6t1d2svpPwYHAK1UNAm5MH5HYsOJByUKRNVwneZY5Xzae4F83elZJg3/5aO9LBHhHX4/sCA88kIDZl5dIWBi0SEu20Qp1,iv:6418/X0ks5QHncrE/KIh6A01stBMZvxTeirJ1C4eMz0=,tag:Zp9VG8PwXe1sojhVHTSZtg==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ3ZmU1N4d2VlYW9IVFY0
        R2lzb2EwV25vSG1vZXpzQ25OV3VaL3JCb1VrClVqWEh1QzR6U0dJT1ZYT3B4RmZt
        WEhiRXZWbDlJUW9wdG04ZFVkN1gxalUKLS0tIGFNams0Q2hQRE1rTW9uRDRMQ2lE
        ZTdBcFZESGRpWGFvQWhXSVJZL2Q0dkkKKveRHUvisP8gbKc0uwVVUZNq9AFwAvek
        mmPeJY8hTIrXU88GiCTFeEB6KGc75yTNPdqYDEnZpVBTBPYh8hLU7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T13:48:04Z"
  mac: ENC[AES256_GCM,data:/MN9SpW0KQOtKjjd5ZSvPRc4wkJcTj3yV4XYqwCyc66efJXCLSo2zshuxCSjOhu0wvBkBd0YEuYisgtN8kCnnbXVko2wTv8R/+EBSZmch7hg+fuSx/1zR8sq77KtNbGHe0cHrBxV5LiI+AUpLjHNp9kmAw7PFqXDh3RevzjLnKE=,iv:oxG1yAjq8WNzaXFFW5uDbCwy7crxgGhzD7KEP9m64pw=,tag:Hlh587PNxMsAGWBQGwbueQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
