apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
stringData:
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:VsMaVAGovAvQz/pCuFsEkehVmqHenZ8C6o2wckX2YeuNFsFG4/JNchxmsR+N3ZTqWTW6t1d2svpPwYHAK1UNAm5MH5HYsOJByUKRNVwneZY5Xzae4F83elZJg3/5aO9LBHhHX4/sCA88kIDZl5dIWBi0SEu20Qp1,iv:6418/X0ks5QHncrE/KIh6A01stBMZvxTeirJ1C4eMz0=,tag:Zp9VG8PwXe1sojhVHTSZtg==,type:str]
  HEARTBEAT_PING_URL: ENC[AES256_GCM,data:PoXxeHUKxVFGAVzKsAwbEFYXIo114dWaxms+qVjjmbhwxhXwsQ==,iv:Q1w+xgaw4Y5awc6qcjPz+YSAzlcmh75TxLpQfXZT3po=,tag:veZzg5NdhwzLcKDvhkHADA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ3ZmU1N4d2VlYW9IVFY0
        R2lzb2EwV25vSG1vZXpzQ25OV3VaL3JCb1VrClVqWEh1QzR6U0dJT1ZYT3B4RmZt
        WEhiRXZWbDlJUW9wdG04ZFVkN1gxalUKLS0tIGFNams0Q2hQRE1rTW9uRDRMQ2lE
        ZTdBcFZESGRpWGFvQWhXSVJZL2Q0dkkKKveRHUvisP8gbKc0uwVVUZNq9AFwAvek
        mmPeJY8hTIrXU88GiCTFeEB6KGc75yTNPdqYDEnZpVBTBPYh8hLU7g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T16:57:33Z"
  mac: ENC[AES256_GCM,data:grnoXvV/QzQ3SIFT/SvGct0I8JhKFM75L7GoJATEJexyRmY/zmgp/3jU40cnonTMUJBAkYXq2MxCdrTiUGLKNTG5dW+9+FZUez8omugu/QyNngT+UUWXoBxks3uGg9g7QBgV1UaWaA4Bzc7lU+YCn3sx5qllGLAU++k0b+USzJU=,iv:MZclRkAjpmgxUY877ooSH3//D3t8Rjd2GtwogG71koo=,tag:T4dPDU0jF9mahVyCW0dEsA==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
