apiVersion: v1
kind: Secret
metadata:
  name: minecraft-bedrock-data-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:+GD1Tw/lksNnA+FlL8JV903boYjyz3cgcghj9eXaHCzhIBoNYXdo03OvVw==,iv:ufexfjDPk1lFBCJU84AymZURxC/2VapAk4zvoINAM/w=,tag:Gd2cajRJzbcSBhip/U+JJw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:5tbnjVPI8HrlEbqyK3ENCsEqDHnvLGCN2dD/Pg==,iv:ZgjWD1nvy077LQts2+21pK5+Yu72m3T8BzLTtc78Jq8=,tag:QPhGCT6NKykEWYNszkNgxg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZW9tQ2d3NTFHZTMzakNC
        RzJic0c3VDZHUUU3K1EvekZ0L1RWYVdiRUJjCmZVVDdyVUNQNEp3dnZ4dWdWWjhS
        OXhyRk1qMWpPaTI5b0FNWnpLN0hEQW8KLS0tIE9FUklMaE8xK3BveWVPRnBOZGJU
        S09jRENBLzlkVTVTemNiVnkyMzUzYzQKKbFnLmR0HjaNx1YuKTPePP47SWjxDrps
        UZT4+w6kRrR1sJVN2qnGZE9GRrGx9MZaEoqlxxMkjMnP3dbfS8lH0w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T18:54:04Z"
  mac: ENC[AES256_GCM,data:Bj5QhcvrbUlrVwXglr837R0Oy3LpiYU/EhdTivTqHOTBDj2fAk0WujnL1vwOrAUZaZeynKtR2kx+mKJ1pTfUEzbJ+4zuUSrX3upHodsffMRhs3DaN1rgNy3FiluvFtD3mm3gxmJInkE9nB3BNX5c/n+x33/CEDXJbDTXtIJ9bPw=,iv:T/O5su0tHCzkhHI5KRfARu5i8ZvNfr1s5Ib1KbOCIq8=,tag:LcwQlZM3b84ww8M3r1R1IQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
