apiVersion: v1
kind: Secret
metadata:
    name: democratic-csi-secret
stringData:
    TRUENAS_API_KEY: ENC[AES256_GCM,data:M+kGVUVLVFZQqg1qkJwXqknKs2UThfFNG9LCXKHOk5qBp4lkBQcnpzsO+9I5A9oDTPT+ut8U4Q5d0h3Ad09r1SAe,iv:udRg5eMtwJc1vlPWySxsZuQtASLTPvhfXL5xUnDrZiU=,tag:qcKCAFJSr9CnkLdsDxV3Jw==,type:str]
sops:
    age:
        - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNzdsSU01dUIwZzNlZ0Z0
            NmVDdW0yYUdyUGQxRnNpZ2w2OGJwTFIyaFY4CnNtMXdORDJqa092TlBUV3NGYVM4
            a2J4M1hQTk5aSjAwNzd1RGpsaEI5U28KLS0tICtvZnlFSFJrREV1T0Y2YkIvOExl
            Q2tnM2xzM3FMRS9BRGwrSkgwUmFlTXcKE7oNCFQFXrPGvCPjNONY9SBG2viasPuQ
            mAPS0nLlGOHIg5aDOYnjBff7TUHALkPH4WcNpPTiAar97wWMPV8p0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T11:41:54Z"
    mac: ENC[AES256_GCM,data:nv/RWzvTo0Hz+OwzzoI3a8FPSTtGrmkDR9mML8SlQjbz4jjkPc7prXKEwBLjWbxyMsuaV+cIYOhQg2IoX7NgLkUia0nHdO7brWo38R16q15NILdrP1dEs7vQQ2VNY41LqbuLGHFKqQNahvYto79EX/IJbr1YwlUQdHdrKJqjs24=,iv:v7c/9pgLHau40seez7m44dUwjPAXqdUX0fC7EsfHoZ8=,tag:BYYH/3+82oGucHpJar5qDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
