apiVersion: v1
kind: Secret
metadata:
  name: democratic-csi-driver-config
stringData:
  driver-config-file.yaml: ENC[AES256_GCM,data:TqEckT6s9c7hy25D+DLmKq2Ns8KlphbU6Cq26GaiaEXm0FW2TH+CrvbFFFEfFwRX6JrfF48NIKr2xlF1GCyEtico/WRKO/HSmlsu3hDulFfA7XvSRqkHMhqIWRsPsbsCgRV+hKLxWl7bHeMhAdpUAjLvQm5cwfefntzGIruJxAUAuADlsylFyXamjTmQmIvrq8YA9Nnrod2pWwYU6Gof8BmQT/uggzTwe1txErXoG1ruhCc+ybVnCyS8fVcITx5gzQVWE7cM6tvTEAANg1qsGXwBkdOb5pCXG43L/HOLMsQVTza6apTG7lkAYWs/yzTmgcieZR0HphoKuRCQ5AtmvrKgthtdyUZ7sbzG/SI3u61ATxoLnliLUoyDmIywrOfk2p+ycQCV6lqxFNIb+yAcAwSvaEFzExElEJQmU07VJsA82tyQVXgGvht8w0QCyUMcE+PrWeKaf6xmRjhE56n0QyrsucPDebF6odCQxQKhn6GYkrXhsY8rKFuuKsi2QliTorfRSHAYSkiutFgDbkbvfmDdLS62vkJEXsLWxdnayPOrW8dkg0YwYpz+26e1zzDQjqjs38fsru8i9cDVRxXKs9G2nLYijmUUxhMUhtYo0EjtSiuOG9Hr+Lt0L3wO1xNKS6h7mvH4zESafdRvlYUvRATxDJoaJkmLOWNVwv+ICQ4S5qom0LbE+pfBttweJUDb+e4pkzCGWQ44j/PQMKyS848/5tpT2b8lS8Gx6csHiM5oEJwJt3qly9ab1rB5p90OI2Ty5Ajpb4llnBUpjt+7R8CjP63q01/WUAi1qqtdYBP0MAw6PWV6DK5SNdWCbs2vViD173arunPuJlCp2r7squSpBVS8lihW4dpWDKxJtf+bzXoeBnF4vemNKjMXK0/ctFuUqpHFF+YyssebRIX1IOGR3uTYbVsA1CSrvkowKt8cdhlU3ipGe4jrj46smy2ae72GnG5/wo3C+lI7lZ9QxxqH9DRNC9126NnJQS2BsNkxbd6ocatVTA6Ezr/EM6Ay7Ig/aN/g9NrlRJFwU0+8LM7CCJqbAEVIWGs4FNigE3ZoNLDU8lqA0MlAH4SprOcVAwNFUi6esz+UoUusgYe9nP9Mu47rmzFRlETCh2orYD7MNRQrWP3JtO1fWivN+VwYAIevpgHsYQ8cKChQDMzqP43df4qBHwZVz626fZ99e6Q6Z8A8DLtZGp00a7irffC2kjDkUBwWaJhNFVpXyok7eBbVc4lez+nayQJQmuWpqeWq6i6fo5cpSB9xa5FNGNb+7A==,iv:sJ9vRntSrs3tOrGftx5W3i1Hqs41gGDjGSbs5evT8PY=,tag:YlSZak70uBS1tCPev/+JFw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNUE2Ym1QVDFYK1A2Sy9y
        NUdDd3l2NjVSR1daTGlUUTFKcjJxUGRGaUhZCmNNTGtLZmprR1RQajVKWFQwbGRu
        b2RUYWw1OHZlU3ppWEpLRklha01GOU0KLS0tIGNPb3JyRFFuZ05WWVF5Z25GN3I1
        QklKR1hYNDkvaXZUNGtkZDM2eWZEVGMKHNM++WTZir7pfkXLo343vhW4oN9hr6pM
        9ph4lQnmX3ArVSOuq466nLBJYaFkDvCk7VhM/H7kW6wrf85ZxazX8g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T13:27:25Z"
  mac: ENC[AES256_GCM,data:/ZIS+UuexiYTr2DbaRL+EeMqVBak53iSAQoaYa9gukdu8L3INHNy9SZKW+KGC7PlB2jtpk2RKwvniuuZVlhcwkHsRDI74L68DEaHRlMF/3Xu13njZEIJ5VqREnLWMV34JX/PGW7XdbqWNghgf44Ql/e4ISQC3KFRbaAFAsgiv7E=,iv:lTiGA7/sd2UXb2Z4QMzfnWBk/srKUG1+guiAOQBr7bQ=,tag:eTz/qwKkhpdgGXk3+K7h5w==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
