apiVersion: v1
kind: Secret
metadata:
  name: democratic-csi-driver-config
stringData:
  driver-config-file.yaml: ENC[AES256_GCM,data:PR2pyXRhV9WymnQd+yf51420qeJ90G8TJGArwINlbIbvopmf2HX0q1dEt4llPis8borAxOhnYtk5/zlMUjjGEH1lllX4LaBAYNeR5Kz5YcqHidiu5UTACBZiR127crWnaXqWerxo0lHSGXoxB4+H48M0hYep5jxNnNQZT3rWUCWD/YBACIPAz1we8THEN65lnUJ/4Z0uObx7XldX5fSOcNGCizrtU4z9MUlOssfSKuOcECm2iy8rG/BwjoOs420rzAtEwghgWlPBc1AA09xmfIEWHXqB1WFCtYZByXgC4NhAIv8R5pc2BFultsXGivCkelzvDG//tn5PmprxHkw8EmTJlNRlV3dJZ1uZj94OkQXfqKEY1e7b+aox42MswyFXQruLhS+2TkalfnTZX8MOfgKJ6uUyVCTcxt2dSWEQf0x5nefaStLgPvrSuInz0M9Z77LPV0WQWpQ6wAVl24LqKHtyqVBFDdGEcXC71giRFGR3XA8djOdIKtCFExP6rXiiBLnBphYobaXnpytsa6vH9yPDNSjE1XnzB0DsGAQ2PRlKb5H7tWH85EC3n/NHz0/+AqFoIcFPg0KgdDT2wKR9NXHOETdfoMRsQTZNAwYxIcfhv5qUrSShX8d+PUKzOQteFoGrPc6QbHlTGGIrw0q4P2T5mtAgF5zMfq+a35fM1lwXuiHXk5UBl0UkFtT1WLb0ekBptmNC9uPNk1ICHcAOHfO+Ihc6OGtJq+/nh+AB26G/3JSjc2cTL0THil+sLM3mT2z4nTjuDRDr+kjc3NBSvV44BhvgCaxy1L46e4SvX3H9KKGYRE/3Qo615gc98qAe0ebg18a03r8QaFhlnfYri3HXd9eoP3z+cWCIfURdZfFYPusVEVV0Vyi6mVhh/Drnk3dFFnMuXquJ7tNbPfDhSPzgxNRXgOFnjABerRtVUHf4mn2iBygHmHdEwc/BuMptjzgxW9tT7Fgj6ByrGwp7Z6ssyw3n2sliBs2sXTDn9h4DSCoK0FINPYNvPQhjcLEbpfc2H83lhP/3Zig29UEvp8/ypIokqRvLWGLvvMQa8ZfYpn3jegH8z3Ktbd0JbXE4lbevtayXDGC1I6UIKeXuKhmav9drrVA9Up58mUObQWBJY1vSZ/IXCCRn,iv:vTQ+o0SY9EVeaSjDtJgzhpk3lmkO0xgYOx817KCYyjA=,tag:N0YU/9qLIQsG3lPFkhwHKA==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0K2lncEt5V2g3YTF6V3VS
        VER1UHpMbksrL0gzRk9JMlJhaEMxeHZOS3c4ClB1N1BLeXArajQ2RnFGRXBQN2lK
        bE9DVERzeG5QMVYzZVdtYjJSKzVyYm8KLS0tIG1HK1RXbDdGWjhLT3JvNVVVSFU1
        K1AwV2pJeEZyc3RlTTNLb3F6Zmpndk0KPoeQpoYg0Lb3CHHrPDRz2/09RBSZ+LMN
        a8MxlcC/Zk7VBVygf0lIp1/wPblIcqgC4v/03SOTaftS44CF1FKiDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T12:20:43Z"
  mac: ENC[AES256_GCM,data:jyGc3pA7fCnXy0r206st8UFw8u6+2bqbdSSHyhNDYPAVrjsvEcdP0EQS9e1YJ0jsW1io4+a9wwezyGk2ZBO+w6QXGlxme7XB5Cw2jlTKOChim5Dq1x3tR0RwLM0jDpwItq44rGXEUM0zCBjzDQIUr6z+xQj0ljiKDjwvcUoMrHc=,iv:nxigKq3MZh0FkaYRDPdap715CNDi9cZULgRaApHaKRM=,tag:RZbQoGw1Jl+SgHxZ5SUc8g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
