apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-gluetun-volsync-secret
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:FJ0OzK/TxgNonGZOXkZWJGN9F0FEDJxNt44XtNT1xujuX6LmL5df8BPlfg==,iv:Nj+er1GXxiT4Ok43MIjsUWT5s0w6kN37FvLshnALg0U=,tag:TVWwgUShBUYO7HGG6uwB6w==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:YwxF6C06fYY3+BnqErzQHhfrar/RGckKhbV37w==,iv:DCVgzizHN/GZgpVoT92A/6O5BSVWxzyResQxHfQQOjs=,tag:Lpy+ZyNmugIR3IgEvqOrdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDb0ZDOHpPdDV2cjVHSnJW
            dG93VVZhYzRodFlPTUxwNFNSK211T1NGWFNFCjVNRW5oYlNhOFZqamR5ai83VWxC
            Q2dtZWZNTkNreGpVaHgzUEd4T0RYOTQKLS0tIG1Hc1pkcWJFaGdtcHF0SVBNdjdX
            YkNMdU8vUkJ4MWdpS0FnQjFEYlg2cW8KLkpS5YwTTJh8mDX3yZsrH+WWFo2BWAlV
            kMQf2gJOnAqBli+yiaaQMhESmvm2PLYwfZ1DJQRDd+e6DItHdTbIqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-10T17:52:42Z"
    mac: ENC[AES256_GCM,data:yb0W8Mi09Hr0k/7sZXCUYXh3sOhQ9qpdG/Dz/TT9hUAqMiPIOZ1P0B0BYl+lJzV0pKi0aD0Swi7pJ+urjIwfQ7wae1HkeaKYNareR2EQODIQIsEdR0qb89V7lMjQWey+SPL2vqYIKGooa3qvsfDpV+YfrSNvnQv2axoqIgHi8M0=,iv:TlPsOewhZHaaRWPHp521cWfxAGlhU7ky3XfjV0lTeiU=,tag:MCSRohHjyKZIEbtFbBlB5g==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
