apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
type: Opaque
stringData:
  PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:v8WyTDZmj5p9d09Rj+BSA/2mpmD39/vnqdijulwpNgQ=,iv:oXmjZ4iUyNpc1KEp36sV8R8vS2xAcyWY2bGRDYJHDZk=,tag:LEIAPiITbwQCHA9NrVbuzw==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eWh5OFo1TFVkS2FRMjMv
        U051ZDNsTlFrZDBWSzUwL0MxVUV2Yi9mY2xzCjFIenFFd292akszaElueHJ6RldU
        aHYyeGxkZjZ5UTJkMnVIaGpIY0dneWcKLS0tIGZKS1lvaVh5ZWFseXlUTjFaallL
        aGRMSWx1eHhleHp2am0rTTVYN016ajAKsAgrEN2kyVlPeiO7q2Q0p/CHSijNff3x
        s/2KYjh7+DrUsNUBF2fdZ/UIek2U4bWZ29J2tGIv1i/i7vmT/cfw5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:CVp0aV/2jSrAwUsgaPk+EAwyyQui6y9VO+imdiW3960iYLMzx5Sb4V/5OaNZf3j7usW+XqzI9+7MXuUNJttARM24VzjK0P5voMwNoZUzaKShEnMYtAbF93vRN29HxtVRA5CrJQeNV3TPDCln4S+di0inbWYPt+A0mMXnPJJGjEs=,iv:5UZDCwXPlRkrq8SOUMdmyRjds35JpS+bad1BEEoNfF4=,tag:ArLnk2xeb/LvmA47Wt7FVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
