apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:GiJZx9v4B5qsvkejM+qZckh4+obuKJTNpkqryUpq2/Sd8wl9k8WYNJmCVw==,iv:KODbExI6FJHowtbIsN8WpXlNmFeqtiT6qs4UxEARXTk=,tag:dehdDJLXH1E19sFU5i7VvQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:89EojJpUXtOv8unfN829IYqXZixym6dLgd4smA==,iv:CvcnJYX4KqzK3idcCUb097zDjQ3jbxFjTndqUb8eIm8=,tag:4ipormkra/pXPnGQcMXG2w==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVHYyZmVHdi9FeGtqK0dy
        N015WEYvOG5vYUtzQ2UxN0UxWWF2VWNqNEdVCjFuMHA5VkJ3TlpyYXJRYjdsZzcy
        dTZEbUhsaGM3TWx6MEFDcVVXSFNPRUUKLS0tIElzbkJEdEdycXlPWmZVcENGTmd6
        ZHJnMmRneFQvZTZMU0hnVEp3cVFFVTAKH+kLZkY3FG0NM7G8od083qIp6zW5hvmP
        2HV+NHOXacKjTYNPxUGuB5uxegu0KtRX5ZiCI6FdkioyY0m9f92hKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T22:12:30Z"
  mac: ENC[AES256_GCM,data:PDsj9cBmXZUqPVxCIgJY19f4KcvENTsswJrXf9i42perhw/0amc9YpXzyCDHY+TTY/mfW4UKSMlh+9gRAAJbQVxKGExTgHfSmCL0upvQQQTWpycIYXFJspUg1Wx7k0uOP0w36vlZ332a+7HuBS1iymE/2lhMYlROkzBEzZ4/JDs=,iv:QZPaZm2bv2LsuQAYXRq3qlMzsZ/kpKjdG209z7PmTe0=,tag:1R59jH3DHxigc04+NurrRQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
