apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:PvQYe8R0LiV76+ex1urnLugnzqCkmr8v3iD/n7q1XGw8+IhI9BrKdF+RHKF9gf710IhURGcTPuea1YMKRka0XA==,iv:bTPTPW3kyRtFh3Rsk8ZW5L8tLf298jJSlTER3omTPIs=,tag:MI5vIiyrAPRlQ4ivAYA/xw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:zwTv/J/GQ6k=,iv:7hn5hLPwcbz2ij7lYSSeMUuL8/eTYNwvmV1fmj8MSQQ=,tag:XPN/Z+m2ILB1T/8eXoTFzw==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOXBieFh3aWQyQjlLUmRV
        eUlRTmJ3V1BhTldNcWJDby9yMTVMU0hXUXpjCjJndEFKYUVGcmY1Y1paWGs3UzBu
        Ky9rR1NGbDRVZGQxTVQ1UkRqTkdJOUUKLS0tIDVhdXU3cWJjQTNoV2RzZkNGdHJG
        WnV1WXVNQ3VGM0wvQlg1ME50SXJrakUK3O7p+rZjJEAZs1b26jXN0xfRWyEibR+L
        s0bz+YxMqiuhLaHLMwNlVJInXEmYdnZpkjkYl2dXJSehd8xjaHf5jQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:Rpfu2PDluw+SCYAzvZwzEwcPvKnKQ0MY9Zxz8TBrKQ86HaNMEt/k+y8r8D507xjAsZTsW398TGUH1YGIfCDHv8xxzgQO9h36unQRVhji8D8KcS6KpklR4woMFMQ+Cqfne5nxP4Pw6KfEVyq8kfyTZJGuvcASUfzBXQGYdi/hSzo=,iv:cpSpZ0kmDUASu4HrBWCFRhC3kOXZz5CzMmFCm80zgW0=,tag:ZrcFKUpR2bstcDbrpz6Fzw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
