apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:EKYTHpZ+tWT2xDkJCCyL+ai0DGToaPBkEBURtRYbDsjpbbzqi58P/9ux7SMav0dkjx1bzbQL13+ucrF+u4bKKJR+yzK565+FpS+PtCJbM0o1xC8UH5MWgMAVn4tLIjujeMkVb3oXOo9MoXdLjleMv5Y/5SycGl1Lj8GdX6lF/iF+ylvtBpfSP1bDfTmdx8/blNGjT+IYhCJAi9EhZ97jcriTeA2uFOh4wUUKe8X5UIOVf7Wt,iv:LqSWC/L2pvTd2w/7aDOJ/KYRi7KkgTqqIk1NpUgavKM=,tag:MLwjZtTvAycVdxj+sDWbNQ==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWGVqWWVwdjVxSkJJSjd0
        TFY4RkVBbk1ucU9YdGpjNStPYTJOL3dVWldnCjAwSlF3QStsYktVM0xiemU1WkZQ
        TTJMQkFGMVd5bmdGVzZzdGtSSWZkWWcKLS0tIGp0VTIxK0J6UFRyNzBUL1ZkSFFW
        RkJndG5HTFd6Tlg5Y1BLVEV5K2NRdG8KqXOJW0h6WMRuARl/x2y+5wRl9zw8Fxev
        kgK2QSh8EeASyV3Qq1ZZgv3z7rZQj1gSwmsBP5GvnyufEbRjar0w6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T21:22:05Z"
  mac: ENC[AES256_GCM,data:JDrQLe/WrZ+nCd+pmFujTwEHK3fDLC82uNtHZSTfxTjmpGzrd+7dVTNlRinxNa1GR1UGD38z4H4cQ6dBYGsZxUyAhbYdQCB++R1uFa24rre8yPQIfuC/NxPC3u8H+GoyXTkx10LecWiuNgBxSEV92OO9v1vnilwO0i0X3U9C6K8=,iv:D+HlGa71FYO6lvkoIzq/ovU4M272EKF9X67ps37v/c8=,tag:nm739VXenBHmriwytxRYXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
