apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:jBgv+3zT6hbsdkrfUhT3RFbGmjAFqRISsIwMavEizVtKrQy7lu3h8VIuQZSOxFpdGbrV9D6nw2SwK43pip29PqBgyur1JAw8KiprQNi0kQ8lykuKD5JYDAarMTgRNOdOElf1R7g5v0RXhE7qlqUedvU9KFrPLRvKFJVBaubI3mcFcjuMHpDBy4WUX5X3ni6NpF3ZlmenXPAns2SaGYO+qSV+Hbio7sQlvRGRAw2v4oYVFPUS,iv:e6Ey1h1x7g3QMGrJ06bm73PBMFtfugjPfTO2I4w2SDY=,tag:kUypc3nZbDr3z84+rZTo+Q==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOHZYSGNwWVZOell5MUEx
        RHRYVWZBcTBGREp4M2JVRDBLY3pvVTBMQ2s4CjV0aDJKeHY3NWd5am5oNmpqNmYy
        UVlhRHN6SmVpalRMaGxBOUQrVzNpZGMKLS0tIG1WdTQ0MXZvbnBwNk1vT0RtMGdV
        bldOUitTSURvZ1VkdzVja2p0N1pjTEEKlKMo49xMEz7jxv5obHogijDz6mUYF9nF
        uzLQuz65XNUJ0GiFqTYRkcw8ZZorc87XU5BeTmA0DSybTgZ7lGGuHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T20:15:27Z"
  mac: ENC[AES256_GCM,data:FRbppLHPvbqkUoXW/rGdTUl6M25QocBYgge+J8HHA46JQbuL7mNIvux7DVDPbH0yI8zqvPFBhtWPjMub/KHWcRZ5cKSxtltYA6UHhCOYTFZok72hX2hrm2NqstwAs0ttgdNxNUIwNSHiyHQFzxyICCEwm1bdFW32m4T6Y4tsL48=,iv:QpTgwOa3wuaoXel4JJ7ZU74Tu/zf3JI/UyIhQsEIN5Q=,tag:EEOaYlLH3JAyiUEECNsWtw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
