apiVersion: v1
kind: Secret
metadata:
  name: unpoller-secret
stringData:
  UP_UNIFI_DEFAULT_API_KEY: ENC[AES256_GCM,data:AqjZHxr0snRxrMBmd2FmkwJxQd7zKEKKCfzdlp3t4Eo=,iv:3l28rtKQ9fN9SAstsvIjU7h26HlNDWJqaPf8Hm/+PkM=,tag:TVqwU6+yDz+QPBoYUWjQbg==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTGdNNkhET1JVQ1EwZlZJ
        TUJidGZ1U0ZJRTd0WjNwblRqQXF4QWZ1OGtnCnVHanRYMkYwR3dqaTNTWDY5eXEv
        WnpWWUd6ZXNTdDJ2Uzg0cytDUlRnUUkKLS0tIHJEZ0p0ZURWaWNwYU5DWTQwTWtj
        Q2lUam04VEIrUVhCV1MybCtiNUNIVHcKVupmlj1i/TQ/sBqbq0x2ryVVNb/b5sjE
        OQYPzMWmMB4rXdk95WoUgjw3UE2v0g1LTmKqsrRxoQmtpI+BCnkDbw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T14:54:55Z"
  mac: ENC[AES256_GCM,data:szsAFy6NllOoaFpa69gvan8BpQ6LEJ5Hj0yyYMpbNzCDLCyIpC1sqE24js9fzM30ge6GfJ9fvjnc1ywH11pw8e0U+f/55D8axTjkDZGT1UnyquRPG892zDmwXnMkUIY9VvcIF9AvrLQ7GLRuOz4YydbtC983kXcLvkvnylWXdb0=,iv:k+kkBJCTXMuUK0oydDKOlzNcY406VZhdr8spmpfzE3I=,tag:lJW7cfJGSL7rMNbJT87ASQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
