---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zeroclaw
spec:
  dependsOn:
    - name: ollama-proxy
      namespace: default
    - name: volsync
      namespace: volsync-system
  interval: 1h
  path: ./kubernetes/apps/zeroclaw/zeroclaw/app
  postBuild:
    substitute:
      APP: zeroclaw
      VOLSYNC_CAPACITY: "5Gi"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: zeroclaw
  wait: false
