---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/volsync
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./pvc.yaml
  - ./persona-secret.sops.yaml
  - ./secret.sops.yaml
  - ./oidc-secret.sops.yaml
  - ./volsync-secret.sops.yaml
  - ./ciliumnetworkpolicy.yaml
  - ./securitypolicy.yaml
