apiVersion: v1
kind: Secret
metadata:
  name: zeroclaw-oidc-secret
stringData:
  client-secret: ENC[AES256_GCM,data:ZjsP8QimR7FNjycPG2XqRBkQYmwJTA4oGFv9iw8l5r8=,iv:TrX9oKwv/F5PjaPycSVJ3JrMRH+pcEsEWA8FLmrrVeQ=,tag:3RIaWxCAIUuK0AhHdyuV/Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmd2tJRmYrRlJ3TWQwaU5S
        WFUrNGJoQW5PWm9vVDhFRlNpaFFRRXV2bTFRCkZ0L20yRnZDUXFZZlhtMEF0RDI1
        UmQ0Vkx3QnhsUTVVSEd6dWRLUUU4UWMKLS0tIEZHaEQrN1FzN0FhSk9VMXFqVkdv
        NFRwYTlKd2dZQko1VEI0R29iTGpNQzgKuB3285O7t+f0IwiDEOuHviwk6HO8OTJz
        uDnnWwPx0QxmvAY1pq5G/5BbKSmxZfPLOw7RBiBT28VTTeuaOup1nA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-09T20:23:16Z"
  mac: ENC[AES256_GCM,data:wwW2r0ZFAuJz8PuSZLtfTklIty4eVhRLe9Agz67Jrw0ivCxIUxHQaS8KhvAjOOQ7XH1e0hCq5/r0rsqaTTYU0A+jWrPSzyoUipXZfOVpz1NaxSXSD8XvTCnTVo6fxtepDWQyTQZQKPeEf1o1kb6nRoIAg3Kc1NL1ozgdo4KA7Cg=,iv:6umkRBR/WQ3tlUQV4babLw3kTINJ5pR2i4nph6ZrJAM=,tag:9BTPaTzwjil6MLNtp3eTjA==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
