apiVersion: v1
kind: Secret
metadata:
  name: zeroclaw-secret
stringData:
  DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:NkCoqzIBxjdgqyNVK2lLvXa/G8+pu7bPSfFyWlRDXXMYR5DK9kLbT2yDdIhsbyO24ExExHNbXcUhiraYfRjGBzswiS/tBRf9,iv:Ym2DQaCZXwEhaS00QQr4x9zyQQfteRDxM05TMJ8FiOY=,tag:0f4nw9ShgP/UNxo3IoxKaw==,type:str]
  DISCORD_ALLOWED_USERS: ENC[AES256_GCM,data:j+gPHKLj1g==,iv:6TYDSrSfhAoqG3IkFUmAq9nmM0SizKsiPXEVC0Fub8Q=,tag:m594pLHrrJUJLnbGRJQS1Q==,type:str]
  SIGNAL_PHONE_NUMBER: ENC[AES256_GCM,data:wJ5+tZPaatrtB0g5,iv:nmz1GvJ3b+0VU1lH2FJSRfPKjZu6v4oWiKpzhcuGqOo=,tag:EpCOvt977jJgTv8HHZPAZQ==,type:str]
  ZEROCLAW_API_KEY: ENC[AES256_GCM,data:fnscSLL30NaxUNV2zQJejFh0Z9ukEpSHcoZEIKk4mk0MS8nPwZPsArxPdFu6WWZ2Pn3AGbmKNa0W8XEkt9WoDA==,iv:ZKPTukPqx6lQSSdMK09EWj0RlKzX6YZlcHwUeHgHYVk=,tag:bb/n6dEoRJMLIvhlN59CUg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6a1hXRjJLbmN1R25hNjR6
        Zk5YdFVjWE04aVgyTzRJTmRTTEpjOG5RV3pNCmg4TXY1VHptZE5DbmloSEIyUEdv
        bUNLQWpOb1d4S2J5YUFLekdDQ1lpek0KLS0tIFFSZHdUQXZsemJhQWVMYXR5cDJs
        UjBvTHJvdTdUdFVsYnQ0UkI3dDhxTXMKz0PDOBZAJNiXnB5N+GYxbWpuh+rdZ79b
        8jtV25Lp9yjhwZ2HnjqGU82JgU7PaWmLPggoZ/OaO3zf8eLgy3TGtg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-10T18:24:45Z"
  mac: ENC[AES256_GCM,data:30BakjOR483vm3Hkd/rN+7rmJLLVIrcKHX/zCaT0SuiZy54NCX9JaPEihYr5V+uJNry3QGNYOw3XpbGZ2D1YyJeDZwV873PjB/xVZRlb30F8uwb0PBiizsghVztEoGIZMdGtrKGChIXTEqezwe4Z2hcVwI+F9GwD083hAeHf9mY=,iv:hEHbD/qcB1fJZlDm+yTg8Fp84COReCe4OUCpS57aZJc=,tag:kT6kMHC7iRSNMgfqOd0rxw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
