apiVersion: v1
kind: Secret
metadata:
  name: zeroclaw-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:tODataHvF4tp/QjNCS6JIJcY3PHAb3EUfy56LvVlrHyXj2qqz3jAo3ZjRw==,iv:CvYmUI9wwcfiOmxnUxCRyM/kYcVQZYsQXqSYr3EHjro=,tag:Ko/6CFXe3pvRgTtonkvB2Q==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:MlzjAk5Rrvo4KpoHZl5B42z7xWHLh3rdGqV6Cg==,iv:QTLbrzxIqStWceCCbpwB78Z3bEBdbmBIgQTfKivk3cs=,tag:olkvNKw6imqr8WcdUKHTzQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRmdqb29kQWdBdHJaVDJM
        TkhsejJVUXBWVGJFUXJHS0tOcG5kVjlobHhBClRIc0NXTVZDNWdyUnV0RGpqRzFv
        d3h4aGEwYTFKMHJaT0N5U25mYmRWSlEKLS0tIFhRVHBURnRpRkE4SXc0V25TbHpK
        OUs5Y1JqSkhPMFdKdGtCSzZjeXNoMWcK4AvWuHDBE09ksqdpnsoKcF5fng916ju9
        0gxfOIfQC/yM2yysmKmUaf2mmTZgKybgRDULF1dg2oCgqIPFxmi5Ew==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-09T20:24:48Z"
  mac: ENC[AES256_GCM,data:+Zeoqgy0iXMuJU8E6dOtHyvxK4eez7xBo+oWO6hyYtznYrkMA/UMHd7njxiXY1Un/69HU7Nr3FAl4FTcx21zywL33OkexPhFVkvyDzIUPBBewXjTxjsbynDAXgNmQtsVzyZRmFJ6ZtGuWQD4aWUs7rg5mbmf18rFpXSNbfhsU30=,iv:qNsHQOsywf6aGAQYqcdrplLrGehWbeDa1GB8krk31bM=,tag:x3BFLn87WULnbjjopwS6Lw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
