apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
type: Opaque
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:wi8eVESmVrAZgG6jwbYAu+w0aOCeJxfEW9iV+f723F0=,iv:VUdAHr6srhTiP+qUbZ2PnfKaTT+uUyaBbFecBhHEk2w=,tag:5b88AoOI5+D4TwGmeyU5jA==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYR2ZNaUFJTVlpMmNURFJ1
        dEZyaWhtU2FnQUdTQUVHNXluMyszRWQrcDNZCnRIYlVkYjE2TWNCTENLQjkwWkF2
        UER2SGwzUlI5QzZTU01paFFEMkxlVzAKLS0tIFVGakIzWWhMOXR3ci9pNTlCSWla
        eXdDT283T0o5Zk40ZTE3MWQzdXNwRVUKUB4bqCX7yRzHN467/yWKI3WA74lnQRcX
        LKB8XdeWIbuFyID61QzHZhvet2ULnQDzouE5nyjPw4crXmPz0j3uiA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:yQAjny5PHg4FlsIbwRi9iXBef4PBnz+Jqg65rEmxd4qTg7n5FfNSQhmyGsuu2CSEFyfRgPOonCZ85TPKrAaTqpqyfh/yc1j8qZDbv7DmUJIOwZQ12lo2rgNPofIKtuqYCZAXnLGcETviUM6v7mj/akjLywqGZ7bO1kKgyn24H/k=,iv:VOwDk4FqVGH2FY5hx32AOnml9xqZ9ncOU/h6nCq3VFQ=,tag:tYRG+SyO5XnDQWv6z4qkhA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
