apiVersion: v1
kind: Secret
metadata:
  name: radarr-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:MgP/UMsZCWaVzGCYVN/uH2R9Wh8YOTjvGIQc47pHvpfStLsIuxzfg+HuoKYElGwvro/kA6urTHQG0iNkcGsGpQ==,iv:TE0ifg/1/33dhsPhI6KRMGz80cA8roxUpUBYRccXxQU=,tag:CzWY1fBfxA7eYiAt5urk8w==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:BM6wYoNK,iv:VBLj5hif0/NqrKbZ4+yQyZnIU91X/3FMXYHJUc656Jg=,tag:UjgrugYK3lo5/TVvnQoWRA==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTC9CamxWU0cwN1J6aXJ5
        enIzcUpmeGlxTk9hN1JiNHZUWVNscFZkTUJFClNOcGxUeitkZHZEaUwxQ3NrOTNM
        empvR0JoelVqME9oSWV2UDkzQm8reVEKLS0tIFNRMjd3aGYwemsxY0JWYW55ZG1k
        MnFtNkpGUGFiV1hPRG9yYUF6cXJIYlEKBNE7uG7zOSrLaJA8If5yDibl3r9+WMYV
        k3PlBTR0Ie/AsKeNT9vxQj5g9VtmOnAQ5xWAAVjBMU7/mTz2SWHE5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:b+GAD7buP4jzzj8LY6Rq4U2Ol/yJL64zfk40vwnePMDkganOYh+pYDJhJBszpj5mCkow8wGenGqzkQSmKf5zLaXbE+dmxXNeiFLdGUBKDvr1LtgJkwdvA++6JLcQZkfkrXixairXvjzTYch2lHMXBfaxwESQYpO7TLlnS9Uv04k=,iv:+JoqqZsDVpQtk6FaBsoDPj2gppybfaHWVoQyxh2y5OI=,tag:uk4KtR2xtiItt6uCPCqABg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
