apiVersion: v1
kind: Secret
metadata:
  name: radarr-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:CC8sT6Q8a5VC8RKRbGCIcewpSv312r1XPLMOaCEbTWGbqzn3wdpjIvvlVg==,iv:gQlBH7zeJ9GdShxULmYa+Atsf9J+c4p3PbsTZg84rIs=,tag:MXkh+b1vrMvirAVBUCTSIw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:9c82KUuMWNh3D4SFt4yZd86ISg86+lQFPLC1sQ==,iv:nMTtWOEzakcxZcSSbNZRM0yAIcLT7bC9TQZM6e36LBc=,tag:meH9ET8GzMi8/f/20pNuow==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MmJjTHNTQlpNdWNpR2RU
        OVpkbFcxSEphY0ZsRVdEckxnUk0zTThDR0gwCkhTYksxdDgrdVNmZlhDZkhIN05l
        Q2JMelhId0JkVkt1MEJWWm9ERWNiV00KLS0tIFJTTm1uK0dkYjFYNWpkbmNIS3dU
        OC9OQlF0cHpscG1LMnpMVnpOR2FMMUkKdwRU2uIGbEL7jV9sv3gX1TDoiodrwe/d
        UBKD2eQpXL1jD1zHtrSz1z+RePP0wkl3dZQ/Hj9X+nTBNHRVJ4Gazw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T22:12:30Z"
  mac: ENC[AES256_GCM,data:leK7tBLi5TmbQWP8GZMvdDYSE1Ruy/ENIYJF3bll2qR2/xXj8ZssAJ4clyNlIHXkNXsh8X26vw5zXhXI1FQrNsP9GWZAG8IxQOTtZ0lXydB/m7UbXsaSmaBXnenijLz0sr88PxWABYt2PV2gHYah9UUPhvApRzhD5gTPwIZ7k64=,iv:1u8RGCEwGZ6Dj1Jas79lI1VFSXie2AHMpOh2rx4t0go=,tag:VZJby2xBxhx88N+ceVnldA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
