b2_access_key_id: ENC[AES256_GCM,data:XP/DV3L6qsoR6fHL4HM8WU9tUgQ4DznYcw==,iv:EeI+MBHTQ47ocQ4gh352K1QZLrj/1D1fzABwBOdXD2w=,tag:tbgB+V34nKbggxzEfZP48Q==,type:str]
b2_secret_access_key: ENC[AES256_GCM,data:4NlZ9OP+cqI7rYX3LmFDQ//uF2g/CDa6JgepOfMJ2Q==,iv:s1Qa5WRawamL3k3XEhluHQnKd5RN3taK6bp60JGerG8=,tag:IYTBXFEmNBlBbC1i33yAHg==,type:str]
sops:
    age:
        - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaTFvc1VGdHlWRzJoSFVl
            L01jMEFETWVIaEk4ZzU4UFFMRjdNV2JCdFVvCnMzais4RXZndVBxRVI1SGpjSkZG
            VCtMbktOQzZhcENXa3RwaWFUZUQ5RHMKLS0tIFVTQ1YxUktmMG9xakhhN2RUWnpi
            VituOVlFUDdGbjBTdldnM2dzTW1vODAKFK7sCAEF1pVYSiBdIidanVn0ktzfnI36
            D46KEHWz588KUCyi+SzI/uGjv0GsKfwJFWxghcMZRelCLO3GHF1fvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T14:04:38Z"
    mac: ENC[AES256_GCM,data:fmzfAwZLktXL3zrOYoBYaX3ZYr9ujX3KsSGhK9xqauUnezr7Gs4ly/Abo9r44yZSTi9UVQ4/1uHgrzAWmTNP9GbS4hCv++u9ETNvlpGI0UjN/Ak5tyz9qeXeuQvz1UZni36YaCxhWAQPNZs7qtZCCemSHFPf5woWUbNLpdRMpLw=,iv:Z/eqO3tHDb90ki3x7JlJJiY1WkQwtN+MMCFkGQihaOM=,tag:EAbXd3bTONR38bSAvjFZlA==,type:str]
    unencrypted_suffix: _unencrypted
    mac_only_encrypted: true
    version: 3.12.2
