---
# Backblaze B2 bucket configuration
b2_endpoint: https://s3.us-west-000.backblazeb2.com
b2_region: us-west-000

b2_buckets:
  - name: sp3nx0r-backups-workstation
    versioning: true
    noncurrent_version_expiration_days: 3
    abort_multipart_days: 7

  - name: sp3nx0r-backups-archive
    versioning: true
    noncurrent_version_expiration_days: 90
    abort_multipart_days: 7

  - name: sp3nx0r-backups-truenas-config
    versioning: true
    noncurrent_version_expiration_days: 90
    abort_multipart_days: 7

  - name: sp3nx0r-homelab
    versioning: true
    noncurrent_version_expiration_days: 30
    abort_multipart_days: 7

  - name: sp3nx0r-homelab-kopia
    versioning: true
    noncurrent_version_expiration_days: 1
    abort_multipart_days: 7

  - name: sp3nx0r-media
    versioning: true
    noncurrent_version_expiration_days: 1
    abort_multipart_days: 7
