---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: warrior
spec:
  chartRef:
    kind: OCIRepository
    name: warrior
  interval: 1h
  values:
    controllers:
      warrior:
        containers:
          app:
            image:
              repository: atdr.meo.ws/archiveteam/warrior-dockerfile
              tag: latest
              pullPolicy: Always
            env:
              DOWNLOADER: securimancer
              SELECTED_PROJECT: auto
              CONCURRENT_ITEMS: "3"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8001
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 50m
                memory: 512Mi
                ephemeral-storage: 1Gi
              limits:
                memory: 2Gi
                ephemeral-storage: 60Gi
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
