apiVersion: v1
kind: Secret
metadata:
  name: warrior-secret
stringData:
  HTTP_PASSWORD: ENC[AES256_GCM,data:KPKU6Rw/QfYoBAEUyX6Reg==,iv:Q2JYTTptx5Z9bVQaPVkiB/T+JUvAyLjMS8UcvsQcHoE=,tag:7ON2OupXgVnZCnRI+TbD6g==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYUk3TDJnMVVPcmFwVGgx
        S3I4bmtsaHRFb2krTC9WdUpCQmVtR2lPRkJFCm01TmJ2MDFndmVDdll3c2tVaWZv
        UVhqRWdRK3FwbWErQnpBWGVQMGs3a2sKLS0tIERQaVVYamZrL0xqVHFqK2JoZmI2
        MTB6MjkvNTRqZ1o1WFB0RGJkWnJFV2MKT9ndms7CTj7Ef2gbYdoKTadytrXVz/B9
        dTmh790ok7tKsclqqiSFhTym7bHk94fMq6D5OM33hTILgSbVpCFRUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-04T21:49:26Z"
  mac: ENC[AES256_GCM,data:B4j5OSTjyFPHAwA5a70kz9PJFLW9IchNsFoOc0wXGJiff3nbI6zgKjDC2eCsDhm1vdUYkCVRbxw4wSyqfNIyKM4e7SRBU65t0Rk5Z9QuLH1at0hk+Hdkr6XR2j8/ad/U/PHb5JY1dtR3ywmAmWNl19SvxaSES7WMxsVQBsO5UP8=,iv:hG49mH9IiFowsruM//ZYXroCk4cdYxKVGhU82aKPHT8=,tag:/aHOV9ZgcL9+PBQiSjV4ig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
