apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:8iYNZjVvX7QFLCpuPYWWtSaqrPUtT8uw2wWBEv3desU=,iv:Vzl0bvYeNUI4FA0dBsOOJQJa8YHzcZB09yXiCi2HD/0=,tag:8ckn7q9NepcgRJZCdg2ihA==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WmVPazM0MlVYRWVPeCtw
        eU9IbWszT21IZDlkQTBOVXBwV1FTa0hqVFdrCnVPUm8zbmt1RXNEamppUUhvTHVs
        enErUllhSkxuM0g5OGJ4d1Rsd3ZVSDgKLS0tIFF4L01ld3QwMHl1WmZyRzlJc25j
        MTk5c3BFZHBkMXRNOUx5WnlHYXc1RWMKXvp5F+qe1tMCS/Ng0DYuTncidflDGQrY
        gHc0zsPZ0PB6C+yIAcbHz7C0f5HP7ASxgxfPx+jY8xu4Qxfwt77d+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T18:27:38Z"
  mac: ENC[AES256_GCM,data:CYhUGHXoPS6s+yU46csVCMmg83rg2yzqRIX5P1UkJvYbpnzIh2Zo+Gzc5McdTZB1C8CO11kZJ8CMevcd0dS46RDv1Uh3HviF/hpmIx2xLzeXZda6ZfIHchno/ze3Tr06W8XGaMH0gkhCjZ/rW/5baX7HETEdiQEJ0SqwcNSTnhU=,iv:aSgSqN/cqfbvcu9cX9yOcmkorB3xQncMUszHPMyhBGU=,tag:vwpz56/OFpvIexIGG7YbyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
