apiVersion: v1
kind: Secret
metadata:
  name: bazarr-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:OP6x+S3pwuP2JhaXk7k/j1KCwfS/YeyLc0+aP4dlW57eSlbl8jAK8KSdYQ==,iv:9iWmDypZEJTBaGWjhdSWVdTyY5pQyJRwx1bz2vtG57Y=,tag:i04FlomK4mZtYo+kQRrJMw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:AuVd6N0AoC2A4t99f7xm/2ntAPdC9gXAZB8Lhg==,iv:1cV8fw2dCSZX58RS0b79MB/nbG2YQZThRoW21ODHTyM=,tag:azRGND4waj4fvtULG/lG6Q==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUlZzKzV2MkdJNEpOaEdJ
        SXJVY1lIMWpzWnpQZVlzU01sdG51MUlpSUJrCklmWk5KZTJlTFZ1UWlxcC9SUll6
        cm9SdU5ndnhDbkZTbStNb0YyNkhzdTAKLS0tIDkzVmVFeDJON3REUFVJbW9QRFVo
        MGEySmtnOXhqTFhCUHpqWDZsZDlSRWsKs6cFAXdpbuhfwWBY9GTx9S8iyxJWOr0E
        9zNZkZbnTaEqJSCWBhuHUglySQejXR1ITyJenHEs+zpeOw/RNoze9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T22:12:30Z"
  mac: ENC[AES256_GCM,data:GjahLDU2UMxy1BWrOLZoJr53dcfZLnP90ExX3cl90CA7Zir0BsoiEz0ooM1qIhrPgYV83McAj+6qjp8OxpzxmR7HgdN35NJ2ixzhkE4MRG9g+2PT1MXszx9iQmiMfwnRgwC6IxeM3VXefUsb60CNOV/4rMXI8mbOc2oBW3F5bGI=,iv:1rfG5cP3wbLY1s39D37Vc/A6W5RLyNlL/lz6UWUrqys=,tag:GXwGjqduI25U+CMLDPo6dA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
