apiVersion: v1
kind: Secret
metadata:
  name: bazarr-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:TlizV3EhyAXxvMhDt6TShllDEYFnWolHRslcwP2v9zSCXmz1Aq3mHale1ufc7keJVG4K6aEEaqhpE22wtnGrBA==,iv:bqjfll6aWIv940rn8rf2BbXZTVNe8w8aeMLfKddFwzw=,tag:IKSjdUiYcAgVn1JXtkiCVg==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:EykYI7To,iv:OMS6h5vA1m+ew3+2RTo6I06q95iTF/1lCJDydl8jmhI=,tag:xL8G1nQuWulglcMYDaZRjQ==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTUx5OFYyQ0dVbGdLM3Nu
        UkZ5OTdneGZ2cFFzM3FpWjhlUFI0bWlNQm04ClFFeVN6Tk9TZ2FDb0ZrRmkrY0lu
        V1M3eWh0VElNcVBsZUZzcTgvQ0Q5Rk0KLS0tIHFMT2JZM2VuMkpYZGtFYUpwSCti
        bit3YUlKREMzMSt4SXphNU9YL2Rab1EK4DDzebqy8lZtic+k/E/K5OYjmIqpD9tF
        hKWlUGwEAb/0l7k6XxhjlgcLDK4XPos10a81EKery8hYPuC/9GI+Jw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:MRZb/lxncEOozLLCLk6k6VrhKMtzMGxaEl3iw4/SMsaG8hmhcM2MVEpy8znlPMOihVU+O1uFZTMlVUhn5SAjyvItWLpY993LiOyuaJL93zHyqf7oaoNnmA+M93Zx1ixdt3fJLvBy7dQUoBooYVsRy3sSAjA2PBmAdTE4FYm+6mY=,iv:winylGasFqCNaewHCeVjDPZNHrmzgXKU6LDcYX70JoA=,tag:Kv8hXW6q5YSQiHTzHbRA9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
