apiVersion: v1
kind: Secret
metadata:
  name: qui-oidc-secret
stringData:
  client-secret: ENC[AES256_GCM,data:8gSTR593f47DKoALbvKp4Rw8Aehy6ioevThb+R502e4=,iv:ICNLv1a8iI0lh7kmvzoduL3M9CRdnl1asLpsydcBZpE=,tag:SI/MYYt275+i0p5Rh+HX6A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1U1grdml1c3VyZDBva0dG
        dFR0N1FMS0JkTFNVNzBoZ1N3R3kwUTd4S1YwClpzZkpmcUE4SVBKTzZNU054NGwx
        OTIxSGZyZFBRZHF3SFMzWC9nWkZQWXcKLS0tIGdScWNZTGFnQXp1WjZRK0ZTWjFY
        M2h0QnMwaFBXTm5naEJsY05YdjFIZTgKU/V+UEYR7tMkP2ika9FamHUatNvr6jC9
        hHNHQhF3aORwsSy1Jn1hP28UK8SSG2scCg/bTJLnUhJNamOx7Owpjg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-17T13:55:04Z"
  mac: ENC[AES256_GCM,data:65R2m2wnD5PIsXD1AS3SEoMjdgz1W6KX1h2Agi4/I1X1FlS25p5fTUESNaLncrl9JySyS7LSxxkXxGnUWYKJxmz9JuMrbUE+ocsaV0Ee1DQtiUHkMjflAz76Owk47Zn9SCL3FmLuH9mNQgvmHBte+LfvJgaU/42tmUrbZFzQoPk=,iv:8Z/vvAn1JUhj8wSks9sfAsi8sC/LIdd6dO6xaJAco0E=,tag:5uq81nqub3ItxvVWuKMeIQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
