apiVersion: v1
kind: Secret
metadata:
  name: qui-secret
type: Opaque
stringData:
  QUI__SESSION_SECRET: ENC[AES256_GCM,data:05ocl/cwcP3+/R/HJVQ1ru/TA3J9/z4GSy6CL06giXkibMUJ+a2EDRcP2H3KgHPpCkN/RMB3rxVqEPrxH4jeqA==,iv:gLOT9kam7F4j+ikVVioEwtJdI0dG/b0gkRbHbUPZwiw=,tag:W5dHcWAcLWNhNj9GPFVjNA==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5L3BFdThsK1A0YmdFVDB4
        RHN1NTdVc3EyR1ZsSmVBUmpVMG5xam5nN3owCmdxSHFKNUw0eC9aT29RbmlpU2NQ
        SkdETmZHTDJid2YrUjRlS1pSdldlTGcKLS0tIE5CcXdvYjZ5ek81QWt5b3FvTDRm
        RWx5T1pNajJwZ0sycUNXdFI5SVVVdVUKS1+3KteRDNNLp2ojaDT3Es1Zujw92gKN
        9aKRwKfw+2giESGRf0YJcureMnoXxqi+kcspN5OZih75ejAYnz6nDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:zEk0f/cbZbyhRotJuVo6jTK84+PMBH9XZrOVlr9qKhpMencyTyj0DU/n2x4oMYfArCSdWvyDVmCmvcZQLrfS9pxmGn/bKYtk7Dpr/zwJSvDLKq+VIT1iGS1IBAagrSas/31GPEdB2mR8+zlKkdcHy2YIdF+uFeWpOrSse/3PxLs=,iv:OMgRUbMKZ6n+ohGeECbmizBGqLYJKDJn2o2aSw5xdKQ=,tag:1cShG2MNVD//6BSGlZ40kw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
