apiVersion: v1
kind: Secret
metadata:
  name: qui-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:wB+uTeOEf5JS74GH/ICztWyaV6Hi6A+MWn3XUFH4XdPKuz23g5oxAlfO5P9dIirUjgSQHc0ikFQQgvZYgQImaA==,iv:6uuoj6K4L2wv1w8UTh4Os8Rm/psjE0hON5gXzJr5tKM=,tag:Kj8WA2pokXH+MdPibDof2A==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:6I1m,iv:PD0+ECvuWgO2kN06XAYOlUh86O2KFX8Hl9AB/90FUMA=,tag:ZKsBioEStqsm5DpQdmd16w==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQWVqN250REhubzNLT1pr
        eWNQWDBGMzdpMXNycmZQclhRYm9qN1VaeWp3Ck52dHVVajFTcG5rb2JYWW82bUZO
        aHY5WlBvY1J4N0VReHRWSzBCcVEzRkkKLS0tIGh2WDI5SkYreU9nNDdBcVF1aDhk
        bUtaOXd5VlZFQzd0NkdIQlhDemdRbzAKUDDsCufltaOZrww2jPSVZJKYeZSgIeJp
        bwZN+mV+jIKMW0/iNpQrOIvKWKjm3/bo6PeTr07MBR0tpkhhhAO/fA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:GF3HKDueNNIHl6IOfDtXedqRIyuIqkVW6F0pNaq92NAyBDALHCpgPZ+cg/HtvhTNQghQMA/rSGm5lr8WD7mtkFu4vMfejo0lBK+ttSBHQrFnsdq88uiLb8SfWyrNeurs/pd1jt1yW3+TW0ACH8VXsDYf0krM+Ql5Okbe4nYD+QU=,iv:VwMs+Qg0cZzKcZgVqygEAonrHhJIA/qrs0LOKhJUrA0=,tag:qRwX9qag2JUP0fFY0bgphg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
