apiVersion: v1
kind: Secret
metadata:
  name: qui-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:u8LCh5/tDaTyxbt/YfZrXRisz0uiCZtPwB+I2taFofbgeBscOfTB5F29/w==,iv:J0oUVW6f25TGVAvILSapU/GWl3JgTpDjuz5no29Seug=,tag:TGMkJe9KlJL5N51MFzKWHA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:uh+ORW8+B3iibFax0y/f6sgHAN07CEdhfmxkJg==,iv:DZZlOxIX7CK2BGVxKe7Ja8sDeQDYirgXkGIEMWfpaz8=,tag:f8Ug6VC9moys8sze10bYog==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRC9iN2svc1NmdTMrdFI0
        bHdNcEVQSnkzN2VTaFo0MVZhREZJSTE0dkdNCnNtak95M2doNmg1a1FsNHA1S2J5
        RzF3bFZLeXRrRjdYVmZpRXp5Sy9lV28KLS0tIEp0SU5HOXFIZG9XK09Yang3WkRG
        UGdsRHNhQ2VGeTJSdXg1c1pZT1VtYWMKbM//ziMjubs4vTCTvcuu5SyLlAssRGMO
        TfbU6Vvxi1imQRMompQMEI9jYNOT3T8xOuHUfaFdfA3/2+H8BSFEpA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T22:12:30Z"
  mac: ENC[AES256_GCM,data:2KKYyCl7yU7qel2T/1UDH+4g1O7OTSAyh2bjtwiWcSDPbmlGMplGlUXQUBM6K5vtnD2x/ZZeM77+zVx9XEwAXZdfdZg6IbNh6P8hQtJvppLPsTlncrnjF3mIDUtWdXohASHDaWhGktnSDFBogajNj7zFSVtxkknFQl7ZJuPiU84=,iv:k9uYWOxdkr7DU8BeGgzK7Ww+uNaQwggwERUwY3CNYoI=,tag:xi1kbiOc/3SowNhS47RC2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
