apiVersion: v1
kind: Secret
metadata:
  name: thanos-oidc-secret
stringData:
  client-secret: ENC[AES256_GCM,data:N98ujzaw5YK/sDvwuYxxQehoLow9X9UnPMrilzZhoac19irk7KqTasFT0w==,iv:J86FRbGcfAbIODTZab9fpTXWaba/rzVmT/iCNeDifrc=,tag:AmO9xbC8hTBm9usErRGUyw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ei9PTGZiYjY1cm1udVhC
        MndZR3NvcWk1Uk5leHh4RmhReUtYck94eGljClZtLy8zb09wSUxmbXZGZ1ZxUWVn
        SU91dVBpbThJQk9EclJWOEg1WUYxaXcKLS0tIE5vVUZVbUhjU3VLNHp1SUVPYU16
        Uktkay9RS2pkMldKREhLMFdIS01DWVEKlSNIFxTSjKAxtGCh1xffGokdQKF1MNpc
        irru4bSCoQGocIZY692N6p6ZskbHJvITE6rjFJozoU9+b1SK0M8WMQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T17:11:16Z"
  mac: ENC[AES256_GCM,data:9e908up8NAWvKiJYDeG27imzHdUwT6ydgv1x7dq5CLruA4B/o4FHcXforuFzR9xcIuKFTR1z+0uL7TQImZMTtlfDzJealN9zud/NrnxyBOa/8RPgh5Wxcg/xWDpwpsLcNUUtv3XeJLC/dOoW/LewsD2v05WVh9B9GoSCuWBNfa8=,iv:B7CbqC6wEM28tL1x1oDBu6wWKcqg7v8aFvyeMwSahaI=,tag:3DvLhQyAlCQZtlKU3ehtsw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
