apiVersion: v1
kind: Secret
metadata:
  name: thanos-oidc-secret
stringData:
  client-secret: ENC[AES256_GCM,data:RvqS+WwSgBV7Eori5RcBxbCSRdxSd/QIqx898Sts4kA=,iv:zhWr5AzfqPPdqcS4mqr1K4Wk7GsOYkPYvCQucYHrNzs=,tag:N/glpjfXhoicuI4950YSMg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ei9PTGZiYjY1cm1udVhC
        MndZR3NvcWk1Uk5leHh4RmhReUtYck94eGljClZtLy8zb09wSUxmbXZGZ1ZxUWVn
        SU91dVBpbThJQk9EclJWOEg1WUYxaXcKLS0tIE5vVUZVbUhjU3VLNHp1SUVPYU16
        Uktkay9RS2pkMldKREhLMFdIS01DWVEKlSNIFxTSjKAxtGCh1xffGokdQKF1MNpc
        irru4bSCoQGocIZY692N6p6ZskbHJvITE6rjFJozoU9+b1SK0M8WMQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T19:02:20Z"
  mac: ENC[AES256_GCM,data:XhZR0vS4o0TpZrYgNu5mU/GGWAG1ixaa6AhMkbiFB7gZV759zJUF6yuz82NHHTRHl94Oe86mo60v7j6XF970sKkzaMxG4ADD9Qpc9sFcyN8vbfG4Qet9oHANYZz1R0VeKakFaFlA3LJCHlBN8kIEZM6905xfQinufSr0kx6GIo0=,iv:uIyJq1lpxbA+FK/sTArDSwr2zzhTHPCSsgbPY8PqlzU=,tag:jlxyesfQA2/xUmKNEhlPjA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
