apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:h7+j/vKxLF4XsC1oriRe4J8LsRLEuSydOFPR2ZPUpJ3gWmv7knsnDjbHt2vVmiTq6aIZV6g=,iv:FxJo+qsUD2dM7nfuK2Hw/EhqnHdKSm79rtiig8zUg7E=,tag:d8Vi4elg/+04wjx/2XblcA==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQU1HK0cwK2dJTEJkOWUr
        aW1PZnM1cU9HcTlWTVRycHJRWnJuVmUyVVhJCmlLWDNWR1pld0M4TE1BTnVQTzBO
        QThIQlFvMFBab3R5U0xWR2szSDE4Nk0KLS0tIHFLdjYrRXhQRVgwUGcvck5wbVFR
        dG9yYkE5MlA3aUhLb2RzL2owNk5PcmMKN21tN/Z4ug1tNeXfFSN3Qno+NbfVxQJz
        pgbArSynUS7x+9krWw87JDhNM5/l1VgmCNNHUR0FIPPoXbHTnz985g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T21:22:05Z"
  mac: ENC[AES256_GCM,data:tZkUoBcaEcZx5H28eB2+6rP+gtjHmqAMPImCZheeYXxHhayNxpjkuwxa9lULvlc1IWj9/OmAhMJh42J5313UpfVpHihADQhVDvmm+ca8TsXVO9FHlPgTiSZdVmZi2wMNJdmRzQ5VoPUArz1sporM2tAv2ebvRVcBCDFzO2DMFVg=,iv:3/DggrsSb5lPxMcTb2onGA3Gy5MpqwzbfIQ1zi9YjGM=,tag:D8Xb99nqIul7sfhb38rY6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
