apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:RFrvAIcR+gp8KV4GngYU8Wc6qI1Wice8UJjiV4FP7F1AdDiMmxAdkaFYGRLD/ebl6dzmEWI=,iv:Pi+aCmAZVHngievNmvxCZR0r356yrzIWWRJHMQ5RHsI=,tag:UjBJmo9EHXc60MzO5iCRYQ==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcGk1QlluNWUxUTIweUk4
        T3VhOWlYc1crQnd5TDF0WkVGWEEwUlZnY0NFCnJMbVY0cnp6ditrdytjTXJEcmFE
        VFBhTTlyS1JTZkNMVjU1cHhSYno4NjQKLS0tIEJ2ZEVhTU40SytpbDRNZnVhZ2tx
        eTNCaGtsd0tCSjRodHk1NlFSRkplUXMKkXKFSrvFB+dl1XOW0/3qt6nmy9K2k9I5
        qlmnhvdYlhNmTWDXfWaSvtMY9+CxyggGSdXe/YW7C4I+V6z11HUCWA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T20:15:27Z"
  mac: ENC[AES256_GCM,data:YhRekOQ4BsMc9Qzxp8bt3Qt2p0akU0Q3SgCS16oFXbiBH4Ap50Ege2BTYiIeiGsiGTn+FcBKle1JZhLA17oLzWvoFsd+I+H+e5WhObqRRrDDURncvKNBaDhis25vs7y1/0MA38ieN9B7YtJ3bpujHfyRSBIdcFK0NAR8g2mOvNk=,iv:uBvbBcorTO2KmLZjcavbkcpuZw2U6WUmS/bXjHwJGoc=,tag:fAv5L1oHvFY1ZFEgFI+QRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
