---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-adapter
spec:
  chartRef:
    kind: OCIRepository
    name: prometheus-adapter
  interval: 1h
  values:
    fullnameOverride: prometheus-adapter
    prometheus:
      url: http://kube-prometheus-stack-prometheus.o11y.svc.cluster.local
      port: 9090
