apiVersion: v1
kind: Secret
metadata:
  name: plex-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:Ne5YCKTgTnbPoiXzrA4piwUeRVrvLsLNmazsj00r9TcrX5e1IkJs30bivw==,iv:akklSIpZ1exuHZxSu6fllNMeTngb8P662kc9wf2lEVY=,tag:Vg0A7o3o4EHegJLMr/MM2Q==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:+Vi41l3WHO+0hm/Jy6+kCwVGAVLZkocj88+o3g==,iv:lYr6DIfWhyEVihrLwtJpolXR5B/Z8ck0fIgLQRIVW/E=,tag:JwXgzF5vbj+p3ofnAo/Xkg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQVhZUUg5TGtnZlIwTTIx
        UERRSGhMS2NNWUhoQXpiZGZENHZ6ZHEya21zCmJlRnNHZjhIWUkwN2tlZ3JrL1Nx
        ZEJuUWJobi9ZcE9FWHJmR2tRWmFFTzQKLS0tIFhnYVJWUHhqdTN4bDVHMURSbTNL
        OXZmUXc0RzVIcWNpTXNQdVo1eEgxTEEKpm53Q6RDeXajJoqc/YK4pvxcVcwhQlgI
        cUAeLVa6NusqLv84XxCD3VTqFsEmRkmDWfNlmwmApFwNW7jeOfEJCg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-28T01:26:37Z"
  mac: ENC[AES256_GCM,data:zWuGVl7z2bpUmxKeUqYKFOfLsEUEc0h7Rg6cS6skQSCYt3QYx7C85vY3SReHA58t2HYCMHHCPrT7aZbDGpRZHlAHHfuk84zNIyG6KKlONsL3uMqopOzzTUhnEq7gMkHAkFHCFY8TTm2h36Ti14YM887p0EQpGpsNawA8g9WHm+s=,iv:uja57tKs8kFD9RfcKSTNgM2PB7a4LOrAGNaNXII3GoA=,tag:HToSxZen0uiDCU4xS4Etgw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
