apiVersion: v1
kind: Secret
metadata:
  name: sillytavern-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:w1wW8Bs3k+1n00VQKDXi2prJ7Lc5i9fwqwFmUO01DPR8cmSJJyh2GcVjNw==,iv:dYzKcn4e5Zzdi+S9iGuRUEL5ai+MjlkCg97njf69dag=,tag:Xaht/KucLR0f+VLqDbIJpg==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:3zc0eGBYxRrtyLwdVYXhKQQbqL5+V+8Yk21n7w==,iv:WGr0fDVfqAFwYzBSN8iI209x4HU/BIN4MyFXp2NovEE=,tag:Y6XxBxK3TXZ4/OFBgKO/kw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZ1BLQXplSHVDeEsvK2ZU
        WlRHQ2ZiY1RoaTBsODlzOVh0YWpjdGNsT1YwCnBKVTZDMEU0L0pSdytWS0U3aGZD
        QjQyOFZ4Y3krVFFsWmsreXZ2b0RnMG8KLS0tIDZYNjZLc1dKNEJZTHNHYmRyM0No
        eHZGZVFlaUdmeG11S01iRGNScFEvYjQKIbbQQSN9tIuucHp4/y+e0U5jMVvlMxs3
        4cg8j8AgpBct/dSf4LGwoZkpH2+O5qeVyOf7xTssWX/sxY8DyeSfxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-16T16:26:23Z"
  mac: ENC[AES256_GCM,data:06qDQ0sx2wjkOky9JaOugQk1tkfNhs6GRDyVYti0vS25nwMiA7T9wt5/dJtG3pq0Ys1OZXqHm20L9bY32oxRfrPm97kRjQSwL5nl+ZcHJdfgRGoWAunohN8WoyAd4rbSC/RupzQxVCHM1O3fMnvj2Fg4puikYUZP+ODLB/1dwWw=,iv:+evTytnlPw0NYqUMPBS/Hcbc3/yv/d2BEmBraph6IPk=,tag:QfU4+MomTERMkz4H9nGQ5A==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
