apiVersion: v1
kind: Secret
metadata:
  name: gatus-secret
stringData:
  GATUS_DISCORD_WEBHOOK: ENC[AES256_GCM,data:iYXKsiyqusgtK8X8/kvne96DEYe40C0GLknbWTlpRIqubTur5UlQysmj2cndwuFvsYA=,iv:1Gh0taHPVNgB7WDwb2o1EUiBo0Dl7dfm4cGItAtJQnU=,tag:q965SmyAueRDXc3PimQBhQ==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NGdXckJVZVNycFNxb0RB
        RlRaeTdmLzJ5dHZHS1lwR3lMaUp5YW5EbnlVCnRkeTBrRjJ4cmpObkl5Y0FEcnRz
        eHlkY1NzbHR0blcvMU1mK1BOQ2lnbk0KLS0tIGJWYmg1WDVjTEZUTWxXVEpqRWxt
        c01qZjIzcWJLNU94Smtoc3hKdGsrU0kKtuMGs20rBdchYIk9IVoD9sIXrufES32E
        dkAtCyJEHCgn9FzBZigcGMZa9D9v9e5YleYpDbHtoxfnm1amXBxzKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T15:26:51Z"
  mac: ENC[AES256_GCM,data:UQQ3IknOstDVwzTRoF7CwAEecq1K+Z6jiJEh8Vb2fE4K88Rho+siImjhe5sVlL24KuHFyKCjlwgkXObf03OqnJiBgtwVAtX6YoyXsdnklUd4+nurxlw5cWGPHvXRIiDjJnKaDV1jKUJkJaY9qpkuP3lVg5ZDNXSN81gbovKUmzA=,iv:2gvKhCYCzDaZcBO2bQes3Vebzj9msiSKxMFAzX04fWc=,tag:pIV17kyYUSt7eKBj7sGcLQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
