apiVersion: v1
kind: Secret
metadata:
    name: gatus-secret
stringData:
    GATUS_DISCORD_WEBHOOK: ENC[AES256_GCM,data:97WveTFFEBUcOBQ3G0g1M8o/hGYCBvPxWN93vf6KKjo2Rm/cMWxjI2bQ5eWUtfMqQIvzzKPbl5ZnddYq0sWpc8plVA0hmrkVMTDOCZEMC6F4MPb2rzynHqFKQ1oU47lfU1Upem+7QHwUss849GF9jLnXPhR8KkR47g==,iv:EpM+Nw+ZYYg9Hqmvxk+wEjkLGCfU3yL7fvPabIV/7Ck=,tag:CcBlhvAJL827ZO8ILoBuMw==,type:str]
sops:
    age:
        - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NGdXckJVZVNycFNxb0RB
            RlRaeTdmLzJ5dHZHS1lwR3lMaUp5YW5EbnlVCnRkeTBrRjJ4cmpObkl5Y0FEcnRz
            eHlkY1NzbHR0blcvMU1mK1BOQ2lnbk0KLS0tIGJWYmg1WDVjTEZUTWxXVEpqRWxt
            c01qZjIzcWJLNU94Smtoc3hKdGsrU0kKtuMGs20rBdchYIk9IVoD9sIXrufES32E
            dkAtCyJEHCgn9FzBZigcGMZa9D9v9e5YleYpDbHtoxfnm1amXBxzKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T15:39:09Z"
    mac: ENC[AES256_GCM,data:sZIHscQQBcM/rtQoqmjXhckoTgcw/Uexzjr4herDvEx8DBieclPj3o0fCwxAEl0ZRbr9gVeReJLm5aHYVOWoGdHgHEgFmdVpjESzwfwMsIkzZE9W5XmqKJFnAZtq6n+aeb3wjZqhkWYuUGMGCb8gtpbD9lHn7hgBh75TtQc4acQ=,iv:RaZy+ZOkmwvWSNJBuzhrZ75siE3om0r5dErFBPzhSLo=,tag:rtPoXZVWhGceyqn9HUK4Zw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
