apiVersion: v1
kind: Secret
metadata:
  name: gatus-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:1L3i42PgHV1Hp/VZqFM32Q/drOa0o/kZ5ItLTjDipFXfinNSxFlss0zMKg==,iv:cOxLku8XW5n5k3Qg27iFMIYhJcWIJFwWGD8v6FH9Uk0=,tag:HRxx4cWMIwvtqwKtts6WqA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:PjEQPHYXA7HQm9nyCbSdc7tlRCQdS9NNGUBcow==,iv:zBItyGmIUhT31RjS+hzE0Kc7ByifWSzDvpPpVRsBG+4=,tag:QGWt3o9enaLP8fOPDJAGzA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbFh2ZUIvbFVicUpaK043
        bmNrRVZXajc2bUF5QjlnVkRMeWNOT2JzZ2gwCmZMamtQa0ZTaXBpbE0wSGxXMnB1
        VE5ZSXFoOU9Idm00QWRVUncvMkl2eFkKLS0tIDVKM3MvYUJOTUd3TGJMWDd0R1Y5
        Vk1HbTRTNlNpejdIaElBTDgxTXdtMmcKI4NwX3pfYRcblDWYh3XSGQbSOpCeo/l1
        mHUcwBXKDZ+VUTJAItMuPFAc5CN/g0A+mD2AUSFEUaK/UaZBtAdU1A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T18:54:04Z"
  mac: ENC[AES256_GCM,data:9RSxcmtaEjJ36jkHza9gY5niw/sXcyjKDxmZR7wwHVNWrahAOljt929gGjjHhPVBSHoSI5UXpHbA1MFRGgRos0nILYvqohdscTzrTb8RP49unGcFndgP23APpJmtORQn9I/C9ZT+rWEsi6vFE8IDGz6o1pOlbfu/eWuCpnBC8og=,iv:bYRFCU6avYQz1J24CxR6ujynwI3gBqE0P0jwmZ0pF8E=,tag:zi7z9MJ/sMfckeiaYcU4sw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
