---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kokoro
spec:
  chartRef:
    kind: OCIRepository
    name: kokoro
  interval: 1h
  values:
    controllers:
      kokoro:
        containers:
          app:
            image:
              repository: ghcr.io/remsky/kokoro-fastapi-cpu
              tag: v0.6.0
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /v1/audio/voices
                    port: &port 8880
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 2Gi
              limits:
                memory: 4Gi
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      cache:
        existingClaim: kokoro
        globalMounts:
          - path: /app/cache
