apiVersion: v1
kind: Secret
metadata:
  name: kopia-oidc-secret
stringData:
  client-secret: ENC[AES256_GCM,data:xWwmwG0m1OQ2E5VN2G2FkP81cfV+r6nIIcq/swaIY58=,iv:Ijjg98okzP4Vs8slGVg8K/pLhai1WGKQ37nMhT6e0rU=,tag:ySZLTyeMNP12tNSHiZuUjw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzanBYeFBjWFlFODNLcDdL
        YkVsaVRTWm5sRy9oSjhDMGpwREY1M1ROdUFRClc4YitpZkRkTDRiekRZRW5sNUxL
        YlZoT3BQNW1vSERHbnVyNWduRHV0elkKLS0tIGsxcFJjQjB5LzBqMG5sR0haTnd2
        WlhTU05ZRzBLYS9NY3RlaGljeWtmaTQKgaUbrD4y61fJxMYsjXWuxO4bDkC59G7Z
        TZ7XdBAdMxActHszRmDUDHgGexd7rwMWOzBVH193ZN6h5myo7xpUHQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T19:04:07Z"
  mac: ENC[AES256_GCM,data:V4Bsjl67dfpf/N4a6zEyT3kEI64A9GCuF+59YuYsS0ZZE8q/OAonYUQP6ENAi0Hv10CAOaQ1XnuxTt4XP8IbJdFSeCCaEsaurlACBmwBOWLUxxwREx3P0ANUX3IC5iVmnhbgqgY5pZkREpJVRxxgU6pSd8wg07DVpqL6uRSAHM0=,iv:jsuKHrhhqs8l9j4UL3fTklMvX3ZcTG1auEdIJbbLK3Y=,tag:qMQIPcTjEU9VwePxuFYo1g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
