apiVersion: v1
kind: Secret
metadata:
  name: kopia-oidc-secret
stringData:
  client-secret: ENC[AES256_GCM,data:WXPNaicqN/RS6vIPfFe2B4WwSYgG5hvbtqXytbdeWDJ4YTsrzYXYFA1Y,iv:wLPvvw8SE6w2KdVdSyXodNWUkmeIws8GWG+nk5+R1GU=,tag:j6Js/wEXsMK0zmNSdHtq3w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzanBYeFBjWFlFODNLcDdL
        YkVsaVRTWm5sRy9oSjhDMGpwREY1M1ROdUFRClc4YitpZkRkTDRiekRZRW5sNUxL
        YlZoT3BQNW1vSERHbnVyNWduRHV0elkKLS0tIGsxcFJjQjB5LzBqMG5sR0haTnd2
        WlhTU05ZRzBLYS9NY3RlaGljeWtmaTQKgaUbrD4y61fJxMYsjXWuxO4bDkC59G7Z
        TZ7XdBAdMxActHszRmDUDHgGexd7rwMWOzBVH193ZN6h5myo7xpUHQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T17:11:16Z"
  mac: ENC[AES256_GCM,data:Fs2n0fZcSAIbRqjKNq/V6gGgPhqlW8KOXv1SCkoAHFHYMUki0Jz35ANUIn6YFbhxA3X1HVyRsmJ31kWjSS1NodLni1Oapw78rnzaS8iT8Pf8NvFFes06XEGgrQz5exg3tbNYptRsYyhkgD9cG7nj679InwTzCyGPNpG77pJ4Fsg=,iv:ahTdk0wXEdcELwLc77dBA0vnoQPLzFTb8RAtAjwz8P8=,tag:l6ZOKrENqaM16kzw96d7ag==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
