apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:tiFsykyh9eM9aygpQ9M7griIYacL7CvnJIyiLPfn2kVrDnZDzITzb3eQxQ==,iv:xSvnedTx4LLdbeJqEpkIyg0FfZ3OcWBER6qCQtryHtc=,tag:zUyegK6GgQk2nuiMMw13cg==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEa3B5aUxML3F2YTF2a0d2
        RlhGK2dldTExTTkxOU5kVUorR2RrMG1zcTJ3ClhRWmd6eHJ6VjJscGFKUzZ3RHVs
        VUEydmZFVW1CNzk4N0l5NGxPVTE3N0EKLS0tIDIwdW9ISTZXZ3U3VkhKTC9JM3Jj
        NFR6MVlNakNhQktZcHI1SEtaR1ZkMlUKBHKd57EdqKRitWM9WwbIecl6NlyLz/1l
        +/DntACwaCJxnW3VQHf82ecyUGxe8OT1kUnO3/1tZr52huNvDb1VbQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T15:31:00Z"
  mac: ENC[AES256_GCM,data:wA+AhCHPvtdp4kY0Pkj/vQNBlccnLQU7w2GWInDjXVzYhlLz6YYvTqJ2B71H4jbneGVa40XR1HDT8iAGAAPVW8tb7Pl4ptwhZa1rsFH+lCrKSiRsf24x73rZ2USBQZb3ZnvU1Z5v9CrL7AR02psoUmCb35ecq96ihO/3bTQAGlM=,iv:G/Skyxs8sLBo7EZLPWtcpHPgiRqzllRBZDQOgYgSsjE=,tag:ioRZYGO57lHYOppFbZ8n4A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
