apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:CP3awLtZlQpbzL3RjXFAEYkvluzRT6JoxlpQ8yyOAI8ZNdJtVSBL5IyKZw==,iv:1jxejfuDJX6QKM6GY7dVMNoTMfqDJmF/3ibU6FDGPu0=,tag:dwqRiclLGkqrJv+Nwsdlvw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:6ncgrxwbieen3/v6BOW/w8t16YV1r8kNFaMD6Q==,iv:kjIs1+AenkgH0fkRB+0Fn/bAfwJ4d1Lm1RhZuDExSPk=,tag:KMkZKzpgp3v5BpggUs0aBw==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWmRndXdHQ0phUW9rQUNZ
        MXM0cERXczA1aTNTSGZ6enhOMk54RmcyeEhnCnRWUmU4cUZjZE16a2pJWWJidWlD
        TDNjUEhYMERrLzFRdkF5QmJ4eWw2c2cKLS0tIFh5NUpFMWhuZUVxaUV4UnRnWHhi
        TzV1endTVW1KZGVnQ2QwUXY4TThGVEEKkJ0SJTn6whsxG595PwA7rAOEyTd5Ur1+
        5ypoVe9PQyUeym88oGbJSty1BzXrN2pFkSSqNkFbuEKLK6rsL3qLRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T12:22:29Z"
  mac: ENC[AES256_GCM,data:RwEpD0pN2DCRvZ2/F/I5sF+sHt5eK1kPmx01WCSd+FK6zGn7EBhXstpnBHYh7O0hdhc8cojZHjmgEhwvbSynUay492Fqe7lar1Xo9yCjyDvNc3Q3Bj9nsbIUZUb1Qyzo5wJTpeAUOc3jRh9S4sWbHrdiDLca/UWAllObXIi4Xwg=,iv:i4Qv6wqwFfs//5NOuEodZL8ctHfKFkB/LvuDOYgUqyQ=,tag:TBb0UQWIrLMyUJPcawGpRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
