apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-secret
stringData:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:Bp2/OBjYitiUQ6UC4vaAco66gzy8hXzbxFqyNmMI2dw=,iv:kIM71PQGoz0WRGFlP/MC1HDIpfG+3d+b9yjG7CxExZo=,tag:n61C5p9ej+OE1kIWWXxn2Q==,type:str]
  MAXMIND_LICENSE_KEY: ENC[AES256_GCM,data:TG/dPAhtp7TevrLFB7vL5htWl48pSwS235uOw5mnmni/mJst8nYLyA==,iv:9lSBAaF58i1SG1vb+ye0uXzbiJQfWeyDsBbHqGj+eW0=,tag:we7M1JSv/F2aCyR2FIcuaw==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cVk5VHk2Z3JVYjFMZ0lU
        cGR6QmhmSW1TY3dQZFJzWmZKUThBNXdXUjI0CkN0a05wSHhQODBmRVhSbGtkcFdv
        cHlOMmVIYitpMW9zRm4xektRdnYyN1kKLS0tIDZJa0pmeitsRERmcmRnWEN6MDJ1
        KzJNdGdHOHhrekdvVWd1cnFIeHJGMlEKro4UeuEh7HGN3tR+PMRwnyRUoXafw7/L
        WasTaI9adMbVraovSUfX3nr6TUmm4hV5kbA3/gnG6qUymyYceIO9bg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T21:25:18Z"
  mac: ENC[AES256_GCM,data:n0TZjLNst1C6lpeFJPlYwPKYrvrI+siS5k4DHAVDvkNBiiKdENkEDAvLL2MPTYig7r37Xi9EdPQiO99io4tDmcHfK6RFrjBnxldFciyx72gLxqM+HU1PznRiHR1+jD9Fr/lBVK6QjD09qjiBfWPkqOmcX1y0eQuduelIbyFZn7A=,iv:9btGk2hQ8wwk8uj0eXSl0NmdZTY9NZ1v8Dj2k7k11ps=,tag:h6cLeIyn+PuQrb4RY9d4lg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
