apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-secret
stringData:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:WacKez78309WU9ryLn4ReRQLnNb55jxkNM+WWoSxWl8=,iv:mNeVenG1TelFv8AjcpwRheh3oJ7hRRg1PmehvZScAZE=,tag:FE+RMPaQ4bhYmwxGyn37Wg==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSFk5U2xxY251QTNoYmZu
        b3FjY05WMXhUR0o1b0g3VFBVQis1VThLa3hBCkR4MC8yYmgrUktPbldoNEsyNEx5
        a0x1amtLb0dWZFV3aHMzSDJXbk1ma3MKLS0tIFBkYmJrendSQVYzNWFsL1BhT2tw
        UWVORVB2MjlSVkVUeS90SFo0TjRhUG8K4apAnd6Ess0+E3kk99C26M9GqT6FSMfh
        G983YqXdr1giZrERTVB9H+rZlou4NzO59FW6GkAwdL4NaMWCbOhOAg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T20:19:26Z"
  mac: ENC[AES256_GCM,data:nbPWBufu4HplZWxoe4t45WUChawj4T1IUAV6sFCfhMp8FaBnncHSirj/2oRQ/9M9M/NpCI4FnUJns6+heSnyTjCxOHcubMtxpoPqOtoGOWXHfT1Vf8SS/Dm7dBbR4NtqoY0yrqqpKbYpgcUb4zTGKpmIBPUDCF+ur7Oj6b2rkA4=,iv:mUAM3whhSX2hZf6lOLlKqrb70hH/38Gr0zN7adldFS0=,tag:xh0YCYFgxPAm4YBvxp3MHg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
