apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:kJnUKImtVqdKRixM0VGeICWEA37sgmnxRebAriWe+DtHWdL99LqjkdBjTQ==,iv:2xEeVQqg1/ZTSZB0iQ3QqxbJB05Gxft68PHrFccKBeo=,tag:SVVFJCsOoh4wHJvWM2XPKg==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:HuHDCc1QVYo3vG6vMaHKphofDieZk669GyE4sQ==,iv:YgKo3ruRXinFLuhJUuypw71WhgmUDHXnJo7ewdy0+jY=,tag:KeXmSofNQ7Gnutrq/1FE1g==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQck8xYTRvOVpVbUxBZjJR
        Y2dRRWhpU2hBVGpwL2cyUUFVTWM1YmVvMVJBCldWdXhDWW9RTmc1dkREY1BZMkcr
        VCtLc3QxbEZEaHhqSjVEaXRSSWZPb2MKLS0tIG1kV3pEYk1FSS93eHlYT0hNVjNj
        Y0tLV3hpVzIrNGMvT2JobnRua0lNdGMKQFebUPJw+OhDU9Ht2Hi780mgpac6rUcd
        HFjiE1rfLXdMasY4SIpPRDkYae4QV/Cdgc006psFZXql8Ja+nNT6/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T23:35:19Z"
  mac: ENC[AES256_GCM,data:Al6ICLQCAnAJeNqs1iWXpqg2imheioz/Zp3h7q4NPBukhY5Haum8ZpuKYlyAurKxY6bE3GdIagHT5jnW6Nsp7fi1atc7/00fmJDK2pRinvn5LkwmBcYjUTFKWDcF/Q9Uu8BnO61GNr0KYsCkpE63tYnQMyl4ZXTFc3lDPTr+Nc0=,iv:gR+3T5Hz1YGiuuUxaGUZLd3exfpvPOemxSClxOzeRug=,tag:AGVeyeKhH1nWW1ITgwSLRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
