apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:zAz0GkxN8rzpsbXtLc3iERlHZRXpAuGlncD8p5PIYJp8Z5qKTpCY2n2ZUrs=,iv:ZvzS5cpBjQW2/SejV5TqEoZP9IZeGl84fHO6Cfd8i48=,tag:K74FhIh2c2umkJaEUnvSjQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:vIg9w8gKsoJE5/v9AD7fKm6B2/7sCAgLtK43iQ==,iv:DmgXX9uU3oLsq3kYqkH0b7LVoJ07NHiMr1T20H6UccM=,tag:QKyOvhyWNlrqQz3XhH9R0w==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QWl3V3RBOGFyalppTGg3
        ZWZ5Q2ZVL21rN2dPL3k3ekgvNmFqNFk4cUVBCjNCaEtoeHNMQlRqOFVvOTdDUWtB
        d2tqM2g0N2E0aEVjeFdkZXgwaHZmWWsKLS0tIDR2TFhoNGkxbGN2OWVTS25RTTQx
        RCs4R3BuWjN4WkZkMEdFYXZkOGpTemMKjMmtNDvm3wRjLU9K5YEED1r4RnfZiaeK
        xdnVmNFlSYd546y9cRnNq31Yxi6pCkCBe1/Au6pKh/CfZjVa8jGtxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T20:21:51Z"
  mac: ENC[AES256_GCM,data:wtJR88n/EgdHG4ltvLOkaqz5wIRYeDbKzML6K4fs2tPfPpFGSR7u3cQAwRTFxear/wbKIHwvR71DMKzBeZ5CMVWzgEWSNtOUCXJvMyHtp4oTulHI+pYXr1p3N9eP2a83PcGcOMZw5ogEaGJWQ6IWc2k7nv7CdItQGoFoAKQ+p0U=,iv:zTulde4rnFQAlbXZf4QgqtQ2pqK/of1pvS6WkI/qZJ0=,tag:wbZt6UYwHdImxjsb8jE9aw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
