---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openwebui
spec:
  chartRef:
    kind: OCIRepository
    name: openwebui
  interval: 1h
  values:
    controllers:
      openwebui:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/openwebui/open-webui
              tag: 0.9.2
            env:
              OLLAMA_BASE_URL: "https://ollama.${SECRET_DOMAIN}"
              ENABLE_OPENAI_API: "false"
              ENABLE_PERSISTENT_CONFIG: "false"
              WEBUI_SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: openwebui-secret
                    key: WEBUI_SECRET_KEY
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8080
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1Gi
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "chat.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      data:
        existingClaim: openwebui
        globalMounts:
          - path: /app/backend/data
