apiVersion: v1
kind: Secret
metadata:
    name: openwebui-secret
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:O7kMe+uCCxLS+8orGF65psiXrVuUi+b/Tg+/t+MElcYI2DicD94NDwurcfG9ifK/,iv:lYuit/BK32pdQFbz/rxSHsz49aW9GzFtzG4sCp89Lr8=,tag:sPW3OlvrOQaq+aZuP20Fpw==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:2Scc1mirOWHdDH+5FQPiKNlLM2Y1C57fo51M1r5zBzEDmg2W,iv:yiZ8mTL0+++hHIMRm+flmHkDJoAtOjR/FlZQxPs+LxM=,tag:sd8mMLHXPbN4MQZ28RJxcA==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Io3vNKfvOdYKmflNaPFxCvptKKKrTfM/iX7+XPL1JMU=,iv:/1e+6EbGx6rl6SqQ/zNc8Endq9L1j7rhAp4Hw+UK468=,tag:VT+a1DLkVrMHGUr5Pj7KFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVkg1ZUhSMWVBaURqMXI3
            ZXBJSEh5eFduU2VhcW93alh4N1NzOENRcUJNCmhjRVRPN2txb1FYMTBsYnlaOUdZ
            QlZ2aDI4RWJRSDc0amxNejFTaUhrQncKLS0tIGwxM1dvT0ROTTNMcGhKRzhLVG1x
            SmwvU0trYVRPcVBseGZ6YzY3UnNVc2MKFZBZUCZOl6AFE8del4VStxRGk22wMKwq
            x3Cifp8vt7lBDzmODPDV3qDlVh9rfhpVvjwNeNvny/5i1nMnZcdtEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T16:30:57Z"
    mac: ENC[AES256_GCM,data:IsV3v7UfZd0QO7MlK7tbDsUDGBVL5TU7eSJm9DrqOnOl4VACDkjewPdnEXEviUnmNdWenBlpFEXCGwSVf5sZ3sAtGBSO2+0ylxhC6dFWwJr/JmBva5mSkvFeimBXyUqnlxI1SjELCIdO7RFCA1hUZUKsol6EsID/1CnEIXZLl/A=,iv:bTTxF6nben0ob0EmE55rigghvgx4LDk7H5+kRsoPjRc=,tag:QVWgNmOfFPHNjZo6cSb9Qg==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
