apiVersion: v1
kind: Secret
metadata:
  name: openwebui-secret
stringData:
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:O7kMe+uCCxLS+8orGF65psiXrVuUi+b/Tg+/t+MElcYI2DicD94NDwurcfG9ifK/,iv:lYuit/BK32pdQFbz/rxSHsz49aW9GzFtzG4sCp89Lr8=,tag:sPW3OlvrOQaq+aZuP20Fpw==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVkg1ZUhSMWVBaURqMXI3
        ZXBJSEh5eFduU2VhcW93alh4N1NzOENRcUJNCmhjRVRPN2txb1FYMTBsYnlaOUdZ
        QlZ2aDI4RWJRSDc0amxNejFTaUhrQncKLS0tIGwxM1dvT0ROTTNMcGhKRzhLVG1x
        SmwvU0trYVRPcVBseGZ6YzY3UnNVc2MKFZBZUCZOl6AFE8del4VStxRGk22wMKwq
        x3Cifp8vt7lBDzmODPDV3qDlVh9rfhpVvjwNeNvny/5i1nMnZcdtEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T12:28:23Z"
  mac: ENC[AES256_GCM,data:vvda3VFdLBHPjXwDPiumiI1GKtFFAk4OkoTShEFDfeS0ShVk4NttXGZQTfdcslKHFwWR5tS4+v2znIw1GSHlOzq3WKJAHwHpZBSbDDF09CHWF3XaKwXyJjxD287uA0jF26o/CYKNXsZlGIxXuvopkdvDC/dVupZaCDjhJbW7AMI=,iv:b4S/3Iy/20T7wJLG3O5wjGMpirDhqgC1Ou5wmB1zqos=,tag:xHr/bIhgWZJPAnzAtg01VA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
