apiVersion: v1
kind: Secret
metadata:
  name: openwebui-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:h6/iN3/1mTEfmqbLXsKpMuc0HIdOyQFhJtTBx03phzEvSqhLUmEcHOPCxQ==,iv:766NUEFgYvxYV0cAaew5zEyKMvEEvyabM4rfvbJmDko=,tag:28HOSYmMJ9LShzLarB9zow==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:tciVMteCb3YNw0TTJRojmHc78VByMRFXe4wkYQ==,iv:ovPe6leBlV0UsanPdbPrDOX0COf7TRft38OarWCoR1w=,tag:jfJ6siBJ5YepMpSrQgqBmg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0R3dkUG5kakd3WDhHUUxn
        WDQrUGlTMWNLeTJoY2JnZmNHSkFlc1lTV2s4CnlJeHFjR3lwMjNJS2UweUt4UU1G
        dkNObHBKcmJ2MUR1cXIvOWR6b2F5bzAKLS0tIDE4TFdXZmxRM0F3SWhSTkoycHZM
        bjJ2V1lzZDMrS1JaMi9FL3JEVzloNlEKeevDNH0mlLGPyR8/ZauwlUMYxXJgg7uR
        2LnLu1HgNsspIHs42rxyWTG4FE2Eow65s7V7ODYy3Jzuier7k5ICQg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T18:54:04Z"
  mac: ENC[AES256_GCM,data:uDjOyPAj9ucrm1x+gc0ZHxb3BNf5sxzi3RVqAtL/vMGi2iEy8XkS/03W6mXUMEIOYeqpYXrL36PAMYPG8NzoWSwS8fWR9iz3j5tpU8THIWgEa4jyk6evO7T3gcXDACT/wG/PYErrI+k9xae09+XAgTFi3wztDXcK9TjARGLpG9s=,iv:nT3OiYTQl307PemheNf63wPp5sCeeGiDoc7hbuSiIJA=,tag:3bAjt/j0C3ObfwGGW1d79Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
