---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: volsync
spec:
  groups:
    - name: volsync.rules
      rules:
        - alert: VolSyncComponentAbsent
          expr: |-
            absent(up{job="volsync-metrics"})
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: >-
              VolSync component has disappeared from Prometheus target discovery

        - alert: VolSyncVolumeOutOfSync
          expr: |-
            volsync_volume_out_of_sync == 1
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: >-
              {{ $labels.obj_namespace }}/{{ $labels.obj_name }} volume is out of sync

        - alert: KopiaMaintenanceStale
          expr: |-
            (
              time() - volsync_kopiamaintenance_last_maintenance_time{
                exported_namespace="volsync-system",
                name="daily"
              }
            ) > 172800
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: >-
              VolSync Kopia maintenance has not succeeded in the last 48 hours
            description: >-
              KopiaMaintenance {{ $labels.exported_namespace }}/{{ $labels.name }}
              last reported a successful maintenance run more than 48 hours ago.
