apiVersion: v1
kind: Secret
metadata:
    name: tor-relay-secret
stringData:
    EMAIL: ENC[AES256_GCM,data:zeW6x7kKoBJdPfNBZckGyzByx9QZELY=,iv:DLCK+qOL2mvzq9ixTnYSxRyPkt9EHj6XjrymOAI64eU=,tag:aWG1YdLXcX9wLAliUZD91g==,type:str]
sops:
    age:
        - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzY0RLZkEzd1IxaGJWSzMv
            S1h5QVZYZFlmbE1YYzZnT0JsTU05VnBuY21ZClVoeHNQaVFXOVo4QmZkRFBTNWpD
            RTZXUnFBa1ltQTI5aXp3VFREdUYraDQKLS0tIGt6V0FRNUxYRG9WVklmR2ZUQVZ1
            YmVJREsxWnAyemZOVEltMGRKVlFBaEEKQAuaUGpAIGBWPO8PP0hqeS3WYUa1a0o7
            k+R2JostBvBTD0VWeTB0YdrTLN9Rex68MLCqPvy5LAoCx6lJrgH5+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T00:53:49Z"
    mac: ENC[AES256_GCM,data:+tUK89L245vX2k2nHnu1ecMbJpEvV2Hwtdb1UM8/Z4ZC7h6T1RTLW7ZZ4KYAGrHQQMIt4L/rA/iCI0nGJKxL5PcAeIg/l+loksnRTP0jtWv/Y/V+XNDE6FFN5qXf4f2K3GBJEkFZDeVSyKuCncW5yJDrxQ/JRaWEto4I3hYQGgk=,iv:IW5eR0PUCYGpygigzvATGoBFFIEJp+jdrQnVFjLmZto=,tag:fuVgjqx4g1nNGl6jYwjz0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
