apiVersion: v1
kind: Secret
metadata:
  name: agregarr-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:NXGp3qejCPUFFNBlQRKI/hn1AVftHBkbWIZ3T2B5MWXrEfFo/MsJ0LrKusjLLvor/vFdfrZZTLo1EGyM1t3Qow==,iv:Fr6bCZnXev2F2zpmO+y6VNnfo21pKjhPrAhHCjtTwIY=,tag:bsl9NXOLtuI79EDb/LMYvA==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:RiBGnGiaq/o=,iv:c2tE9jRUY1Lcl+ZUWW2dmVf7XQfrqcXr+g1fdHdOQ8s=,tag:h8wUf8xnmXDQdu9V168/Wg==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Z1JiU2xaMktheFdWanQr
        VklzQnVxa0RFVFowNnpjb1htbyttdTNJZHlRClhudExGbzlFNUhLbGgyczBDYkdG
        NXI2ZUltaDhXY1doR0RYSStKVEw2MkEKLS0tIHZwRzVTT3BXQzVPdjcya29JbU1n
        bWh6Rm9LQzhUTWlHRGtSS2RvUXgzN00KYVCJ/frGB+YljD7zWQ8sJqgvNOLb9QCQ
        u9moYHfAwCBb7LUcjfgKbYr8NL1KBd634hFo+GwtatKKxEbHerAz9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T21:39:52Z"
  mac: ENC[AES256_GCM,data:M0gfCacFzc0+QQN3quMb/NyZgzT0YFzYXRKONVI7Dz+4dLLnq/vfFCAH3TbLO0wLiqlaTBsPxmYNFY47ApknkJjR09qAfYVkrxVBeGa5b7Ai3QUNcPfNhu7CeftxCoUIMVHq0136oF4gQ/sYih0GLSLM9bSbd01MVdcIhiSXxW0=,iv:RrHSdjXHh6Wkbg73CrrVaSU4VOQFyt1jI2GN8yzuoDc=,tag:2D5IHe5uo7MyFQwuRvIpig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
