apiVersion: v1
kind: Secret
metadata:
  name: agregarr-volsync-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:8JYEtuUGb/YkAWKRkm5CoSvzpdEfoLPyc/wDX/0xW5Q8bIBKeAtggw42/g==,iv:sjFIUzAUx8RwfZGFpG4tCP0kzYQmDv0rhrDDXz5MIvA=,tag:CGZrHc7GqcGTBqNeHHu06g==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:ohFx+L3oYUx8zp0hx8zQHcJNTmDYl6RZhydXFw==,iv:+lngLutluz11/U2/Ls6Gxuaznflu0PyJeAhLnTyvq2g=,tag:QIsoR9b0fSTMI247X+usmg==,type:str]
sops:
  age:
    - recipient: age1j8auc0sy76etmugnrnqv7j0v9de5l9ffswnqj7ndrzqndh5rdpjq5atgj8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZVNjVGc3UzhuWFVhM2lo
        QlBVa3NkVDhPMWxYNjcxeDJIY3RRMVNmNjBFCjNtMGZOc0d2M3VaV2dkV0pzVExj
        MXBmMjgwem5KRnM2em5oR1pRaXlHRVkKLS0tIEFhbkFrTEVVTWxrMzZ5MzJzV0RG
        d3AxQ3FvUXdoZmFBb2RzMHV5bGtLTkEKOpuOi/OLBphHBC2zXoHiUJZeiIky7H73
        H8LXmV2bCVQdisrvIlZN/wgFo10RIgYCeHkxuii8gVoSFDLjFpb1VA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T22:12:30Z"
  mac: ENC[AES256_GCM,data:DFQj6j4CcgF6Ijh8ucj/bQhvKUTXF0Eq+RCQZFwSJmu73eKHCrFL+ia0q6beWCnOYTM255z5Iefz0ysbq8U6FLQ03TnjkjCZM0WEd1MeL94e13ZcffHn8h50jBqwgB5QK5bZnFQOwcZ+0dDw+eSKDKP0RbnU02mZsSE0/4JEmB8=,iv:jivBJcn1yJt/7U25hNxz30M31GONv2AXUpsp2zrCznA=,tag:Gl6ReiSryjMS9nNN3ZDb0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
